### ISSUE TITLE
[FEATURE] <DB Upload of existing camp information>

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#103]
@guilbep, Please note that the decision from yesterday's meeting was that UNHCR is working on making its API accessible to you. Thus, they prefer that you pause this work until their IT expert can speak with you after fixing the API. This same data will be read in, but they want this to be dynamic if it is possible via API.

GHG General

Be able to upload existing camp (site)
- [ ] coordinates
- [ ] names
- [ ] Nombre total de personnes
- [ ] average number of solar hours
- [ ] ideally in the format of Excel with an agreed template.

- It should be updated only once  (via an update to the database)
- Here is the csv that UNHCR provided attached.

https://drive.google.com/drive/folders/1MCzGF1JAC-g4ApliQ_PnNokTq39BvYRK?usp=sharing

@guilbep Happy to have a conversation on Friday to discuss

**Comment by guilbep** [comment]
Hi @ctobin111  @andreullal if you want to further discuss the subject. I strongly encourage you to use github. As it is more 'open source' and will last longer than some email.

Hi André and Cara,

Please see the updated/cleaned data as a csv: https://drive.google.com/file/d/1zCdKHGH77F7kKNLne-J-0cKG7BKrTGPZ/view?usp=sharing

We went from 24MB to 12KB. And from ~200000 lines to 234 site.
	- We have some weird location like: 
		- Federation of Bosnia and Herzegovina : Entity
		- Meybod : Shahrestan - County 
	- Not sure That’s how we want to display the name of the site.

**Comment by ctobin111** [comment]
@guilbep, Please note that the decision from yesterday's meeting was that UNHCR is working on making its API accessible to you. Thus, they prefer that you pause this work until their IT expert can speak with you after fixing the API. This same data will be read in, but they want this to be dynamic if it is possible via API.

The number of solar hours will be used in the Facilities calculation for the Solar column. It is site specific.

**Comment by guilbep** [comment]
Update February 2023; while waiting for TIMS it was decided to move on with the latest data provided by unhcr
It was implemented in  4316c26 feat(ghg): add reference data for unhcr sites/locations in branch (feat/ghg-end-of-phase2.1)
