### ISSUE TITLE
[FEATURE] <Assessment to be set as 'Reference' >

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#104]
GHG General: < Choose one assessment per camp 'Reference' >

UNHCR has requested that a baseline be labelled and protected. The Headquarters (HQ) wants to be able to be the only one with able to edit this so that future comparisons will not jeopardize the data.

Ideally, any user would enter the information and then HQ would approve that as the confirmed baseline.

- Translation:
   - [x] Admin chose one assessment per camp as a 'reference' (using the octagram icon) 29093af
   - [x] We chose the assessment only in the listing of the assessment https://unhcr-tss.epfl.ch/green_house_gaz/list#KE 29093af
   - [x] We show the reference octagram for common users  7bd51fc
   - [x] Once an assessment is referenced it is made read-only for everyone (even admin)
   - [ ] having an historic of who made assessment as reference (log of user + date) (10 modif a stocker dans le document)

**Comment by guilbep** [comment]
@ctobin111 It's okay on my side What's an ADMIN. But I think we may have a problem with that.
What's an admin for UNHCR ?  We need to identify a unhcr login account as admin. And I'm not sure how to do that.
We probably need to clarify this point

**Comment by ctobin111** [comment]
@guilbep @charlottegiseleweil I will organize a call with UNHCR IT (Marc Uygur) to understand how to make UNHCR admins. Or perhaps you know someone else?

**Comment by guilbep** [comment]
Update: The issue was not resolved; tickets are opened then closed on UNHCR side.
Let's wait for TIMS and some feedback from UNHCR before moving forward.
@ctobin111 I consider it done. If you think we're missing something please re-open the issue with more information
