### ISSUE TITLE
[FEATURE] (Facilities) < Warning msg >

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#105]
- Check sum_Baseline_kWh ==  sum_Endline_kWh (Grid power + Renewables + Diesel)
- If sums != --> Display Warning message `'This comparison is not valid because baseline and endline have different energy demands.'
`

**Comment by guilbep** [comment]
<img width="1688" alt="not_valid" src="https://user-images.githubusercontent.com/161889/198659699-5b7768d4-edd2-4baa-a57b-94cea9e3f08c.png">
It will look like this @ctobin111 .

By the way. I find weird the fact that the warning announce that we have a difference. But we don't have any information on how to solve this. What do you think ?

**Comment by ctobin111** [comment]
Hi Pierre, yes it will be up to the user to put in the correct comparable data.
