### ISSUE TITLE
[FEATURE] (Facilities) < Add diesel estimation>

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#106]
@guilbep When litres of diesel is not known in the field, please add other optional fields:

1) generator size (kW)
2) operating hours (hrs/yr)

New Equation: generator size * operating hours

The unit of the equation will be kWh

@guilbep  - Add extra fields for inputs in the "New Facilities" creation pop-up : 

Add below "I don't know Total of Liters used" + the 2 inputs (generator size, operating hours) that calculates Total_kWh of_Diesel based on formula above
<img width="689" alt="Screenshot 2022-10-17 at 09 48 58" src="https://user-images.githubusercontent.com/18381609/196119221-bfabe7f2-e040-4a66-8d47-ff0691f29120.png">

**Comment by ctobin111** [comment]
@guilbep I will be providing you an Australian reference to this. Ideally, the reference could show like the others with an information icon.

**Comment by ctobin111** [comment]
@guilbep Here are the equations. Please call me if you have questions.

[EMISSIONS BASED ON FUEL CONSUMPTION DIESEL GENERATOR.xlsx](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/files/9880086/EMISSIONS.BASED.ON.FUEL.CONSUMPTION.DIESEL.GENERATOR.xlsx)

**Comment by guilbep** [comment]
@ctobin111 btw it will look like this[](url)
<img width="1705" alt="intervention" src="https://user-images.githubusercontent.com/161889/198640464-a736a3dc-0c9c-4cf7-9cd3-42973f8196e4.png">

For the baseline table I took the liberty to add a '~' and the computed number of litres for the diesel. 
<img width="1639" alt="update_column" src="https://user-images.githubusercontent.com/161889/198640474-f1fe85ca-cfab-41ab-b0e2-a6d0728e3e6f.png">

It does not impact the 'endline' intervention
<img width="593" alt="I dont know" src="https://user-images.githubusercontent.com/161889/198640479-94c22b6e-1662-4239-9f61-0455ceabf920.png">

Please tell me if you have any comments regarding this?

I find it weird that we use the 'REF_WSH_D_L' ratio and not REF_DIES_EFF

**Comment by guilbep** [comment]
@ctobin111 Please chose one of them (instead of two different one)

**Comment by ctobin111** [comment]
@guilbep you are correct. We will use the reference that is in the current Reference database. Please see the Excel attached which shows the updated Reference database and the equations. As we discussed on Monday, UNHCR would like to have the load % as an input. An equation to do this based on the Australian reference has been added. The default value for a 60% load has been put in the Reference database. Please let me know if you have any questions. Message me with Jabber at anytime. Merci!
[EMISSIONS BASED ON FUEL CONSUMPTION DIESEL GENERATOR_rev1.xlsx](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/files/9918192/EMISSIONS.BASED.ON.FUEL.CONSUMPTION.DIESEL.GENERATOR_rev1.xlsx)

**Comment by guilbep** [comment]
@ctobin111 Hi, thank you. Could you please provide me with some inputs/outputs to verify that I implemented the correct formula ?

Meaning: input/output value for 10/20/30/40/..90% of load ?


Thank you

**Comment by ctobin111** [comment]
Hi Pierre, I tried to test this myself today and the data for a new diesel genset does not seem to be saving. Perhaps you are working on it. Here are some 

**Outputs | Inputs (Percentages so 0.1 is 10%)**
0.32278014 | 0.1
0.27288756 | 0.5
0.26245692 | 0.7
0.2514 | 1

**Comment by guilbep** [comment]
@ctobin111 I'll check that this afternoon! Thank you for pointing that out!

**Comment by guilbep** [comment]
Formula is good for load

**Comment by ctobin111** [comment]
@guilbep Hi Pierre, could you kindly enable a default input load value of 60% in case the users do not know the load?
