### ISSUE TITLE
[FIX] (Facilities): Adjust unit titles

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#107]
### Expected Behavior

In Facilities data input screen with the 3 columns:

Column 3: Diesel to become 'Total diesel used (litres/yr)'
Column 4: Grid power to become '(kWh/yr)'
Column 5: Renewables to become 'Solar (kW installed per yr)'

Please change 'Renewables' everywhere to be 'Solar'

### Anything else?

Yes, please see issue #90 
Eventually, column 5 will have to be multiplied by the number of solar hours per site. Just as we are reading in coordinates, site names, populations to each site with the API to be provided by UNHCR, I will try to see if we can read in the solar hours also. I need to get this information from an open-source database like Homer Pro.

**Comment by ctobin111** [comment]
@guilbep As discussed, issues #90 is a next step for this issue. Please see comment above.

**Comment by guilbep** [comment]
cf : https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/pull/118
