### ISSUE TITLE
[FEATURE] (TRUCKING) <Add option of gas (petrol) truck>

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#108]
Now the only option in the pull down menu is 'diesel truck'.

Please add another drop-down for 'petrol / gas truck'

- @ctobin111 will define the  equation will be very similar and the existing reference will be used.
- @guilbep the equation is the same for petrol as for the diesel truck with the exception that a new reference value should be added to the database and used for the petrol calculation (0,25 should be replaced by 0,23). 
WASH - Trucking - Emissions Factor - Petrol (up to 3.5 tonnes) [-] | 0,23
- (Source: Source: UK Government GHG Conversion Factors for Company Reporting 2022. Condensed set. Available in: https://www.gov.uk/government/publications/greenhouse-gas-reporting-conversion-factors-2022)
- 
![image](https://user-images.githubusercontent.com/111510926/196188431-46db416d-7f2d-4c27-a5cc-ce9f25ecc8cb.png)

**Comment by guilbep** [comment]
From a jabber conversation with @ctobin111 on the 8th nov 22.
'Yes please take the ones ending with _L'. 
So I'll use REF_WSH_D_L and REF_WSH_G_L instead of the existing REF_WSH_D.
