### ISSUE TITLE
[FEATURE] (TRUCKING) <ensure inputs>

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#109]
Ensure input by either kilometres or litres

- [x] @guilbep Add suffix (km) for the distance traveled by the truck 
- [x] @guilbep Add possibility to change km by litres of diesel or gas 
- [x] Add specification and formula for litres of diesel/gaz
   - [x] It will be : number of 'litres between camp and water source'
@ctobin111 to provide new formulas based on conversation with UNHCR 26 Nov 2022

<img width="489" alt="trucking" src="https://user-images.githubusercontent.com/161889/196121974-3718fdc3-cfbe-42e5-8f04-77de34712c3e.png">

**Comment by ctobin111** [comment]
@guilbep The reference will be: Source: UK Government GHG Conversion Factors for Company Reporting 2022. Condensed set. Available in: https://www.gov.uk/government/publications/greenhouse-gas-reporting-conversion-factors-2022

I am finalizing the formula.

**Comment by guilbep** [comment]
@ctobin111 

The formula in the excel file looks like this:
WS_FC =  REF_WSH_G_L*WS_FC/1000 (Total fuel consumption (l/year))
CO2_WSH_TR = REF_WSH_D_L*WS_FC/1000 (Total CO2 Emissions (tCO2eq/year))

The REF constants used in those formula seem wrong. Do you confirm that it's 100% like this ?

**Comment by ctobin111** [comment]
Hi Pierre,
Apologies, the formulas were copied wrong and so this should be clearer:

The CO2equivalent is calculated directly from the litres input using the *_L factors:

Input 1: litres of diesel per year = D_L
Input 2: litres of petrol / gas per year = G_L

CO2_WSH_D=REF_WSH_D_L * D_L/1000 (diesel calculation, answer in CO2eq/yr)
CO2_WSH_G=REF_WSH_G_L * G_L/1000 (diesel calculation, answer in CO2eq/yr)

**Comment by guilbep** [comment]
@ctobin111 I'm creating a new issue #135 to fix the formulas for the trucking using litres instead of km
