### ISSUE TITLE
Move "other" option to materials

### ISSUE THREAD

**Issue by andreullal** [EPFL-ENAC/unhcr-geneva-tech-hub-app#116]
For the BOQ:  Move "other" option from <item type> list to <material type> list

Currently, <item type>  list has 3 options: labour, material, other. The "other" option is there to allow input of materials that are not covered by the coefficients database though affect teh cost - e.g. chemical treatment for timber.

The "other" option should be moved to the material list - i.s. moved from the position shown in the first screenshot below, to the position at the end of the materials list as per the second image below:

![Screenshot 2022-10-27 at 09 55 51](https://user-images.githubusercontent.com/108796343/198226404-0466bdaf-f921-486e-a025-e9a2a3c306ec.png)

![Screenshot 2022-10-27 at 09 56 09](https://user-images.githubusercontent.com/108796343/198226441-88595e64-1cb2-4e9b-9757-a86f52d8078e.png)

**Comment by guilbep** [comment]
Hey @andreullal . I don't know why we did not think of that earlier.
Two things though:
1. The 'Other' in material already exist. But it's different since we can only have the KG option right now (because we manually set the embodied CO2 and water.
2. It's not at the 'end' of the list, since the list is sorted in a kind of alphabetical order. maybe we can 'pre-pend' or append it to the list though. What do you think?

About 1).
- Do we merge the functionality (remove at the top level menu and keep it inside material) ?
- Do we keep the embodied co2/water feature only for the kg part ?

What do you think ?

**Comment by andreullal** [comment]
@guilbep 

Yes, merge the functionality - i.e., remove the top level other and keep it in material.
Yes, keep the embodied co2/water only for the kg part.

AND

Remove the variable "Form" (no need for it, I think), as per the screenshot below:


<img width="1489" alt="Screenshot 2022-11-03 at 13 42 35" src="https://user-images.githubusercontent.com/108796343/199724243-40133f94-7bb6-483f-a954-972a27ba0980.png">

**Comment by andreullal** [comment]
@guilbep 
Also, place the "other" option after the last material. Users will scroll through the list, not find what they want, then select "other" if necessary.

**Comment by guilbep** [comment]
Ok perfect! Thank you @andreullal

**Comment by andreullal** [comment]
@guilbep . I made a mistake above. After selection of material "other", a material name needs to be entered as text. So, you could just change the "Form name" to "Material name". Apologies for any confusion.

**Comment by guilbep** [comment]
@andreullal By the way it will look like this:
I have merged both units. So now we may use L/KG/M/M2/M3/PCE as units for the Other material

![Image](https://user-images.githubusercontent.com/161889/203856413-9aaddad8-7f60-4ac0-ace6-29c0c7e566ca.png)
![Image](https://user-images.githubusercontent.com/161889/203856412-6222b66e-5b42-42cd-b873-50bf97de53ab.png)
![Image](https://user-images.githubusercontent.com/161889/203856410-fe832965-7a50-4edd-bc6e-1737f56f4ff3.png)
![Image](https://user-images.githubusercontent.com/161889/203856411-a6ec603f-59f2-4f4d-bd82-6adb5c72542b.png)
