### ISSUE TITLE
Shelter project comparison

### ISSUE THREAD

**Issue by andreullal** [EPFL-ENAC/unhcr-geneva-tech-hub-app#120]
@guilbep :

Enable side-by-side comparison of 2 or 3 shelters.

As per image 1 below: In the project list page, enable selection of 1, 2, or 3 shelters. 
![2_ProjComp_List-1_-01](https://user-images.githubusercontent.com/108796343/199019615-810837f2-8dc7-4285-980c-30020e819bec.png)

As per image 2 below, when 1, or 2, or 3 (max 3) shelters are selected, the "Compare shelters" button at the top becomes active.
![2_ProjComp_List-2_-01](https://user-images.githubusercontent.com/108796343/199019876-d547ea2e-3104-4886-a519-8b5c3895609a.png)

As per image 3 below, clicking on the "compare shelters" button leads to another page in which 1, 2 or 3 shelters are summarised in columns.
![2_ProjComp_List-1_-02](https://user-images.githubusercontent.com/108796343/199020268-f8e10880-ff0d-43e1-acc3-476ccd2b4d9b.png)

**Comment by guilbep** [comment]
- diameter should be weighted by percentage of the biggest value
- probably add a legend for the color of the scorecard
- information of the scorecard should be under the 'scatter graph' so we don't have to scroll to see

**Comment by guilbep** [comment]
Hello @andreullal Is it possible to have the images of the shape of the geometry without all the text ? 
<img width="1198" alt="not-ready" src="https://user-images.githubusercontent.com/161889/205038387-86a59a8b-1e8e-4859-bef7-2d9eefcd079e.png">

**Comment by andreullal** [comment]
@guilbep Typology graphics sans text:

![GTH-SSC_Graphics_Typology_220401-07](https://user-images.githubusercontent.com/108796343/205054817-ce9b4489-2242-4671-b30c-655199f008d1.png)
![GTH-SSC_Graphics_Typology_220401-08](https://user-images.githubusercontent.com/108796343/205054828-0acd8e6b-6b7d-4473-bced-6133a1bfdf5a.png)
![GTH-SSC_Graphics_Typology_220401-09](https://user-images.githubusercontent.com/108796343/205054834-40ad83ee-53cb-464e-82e4-1c92a4be16cd.png)
![GTH-SSC_Graphics_Typology_220401-10](https://user-images.githubusercontent.com/108796343/205054837-0e382f6f-e191-4927-917c-dd0d06ce0a59.png)
![GTH-SSC_Graphics_Typology_220401-11](https://user-images.githubusercontent.com/108796343/205054842-8dc97666-5458-4703-9642-c240622204f1.png)
![GTH-SSC_Graphics_Typology_220401-12](https://user-images.githubusercontent.com/108796343/205054844-56848ece-0aeb-401e-80d4-5d88a927059e.png)

**Comment by guilbep** [comment]
Hi ! @andreullal As attachment you may find the latest visual.

I think it may not be possible to have a dynamic radius for the sunburst.
Imaging we have a two shelter:
A  with 300  L/year/m² and B with 1L/year/m2
But at the same time the total cost is 3000L for A and 30000L for B
What happen if we have this much difference ? What's the limit of the system ? It may be easier to just make it plain.
I think I spent too much time trying without understanding how it should behave.

Let me think if the visual seems okay to you.

[UNHCR-TSS-export.pdf](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/files/10157604/UNHCR-TSS-export.pdf)
<img width="1062" alt="23000" src="https://user-images.githubusercontent.com/161889/205735064-ceb41e10-f51e-42ab-a3b0-3fb5aba1952e.png">

<img width="1132" alt="3400" src="https://user-images.githubusercontent.com/161889/205735081-ea3bdc38-d5db-425a-8c56-52ba3b96ee3d.png">

<img width="1092" alt="environ_impact" src="https://user-images.githubusercontent.com/161889/205735087-0ced8f48-3cf4-4c73-9fea-c32801398a09.png">

**Comment by andreullal** [comment]
@guilbep  Looks good to me. We can revisit it later if UNHCR suggest changes and if time permits. Thanks

**Comment by andreullal** [comment]
Layout changes for project comparison. Reorganises the same data and refines the layout. 
The order/sequence now corresponds to that of the Scorecard. 
Geometry is combined with Shelter Information.
Allows for image at top of column
All info is centred on the column
Some units below the number/value.


![6_Comparison_230112](https://user-images.githubusercontent.com/108796343/212087714-756dc021-9b5b-4d9f-a2e1-854923fba040.png)
