### ISSUE TITLE
[FIX](GHG-Reference DB): fix 'updating references db'

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#139]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Expected Behavior

@guilbep 
In response to your email, I am attaching the final reference value db. So, to answer your question, 

We are using two reference factors in both facilities and in WASH and will use them in cooking, lighting and pumping. So I prefer to not have WSH in the reference titles but I have added "_L"

**REF_DIES_L** [kg CO2e/l] = 2.72440045 (Source IPCC) (row 2 in the Excel attached)

For the gas/petrol case here is the reference value:

**REF_G_L** [kg CO2e/l] = 2.34 (Source UK Gov) (row 8 in the Excel attached.

@guilbep Also, can you explain what ‘washInput.LIT_WS’ this? I do not see how it is calculated?

here is the updated code with the references:

```javascript
    const washFactorKM =
[EMISSION FACTORS FUELS FACILITIES AND WASH TRUCKING.xlsx](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/files/10020305/EMISSION.FACTORS.FUELS.FACILITIES.AND.WASH.TRUCKING.xlsx)

      washInput.TR_TYP === DIESEL ? REF_WSH_D.value : REF_WSH_G.value;
    if (washInput.US_UNI === "KM") {
      res.TR_NUM = Math.ceil(washInput.WACL / washInput.TR_VOL);
      res.TR_DIST = res.TR_NUM * washInput.TOT_WS * 2;
      res.CO2_WSH_TRB = (washFactorKM * res.TR_DIST) / 1000;
      return res;
    }

    const washFactorL =
      washInput.TR_TYP === DIESEL ? REF_DIES_L.value : REF_G_L.value;
    if (washInput.US_UNI === "LITRES") {
      res.TR_NUM = Math.ceil(washInput.WACL / washInput.TR_VOL);
      res.TR_DIST = 0; // the DIST is unknown since we only have the number of litres
      res.CO2_WSH_TRB = (washFactorL * washInput.LIT_WS) / 1000;
      return res;
    }

[EMISSION FACTORS FUELS FACILITIES AND WASH TRUCKING.xlsx](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/files/10020314/EMISSION.FACTORS.FUELS.FACILITIES.AND.WASH.TRUCKING.xlsx)

**Comment by guilbep** [comment]
@ctobin111 thank you. Also It could have been in the same issue. no need to create a new issue there.

LIT_WS is the input, it's not computed. It's the number of litres used for wash.

**Comment by ctobin111** [comment]
@guilbep As I mentioned in my email and on Jabber, here is the updated references table. Note that the second tab shows that the reference database IGES_GRID_2021 should be renamed as just 'IGES_GRID' because new grid emission factors should be uploaded by UNHCR annually from the website. 
[EMISSION FACTORS FUELS FACILITIES AND WASH TRUCKING.xlsx](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/files/10167620/EMISSION.FACTORS.FUELS.FACILITIES.AND.WASH.TRUCKING.xlsx)
