### ISSUE TITLE
[FEATURE] <GHG General> Menu bar update for future modules

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#141]
@guilbep 

For the future modules, we have a new directive.

Under the WASH tab, please put
- [x] Update: only the trucking module for now	3 Modules: Pumping, Trucking and Treatment (right now there is only trucking, pumping should be moved here with same icon as before and in Phase II.3, the treatment module will be created, icon attached. Please put this same phase under Treatment 'This module of the Assessment Tool is under development')

![image](https://user-images.githubusercontent.com/111510926/203285543-36c090af-cfc5-411f-b0a0-77dc8777f211.png)

Under Material tab,
- [ ] 	CRI and shelter to be deleted (only Domestic Solid Waste to remain)

![image](https://user-images.githubusercontent.com/111510926/203285008-75191c55-426c-4592-b810-8a8d0ef5a2c8.png)

![toilet-icon_4_wastewater_module](https://user-images.githubusercontent.com/111510926/203286213-80b8bdfa-e713-4abc-846c-2874a4abff3d.png)

**Comment by guilbep** [comment]
@ctobin111 do you confirm that Pumping, Trucking and Treatment is no longer the goal. And that it's okay to have only trucking ? Or did I miss something ?

**Comment by guilbep** [comment]
@sbancal We still need to change the icon for CRI to something ressembling the toilet icon @ctobin111 could we use this one: https://materialdesignicons.com/icon/toilet ?
