### ISSUE TITLE
[FEATURE] <Implement tab Energy/Cooking>

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/unhcr-geneva-tech-hub-app#142]
Specs defined => rev1 [here] (https://docs.google.com/spreadsheets/d/1G2UfGqgI2jLG3F4yw9wwCfqOnKQz_EcP/edit#gid=333625437) 
updated by guilbep: rev2 [here](https://docs.google.com/spreadsheets/d/1olkQdKhvju6cviIUjPxf8gegdA4aQ5u1/edit#gid=333625437)

**Comment by guilbep** [comment]
deployed to production via *   ffbde8d (HEAD -> dev, origin/dev) Merge branch 'fix/244-ghg-cooking-input-equations' into dev
