### ISSUE TITLE
[FIX](Enviro impact) <eCharts Sankey: do not display text>

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/unhcr-geneva-tech-hub-app#147]
at least on the right side, because it gets cropped

**Comment by guilbep** [comment]
@andreullal 
<img width="1385" alt="BreakWord" src="https://user-images.githubusercontent.com/161889/211271543-4460f468-df50-4247-aefe-a4c256c6f7d7.png">
It's not possible to hide the label only on the right side currently. So I found a way to circumvent the problem by display the label on several lines (break word overflow rule)
