### ISSUE TITLE
[FIX](WASH Trucking): fix 'wastewater and faecal sludge factor'

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#149]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Expected Behavior

@guilbep 

When wastewater or faecal sludge is checked in the dropdown, the total volume becomes 85% of the initial pumped volume. This is because a portion of the water is not transferred into wastewater. So the input volume pumped must be multiplied by 0.85.

Also, there are two issues that must be checked in WASH trucking:

1) the distance should be checked that is it the one way distance which is converted into a roundtrip distance by multiplying by 2
2) the title 'trucking type' is misleading and should be 'fluid transported'

Thank you,

Cara

**Comment by guilbep** [comment]
done in release v0.5.2 @ctobin111
