### ISSUE TITLE
Energy Cooking module

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#154]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

@guilbep The cooking module must also include the list of energy sources used in Facilities (grid, solar, hybrid or and diesel). 

Also, for the list of cookstove technologies, Valerio recently decided to only use the list that was provided by UNHCR in the beginning. Here is the updated cookstove list and updated fuel list attached. I will aim to get an image for each cookstove type.

@ctobin111 Get cookstove technology images

Please see that I added more detail to the specificati
ons in BLUE.
[Cookstoves_Specifications_rev2.xlsx](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/files/10166880/Cookstoves_Specifications_rev2.xlsx)

Merci!

**Comment by guilbep** [comment]
By the way @ctobin111 concerning the fNRB data https://cdm.unfccc.int/DNA/fNRB/index.html
It is said in the table that the data expired at some point for instance:  '16 April 2017' for republic of angola>
What do I make of this?

Should I use the data anyway if country present or should I always use the default value ?

And what is the default value? I have two different values. 0.76 as in the rev2 reference table ? and 0.85 as in the rev2 G-16 cell of Cooking sheet?

Is 0.85 the default value for pellets/briquettes and wood. and 0.76 the default value for charcoal ?

**Comment by guilbep** [comment]
CF https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/issues/142 for more information to follow latest list
