### ISSUE TITLE
[FEATURE] <Design polish for Tech performance + Habitability tabs >

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/unhcr-geneva-tech-hub-app#158]
~~- [ ] Propose icons @andreullal for each criteria group?~~
- [x] Maybe make it 2 columns ?
- [ ] Combine TechPerf and Habitability tabs - 2 columns on single page
- [x] Header column remains frozen as user scrolls down.
- [ ] Header column includes score (eg 23/42) which updates as user ticks criteria or crosses NA box (not applicable) - i.e. - - [ ]  with the current score increases or the max score decreases.
- [x] reorder env impact to be on the left of the scorecard

cf comment below for a screenshot

**Comment by andreullal** [comment]
An idea:
Combine TechPerf and Habitability tabs - 2 columns on single page
Header column remains frozen as user scrolls down.
Header column includes score (eg 23/42) which updates as user ticks criteria or crosses NA box (not applicable) - i.e. with the current score increases or the max score decreases.

![6_TechPerf-Habitability_230112](https://user-images.githubusercontent.com/108796343/212107100-d9330e09-04c3-4380-bad1-34f7289b2762.png)

**Comment by andreullal** [comment]
Appears to be done. There's a bug in the Habitability page. Will raise this in a separate issue.
