### ISSUE TITLE
[FEAT] DB - IGES_GRID Data should be a matrix

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/unhcr-geneva-tech-hub-app#160]
- [ ] IGES_GRID should have a column per year. Detailed yearly behavior/updated once UNHCR has decided.

**Comment by guilbep** [comment]
@charlottegiseleweil @ctobin111 I'm closing this issue because by Cara's last jabber message. We'll update once a year directly the database
