### ISSUE TITLE
[FEATURE] Energy planning info tab

### ISSUE THREAD

**Issue by guilbep** [EPFL-ENAC/unhcr-geneva-tech-hub-app#17]
- [ ]  Rename “Shelters Types” by “housing Types” and have it viewed as a treemap by default if values are filled - with these values (and an “Edit ” button that changes to displaying the fields to fill).

**Comment by charlottegiseleweil** [comment]
@guilbep pourquoi cette issue est labeled "energy" ??

**Comment by guilbep** [comment]
@charlottegiseleweil  A priori on parle  de la ligne 34 de app/frontend/src/components/energy/EnergyGeneral.vue https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/blob/3969a0a178fb5fa935d3d37e4dcd5e99aaf3d28c/frontend/src/components/energy/EnergyGeneral.vue#L38 Mais je t'avoue que c'est peut-etre @blueur qui devrait être dessus.. Je comprends pas trop cette histoire de tree-map. Ni pourquoi on doit faire ce changenent.

**Comment by blueur** [comment]
Ca semble bien concerner l'énergie, mais je ne comprends pas d'où vient la demande...
