### ISSUE TITLE
[BUG] <GHG Facilities> Error in calculations

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

@guilbep For Facilities:

Baseline data does not copy properly into the endline.

The Gridpower emissions for Djibouti should not be 0
[Issues_19Dec2022_Facilities_Bugs.docx](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/files/10256721/Issues_19Dec2022_Facilities_Bugs.docx)

Also, there is no change in emissions calculated.

Please see the Word Document attached.

### Expected Behavior

Baseline should be copied verbatum into endline

Calculations should be correct from before.

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by guilbep** [comment]
- The missing grid calculation come from the fact that IGES_GRID_2021 does not contains some countries.
- Bug was fixed, we changed to hours instead of years for number of hours. But we didn't replicate the changes in the UI
