### ISSUE TITLE
[FIX](GHG - FACILITIES): fix 'All diesel generators - equation when do not know litres of diesel consumed'

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#175]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Expected Behavior

@guilbep 

We found a problem in our equation for diesel generators used in Facilities (and which will be used for Pumping and Lighting). We have to multiply the final result of the 'do not know number of litres equation' by the load percentage (GENLOAD) to get the real number of litres used. 

Here is the old equation:
'GENSIZE * OPHR * DIE_GEN_L_per_kWh

So here is the  updated equation:
'GENSIZE * OPHR * DIE_GEN_L_per_kWh *** GENLOAD**

And the Excel where this equation update is marked in red:
[EMISSIONS BASED ON FUEL CONSUMPTION DIESEL GENERATOR_rev2.xlsx](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/files/10259568/EMISSIONS.BASED.ON.FUEL.CONSUMPTION.DIESEL.GENERATOR_rev2.xlsx

Let me know if this is clear to you.

Best,

Cara

**Comment by guilbep** [comment]
Thanks @ctobin111 I'm updating the formula. Btw you forgot to say that operating hours are per day and that we want by year. I multiply by 365 in my formula:

```
  const genLoad = (generatorLoad ?? 60) / 100;
  const DIE_GEN_L_per_kWh = -0.031 * Math.log(genLoad) + 0.2514;
  const litres =
    generatorSize * (operatingHours * 365) * DIE_GEN_L_per_kWh * genLoad;
```
