### ISSUE TITLE
[FEAT] <GHG Facilities: Standardizing color scheme for pie charts>

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#179]
@guilbep 

As you can see in this screenshot, if there is only one type of energy source for the Facilities Energy Mix, it always shows up as blue in the pie chart even if the fuel source is different in the endline. Could we rather have one color per energy type. For example, yellow for solar, blue for grid and brown for diesel?

![image](https://user-images.githubusercontent.com/111510926/208626977-ee4fbc82-5f5f-494a-9a09-33b936ee6aac.png)

**Comment by guilbep** [comment]
Done in 90bba74 fix(ghg): correct pie chart and compute power for diesel
