### ISSUE TITLE
[FIX](GHG Facilities: Generator Equation): fix 'correct equation with the conversion factor'

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#180]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

@guilbep 

Bonjour Pierre, so the number of litres should be divided by the REF_EFF_DIES since it is given in **l/kWh**. Thus 100 litres / 0.267 (litres / kWh) = 374 kWh (a rounded number)

0.267 (litres / kWh) is REF_EFF_DIES

Prior we used a general number without a reference provided by UNHCR that was 2.5 **kWh/l** so this is why the equation has to change. We are using the inverted number.

Merci!

**Comment by guilbep** [comment]
90bba74 fix(ghg): correct pie chart and compute power for diesel
