### ISSUE TITLE
[FEATURE] <GHG - adding static photos in modules>

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#183]
@guilbep 

UNHCR has requested that photos be added to show some models of cookstoves, trucks used in the field, a diesel generator, some form of a national grid power lines and some solar panels.

@ctobin111 will be providing the photos to Pierre.

**Comment by guilbep** [comment]
done in  bdfb9b7 (feat/ghg-end-of-phase2.1) feat(ghg): add new images for cookstoves
