### ISSUE TITLE
[FIX](GHG Facilities): fix 'another location where we must put per year'

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

@guilbep Hi Pierre, can you please specify per year for the grid in the Hybrid Mix window pop-pop menu for a new Facility and in the edit Intervention window pop-pop. 

kWh used per year (national grid)

Here are the screenshots.

![image](https://user-images.githubusercontent.com/111510926/208709486-583646ff-ef63-45c3-bd78-2e1723303b98.png)

![image](https://user-images.githubusercontent.com/111510926/208709885-537dde8c-e384-405b-a719-136603d5db2f.png)

**Comment by guilbep** [comment]
done in d0d80d4
