### ISSUE TITLE
[BUG] <GHG WASH Trucking when kilometers is used to calculate emissions>

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#190]
## Update
Summary if you change Litres -> KM and KM -> Litres when editing a truck line. It should reset the appropriate values.

e.g. If we use KM we should have '--' unknown as the number of litres not the old value.

## WASH Trucking
 
In the baseline, the liters of diesel consumed are provided as input
However, in the case of the endline when selecting the option of the kilometers and the truck size, the liters of diesel consumed do not change in comparison with the baseline. When emissions are to be calculated based on kilometers, please put a hyphen so that no data will be shown in the liters of diesel consumed for the endline.
 

[Comments on Tool WASH Trucking_1.docx](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/files/10384801/Comments.on.Tool.WASH.Trucking_1.docx)

**Comment by guilbep** [comment]
it was done in * 385a518 (origin/milestone/GHG_february_2023, milestone/GHG_february_2023) fix(ghg): remove other values for trucking
Please confirm it's okay @ctobin111
