### ISSUE TITLE
[FIX](GHG Facilities and for all Diesel generators): fix 'Use weekly operating hours'

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#192]
### Location
Ghg application
When editing an assessment under the category=Energy&subcategory=Facilities

### Expected Behavior

@guilbep UNHCR informed us in late December that often the operating hours are different on weekends so they suggested that in the dropdown menu when litres of diesel are not known, please change the operating hours to be listed as operating hours (hrs/week).

![image](https://user-images.githubusercontent.com/111510926/211610656-9de9a004-d85f-48ed-bde1-372966cd9e98.png)

- [x] Change the input text
- [x] Change the formula
  - Currently the formula behave like this: generator_power * operating_hours_per_day * 365.25
  - And we want it to behave like so: generator_power * operating_hours_per_week * 52

**Comment by guilbep** [comment]
done in 76cb9e1 fix(ghg): replace hrs/day by hrs/week
