### ISSUE TITLE
[FIX](GHG Databases): fix 'update IGES grid factors to IFI grid factors'

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#193]
Here is a more extensive list of grid factors from the IFI rather than from IGES. For now, the default value will be 0.6448

The reference for the database is the following:

https://unfccc.int/sites/default/files/resource/IFI%20Default%20Grid%20Factors%202021%20v3.1_unfccc.xlsx
[IFI Default Grid Factors 2021 v3.1_unfccc_1.xlsx](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/files/10384971/IFI.Default.Grid.Factors.2021.v3.1_unfccc_1.xlsx)

**Comment by guilbep** [comment]
@ctobin111 told me that we keep IGES grid
