### ISSUE TITLE
[FIX](GHG General): fix 'Example Input database from UNHCR with ave daily solar hours from Solar Atlas'

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#194]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

@guilbep Here is the input database that the UNHCR (Ronald) gave us. I have attached the GHI values (Global Horizontal Irradiance) values to give the average number of solar hours per day per site. So this last column must be multiplied by the number of days per year 365,25.

Happy to discuss this later, hopefully with Ronald.

Merci
[Solar_Daily_Hours_UNHCR_Refugge_Locations.xlsx](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/files/10385100/Solar_Daily_Hours_UNHCR_Refugge_Locations.xlsx)

@ctobin111 will confirm the appropriate reference for the Solar Atlas (WB): https://globalsolaratlas.info

**Comment by ctobin111** [comment]
@guilbep Here is the database attached here with the solar hours. This responds to your comment on issue #90 

[EPFL-ENAC/unhcr-geneva-tech-hub-app] [FIX] (Facilities) <Energy Mix lumped in kWh is not correct for solar> (Issue #90)

[@ctobin111](https://github.com/ctobin111) Did you put the dataset inside the gdrive ? I cannot find it

**Comment by guilbep** [comment]
done in * 62886c9 chore(data): add solar averaged and unhcr location
