### ISSUE TITLE
[FEATURE] SHELTER. Project comparison layout

### ISSUE THREAD

**Issue by andreullal** [EPFL-ENAC/unhcr-geneva-tech-hub-app#197]
[replaces the comments added to project comparison issue, which was reopened, now closed again]
Layout changes for project comparison. Reorganises the same data and refines the layout.
The order/sequence now corresponds to that of the Scorecard.

- [x] Put title of shelter in h2 font
- [x] put subtitle under the category of the shelter 
- [x] Geometry is combined with Shelter Information -> no more construction sub section
     - [x] add sub title to shape image
     - [x] put floor/volume into separates lines
     
- [x] Allows for image at top of column
- [x] All info is centred on the column
- [x] Some units below the number/value. (environmental impact pie chart title)
- [x] bug diamond (optional) problem with heigh bug with scorecard
- [x] replace donuts by box
- [x] try to shrink to one page
- [x] Bigger left margin (1cm?)
- [x] Repeat the Header for every printing page
![6_Comparison_230112](https://user-images.githubusercontent.com/108796343/212089204-3361fab2-36e0-4b9e-a68e-f550bd3b7ca4.png)

**Comment by guilbep** [comment]
done in a59f141 (HEAD -> dev, origin/dev) fix(shelter): compare fixes #197

**Comment by guilbep** [comment]
[UNHCR-TSS-compare-v3.pdf](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/files/10980802/UNHCR-TSS-compare-v3.pdf)
[UNHCR-TSS-compare.pdf](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/files/10980801/UNHCR-TSS-compare.pdf)

It looks like this now. @andreullal is it okay ?
