### ISSUE TITLE
[FIX](GHG General): fix 'Structure and placement for all modules'

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#205]
Restructure tabs to the following structure 

<img width="711" alt="Screenshot 2023-01-24 at 14 12 14" src="https://user-images.githubusercontent.com/18381609/214303068-1bcd1943-86e8-4d90-8e0f-56b793dd315a.png">

**Comment by ctobin111** [comment]
@guilbep This message responds to your message:
[@sbancal](https://github.com/sbancal) We still need to change the icon for CRI to something ressembling the toilet icon [@ctobin111](https://github.com/ctobin111) could we use this one: https://materialdesignicons.com/icon/toilet ?

**Comment by guilbep** [comment]
done in 6f280f3 fix(ghg): move module in assessment survey and add default REF_GRD
