### ISSUE TITLE
[FEAT] Implement Lightning module

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/unhcr-geneva-tech-hub-app#211]
Implement Lightning module - similar structure as Cooking. 
Specs here : https://docs.google.com/spreadsheets/d/15PGK9vmu_SZRK2pvZg4URpMuR8QSGhFs/edit#gid=333625437

**Comment by guilbep** [comment]
@ctobin111 It's been deployed so you can test and we can review the equation later

**Comment by guilbep** [comment]
done in release 0.15.0
