### ISSUE TITLE
[FEATURE] about page

### ISSUE THREAD

**Issue by guilbep** [EPFL-ENAC/unhcr-geneva-tech-hub-app#212]
Update About tab (merge with Apps tab?) or make it accessible even when not logged in.
Decision on its contents by @ctobin111 and Greg.

- [ ] Change the content of the about page with the following (based on the latest docx in the comments):

# Logos
Put SDC, GTH, UNHCR (one single logo) and EPFL logos on top
Remove Gnansounou Group logo
Put laboratories on bottom line, with the following text
EPFL contributing labs and centers
EssentialTech Centre, Smart Living Laboratory, FAR, IT4R

# Disclaimer Section
The GHG Emission Calculator and Sustainable Shelter Calculator have been developed at EPFL through a collaboration with the UNHCR Geneva Technical Hub and SDC. At EPFL the project was coordinated by the EssentialTech Centre. Scientific contributions were provided by the FAR and Smart Living laboratories, 
IT4Research and EssentialTech..
The goal of the tools is to enable UNHCR to 'green' its operations by informing its strategies and activity planning with concrete and evidence-based recommendations. These elements are made available directly and in a user-friendly way to humanitarian practitioners working in the field.
It will support UNHCR to align with the Pillar 2 of its Strategic Framework for Climate Action. The tools also support actions toward achieving UNHCR's Operational Strategy for Climate Resilience and Environmental Sustainability 2021-2025.

# Map Attributions
Leave as it is

**Comment by guilbep** [comment]
- remove far logo / living lab

**Comment by charlottegiseleweil** [comment]
[GTH revision About Section.docx](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/files/10956876/GTH.revision.About.Section.docx)
Contents for the About tab are attached here (sent by Greg via email)  @guilbep  :)

**Comment by guilbep** [comment]
<img width="1399" alt="about-page" src="https://user-images.githubusercontent.com/161889/225564787-b89f7c7e-29cb-4866-8b68-e8afa6f26a5d.png">
Looks like this
