### ISSUE TITLE
[FIX](GHG Facilities, Cooking): fix 'Default value for grid emissions factor'

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#215]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Expected Behavior

@guilbep NOTE: Average grid emission factor should be 0.6448. If possible in an information button on this value, could you please put:

"The default grid emission factor is an average of all IGES 2022 emission factors for countries hosting refugees."

For now, we will continue using the IGES website since the data is most accurate.

**Comment by guilbep** [comment]
@ctobin111  by the way I'll put hte 'The default grid emission factor is an average of all IGES 2022 emission factors for countries hosting refugees.'  text in the reference table

**Comment by charlottegiseleweil** [comment]
@ctobin111 can you put a screenshot to specify exactly WHERE to put this (i) button ?

**Comment by guilbep** [comment]
Put the default value in the reference table

**Comment by guilbep** [comment]
done @ctobin111
