### ISSUE TITLE
[BUG] EnvPerf Sunburst Chart - different forms to be distinguished by different shades of same colour

### ISSUE THREAD

**Issue by andreullal** [EPFL-ENAC/unhcr-geneva-tech-hub-app#217]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Material colours fixed. Each form of the material has same material colour

### Expected Behavior

Each form should have different shade of same material colour - eg 20%, 30% etc.

### Environment

```markdown
- OS:
- Node:
- npm:
```

### Anything else?

![Screenshot 2023-01-26 at 09 36 06](https://user-images.githubusercontent.com/108796343/214791819-6a6b82d6-1aba-43ef-a4d2-0bb6089bbfac.png)

**Comment by guilbep** [comment]
done in * a98777f feat(shelter): add new color and better type for upload with @andreullal
