### ISSUE TITLE
[FEATURE] TechPerf - Add criteria to Thermal Comfort - Roof construction option

### ISSUE THREAD

**Issue by andreullal** [EPFL-ENAC/unhcr-geneva-tech-hub-app#219]
Another option to be added to roof construction options. Currently three options, as per screenshot below. 
Added option:

" Roof comprised of single layer of heavy material (e.g., earth, concrete slab)"

This added option should be second in the list. 

![Screenshot 2023-01-26 at 09 48 17](https://user-images.githubusercontent.com/108796343/214794626-33bde6d8-db41-4720-b698-01e43b7f1a77.png)

**Comment by guilbep** [comment]
done the 10th/02/2023
