### ISSUE TITLE
[BUG] Material coefficients - Bamboo and timber/wood

### ISSUE THREAD

**Issue by andreullal** [EPFL-ENAC/unhcr-geneva-tech-hub-app#220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Current coefficients don't take into account sequestration.

### Steps To Reproduce

- [x] @andreullal to provide updated coefficients (JSON file)
- [ ] @guilbep to reload material properties file.

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by guilbep** [comment]
@andreullal any update ?

**Comment by andreullal** [comment]
I'll enter these numbers directly into the code as you showed me:

Material : kgCO2e/kg : source : L/kg : source

Bamboo : 0.26 : ICE3 (softwood) : 25.66 : EPIC (softwood) 
Softwood : 0.26 : ICE3 : 25.66 : EPIC
Hardwood : 0.82 : ICE3 : 26.54 : EPIC
Plywood : 0.68 : ICE3 : 36.93 : EPIC
Stone : 0.079 : ICE2 : 16.5 : EPIC 
Gravel : 0.007 : ICE3 : 1.9 : EPIC
Sand : 0.007 : ICE3 : 1.8 : EPIC

**Comment by andreullal** [comment]
Values updated directly in the csv file that you sent the link for. Need to check that updates reflected in the app.

I noticed a bug in that Density ref isn't displayed in the app - i.e., in the popup, as per the embodied carbon and embodied water refs. I'll add an issue for the bug.

**Comment by andreullal** [comment]
Coefficients updated. Leads to another issue/bug that I'll raise in a separate issue - changing the coefficients should lead to recalculation of values for existing projects.
