### ISSUE TITLE
[BUG] <GHG Facilities calculations>

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#223]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

@

Issue 1 Facilities: please see Kenya Kakuma, 1 facilities: diesel to solar (v1)
Cannot take kWh from diesel and put that in a solar scenario for the endline. Can kW and kWh be automatically added?

Issue 2 Facilities: When change from diesel and convert to grid with same number of kWh, there is still 20% difference- 

Please see Word document attached.
[RequestedUpdates_Tool_31Jan2023_rev2.docx](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/files/10567068/RequestedUpdates_Tool_31Jan2023_rev2.docx)

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by guilbep** [comment]
done in * 279c31d feat(ghg): make generic display previous value (feat/ghg-end-of-phase2.1)
