### ISSUE TITLE
[FEATURE] <GHG Solar Text>

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#226]
@guilbep 

Here is some header text:

Table 1)
Longterm daily average of  solar hours per site (Source: Solar Global Atlas)

Table 2)
Longterm daily average of solar hours per country (Source: Solar Global Atlas) (Note: This value is used when the site global horizontal irradiation is not known.)

**Comment by guilbep** [comment]
done in d613708 feat(ghg): put reference data in rows to add information (feat/ghg-end-of-phase2.1)
