### ISSUE TITLE
[FEATURE] <GHG Diesel generator text>

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#227]
@guilbep 

Here is a requested text change for diesel generators for Facilities, WASH Trucking and Cooking:

Rather than 'I do not know the number of litres of diesel' - please put either 'Number of litres of diesel known' or 'Number of litres of diesel NOT known'

**Comment by guilbep** [comment]
Done in  305a2a7 feat(ghg): change text for diesel generator (feat/ghg-end-of-phase2.1)
