### ISSUE TITLE
[FEATURE] <GHG Cookstoves>

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#228]
@guilbep 

Hi Pierre, can you please add these three cookstove photos as place holders to show what it will look like to have photos in the cooking application?

![3StoneFireCookstove](https://user-images.githubusercontent.com/111510926/217458643-e9317266-9f06-4aa0-8938-ba4e91dfa155.jpg)
![ImprovedBriquette](https://user-images.githubusercontent.com/111510926/217458677-8a2cd549-2c8d-4df4-a637-af67cf5f472d.jpg)
![Traditional_Briquette](https://user-images.githubusercontent.com/111510926/217458703-75bfcac7-5569-48db-a423-eaa0d46c811d.jpg)

**Comment by guilbep** [comment]
done in bdfb9b7 (HEAD -> feat/ghg-end-of-phase2.1
