### ISSUE TITLE
[BUG] <GHG Facilities: double counting of emissions>

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#229]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

@guilbep I hope this can be fixed by 16h since the calculation is not correct for Facilities. If you look at the Adiharush, Ethiopia test that I ran in Facilities, you will see that changing in the Endline does not erase the original baseline, so the result is that emissions are counted twice (baseline plus new endline) for the same Facility.

Here is a screenshot and you can see this if you open up the Adiharush example. Can this be fixed?

Thank you,
[Issues_Facilities_rev0.pdf](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/files/10694632/Issues_Facilities_rev0.pdf)

Cara

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by guilbep** [comment]
@ctobin111 do not hesitate to copy paste the url next time: https://unhcr-tss.epfl.ch/green_house_gaz/ET/Adiharush%2520%253A%2520Point/surveys/Test%2520A?category=Info

**Comment by ctobin111** [comment]
@guilbep ok, good idea. thank you. And here is the screenshot.
![IssueDoubleCounting](https://user-images.githubusercontent.com/111510926/217753250-41b7dc6a-5cdb-420c-99dd-a1c9e28c5688.png)
