### ISSUE TITLE
[BUG] <Shelter material properties density reference popup display>

### ISSUE THREAD

**Issue by andreullal** [EPFL-ENAC/unhcr-geneva-tech-hub-app#231]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

"-" appears when you hover over the "density" value.

![Screenshot 2023-02-14 at 14 12 51](https://user-images.githubusercontent.com/108796343/218750312-be2bb1a9-a9e1-48e7-804b-53b12a292cce.png)

### Expected Behavior

The density reference should appear, e.g., "EPIC v.2.0". Embodied carbon and embodied water references appear correctly.

![Screenshot 2023-02-14 at 14 19 01](https://user-images.githubusercontent.com/108796343/218750455-20313874-5bd9-4269-b96e-fde5b0b6aedd.png)

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by guilbep** [comment]
Fixed in #cf7f8f9
