### ISSUE TITLE
[BUG] <shelter> Habitability page - checking "not applicable" does not immediately change score at top

### ISSUE THREAD

**Issue by andreullal** [EPFL-ENAC/unhcr-geneva-tech-hub-app#234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I check the "not applicable" box, the score at the top (beside title) does not change.

### Expected Behavior

Checking either the yes box or the not applicable box should change the score at the top.

The Technical Performance page works correctly.

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by guilbep** [comment]
done in * 0665547 (HEAD -> dev, origin/dev) fix(shelter): correct typo in habitability and correct css

**Comment by guilbep** [comment]
@andreullal it should be fixed now. Please confirme
