### ISSUE TITLE
[FEATURE] <GHG Cooking: Equations>

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#240]
@guilbep 

Hi Pierre, please find a photo of the cookstoves equation attached. Let me know if they are not understandable or legible. You will see that biomass equations require a variation of the fNRB number. Each type of fuel has its own Emissions Factor (EF). The EF units are incredibly important. I will be providing you a list of the EFs in a subsequent response.

Thank you,
![Cookstove_Calculations](https://user-images.githubusercontent.com/111510926/220090096-5494899a-fd91-4bfb-a31e-0fa65a50160d.jpg)

Cara

**Comment by charlottegiseleweil** [comment]
Duplicate from #142. Please check for existing issues and comment on those before creating duplicate @ctobin111
