### ISSUE TITLE
[FEATURE] <SHELTER> Global statistics - add units to charts

### ISSUE THREAD

**Issue by andreullal** [EPFL-ENAC/unhcr-geneva-tech-hub-app#241]
Add units for each of the charts in the global statistics fly-out panel

![Screenshot 2023-02-20 at 12 56 31](https://user-images.githubusercontent.com/108796343/220100149-ecae2fad-ef51-49d3-8b0d-53e81b1ca519.png)

**Comment by guilbep** [comment]
fixes * f65330c (HEAD -> dev, origin/dev) fix(shelter): add units to overview global statistics

**Comment by guilbep** [comment]
- try to convert proportion to percentage

**Comment by guilbep** [comment]
![Image](https://user-images.githubusercontent.com/161889/224993984-192742c5-a2d1-43c5-af5f-71b0c1ab13d2.png)

Hi @andreullal it looks like this now. Please advise if that's what you wanted.

**Comment by andreullal** [comment]
I think it was better as it was before. Repetition of the units for each number isn’t necessary. Better to have it at the top under the header only.

Note that the percentages are wrong - need to divide by 100.



On 14 Mar 2023, at 12:58, Guilbert Pierre ***@***.***> wrote:



[Image]<https://user-images.githubusercontent.com/161889/224993984-192742c5-a2d1-43c5-af5f-71b0c1ab13d2.png>

Hi @andreullal<https://github.com/andreullal> it looks like this now. Please advise if that's what you wanted.

**Comment by guilbep** [comment]
There was a bug when looking at the scorecards.. it was multiplying two times by 100. I fixed it now. thanks for noticing.

**Comment by andreullal** [comment]
Yes - that’s it. Thanks.


On 14 Mar 2023, at 13:16, Guilbert Pierre ***@***.***> wrote:



@andreullal<https://github.com/andreullal>

[Image]<https://user-images.githubusercontent.com/161889/224998387-994b0ca4-85b1-4c79-90c7-9656961b4d7a.png>

Is it better like this ?
