### ISSUE TITLE
[FEATURE] <GHG Cooking>

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#243]
@guilbep Can you kindly re-arrange the input boxes for cooking input info as per UNHCR's recent request:

Top (Level 1): Cookstove technology (no change)
Level 2: Cookstove fuel (no change)
Level 3: Improved cooking device (pressure cooker)
Level 4: If biomass: wet/dry biomass
Level 5: fuel consumption value (defaults given if available) (e.g., kg/d/hh)
Bottom: Level 6: percentage of total cookstoves (no change)

![ScreenshotCookstoveInputInfo](https://user-images.githubusercontent.com/111510926/221563052-1f115ff6-6087-4a85-97da-2eaee9514bef.png)

**Comment by guilbep** [comment]
Done the 9th march 2023
