### ISSUE TITLE
[FEATURE] <Help menu>

### ISSUE THREAD

**Issue by andreullal** [EPFL-ENAC/unhcr-geneva-tech-hub-app#249]
Add a help icon to top right of each screen - beside reference data and overview data icons.

Clicking help icon brings flyout panel (same as overview and reference data)

List of help resources:

- Document icon followed by text "Instruction manual"
- Video icon followed by text "Viewing existing projects"
- Video icon followed by text "Creating new projects"
- Video icon followed by text "Entering project information"
- Video icon followed by text "Uploading and downloading project files"
- Video icon followed by text "Entering geometry information"
- Video icon followed by text "Entering Bill of Quantities information"
- Video icon followed by text "Assessing technical performance criteria"
- Video icon followed by text "Assessing habitability criteria"
- Video icon followed by text "Comparing projects"
- Video icon followed by text "Exporting reports"
- Video icon followed by text "Viewing overview data"
- Video icon followed by text "Viewing reference data"

**Comment by andreullal** [comment]
First draft of the instruction manual:

[Shelter & Sustainability Manual.pdf](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/files/10956732/Shelter.Sustainability.Manual.pdf)

**Comment by andreullal** [comment]
Icons for the shelter menu:

<img width="190" alt="Screenshot 2023-03-13 at 12 13 59" src="https://user-images.githubusercontent.com/108796343/224688064-ec0736ae-c3d7-45ce-8d53-dbd60e9a43e5.png">
<img width="388" alt="Screenshot 2023-03-13 at 12 14 31" src="https://user-images.githubusercontent.com/108796343/224688071-4743e07d-2886-4115-a998-c653a86f4b13.png">

**Comment by guilbep** [comment]
@andreullal I've deployed to production and it looks like this. Tell me what you think [no-lag.webm](https://user-images.githubusercontent.com/161889/224744143-1585b469-1708-47eb-a6de-ecaa28aed7de.webm)
