### ISSUE TITLE
[FEATURE] <GHG Facilities>

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#253]
@guilbep 

Can you please add the ability to rename facilities after creating them?

**Comment by guilbep** [comment]
<img width="656" alt="rename-facilties" src="https://user-images.githubusercontent.com/161889/227237086-123ec908-140a-4352-90b6-f4b6a59a6707.png">
It should be possible now

**Comment by guilbep** [comment]
done in * fadefb1 feat(generic): abstract diesel and solar for Cooking and Facilities
