### ISSUE TITLE
[FIX](Facilities): fix 'edits on Facilities baseline endline page'

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#254]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

@guilbep UNHCR has requested the following edits on the Baseline and Endline page:

1) For calculated kWh based on diesel consumption replace “XX” by “~XX” to indicate that the calculated kWh in brackets is an estimation only
![image](https://user-images.githubusercontent.com/111510926/225242069-049f4ef5-d918-45b8-aa8f-71a60a5aeb07.png)

2) In Baseline and Endline: Replace next to pie chart Energy Mix (kWh) on the right: “Total CO2 emissions: XX (tCO2e/yr)” by “Total CO2 emissions: XX tCO2e/yr”
![image](https://user-images.githubusercontent.com/111510926/225242159-7b99fb51-7312-4c2a-956d-199c92e38919.png)

3) Add an additional line under the endline and baseline results (“Total CO2 Emissions…”), stating “These calculations are limited to Scope 1 and Scope 2 sources of emissions for purposes of simplicity.”

4) Rephrase warning when baseline and endline energy demands do not match: Replace "This comparison is not valid because baseline and endline have different energy demands." with “Please note that the baseline and endline energy demands do not match.” Then allow the user to accept this warning and confirm the difference, e.g. by closing the warning with a mouse click.
![image](https://user-images.githubusercontent.com/111510926/225242835-f4c7ff13-6312-4320-91ff-0667c343b639.png)

5) Endline and baseline: please update the header title. Replace “Grid power (kWh/yr)” with “Grid (kWh/yr)”
![image](https://user-images.githubusercontent.com/111510926/225243254-20d6401b-14ae-46e4-bdcb-2f857ab3f3dc.png)

6) Add unit for CO2 emissions (kg CO2e / kg) 
![image](https://user-images.githubusercontent.com/111510926/225246820-2b919a05-3a81-4069-b331-fda946cb6928.png)

**Comment by guilbep** [comment]
@ctobin111 "Then allow the user to accept this warning and confirm the difference, e.g. by closing the warning with a mouse click."  not sure how it should behave.. So the warning disappear for ever now. (seems a bit weird though).
In my honest opinion, it should still be accessible somehow.

**Comment by guilbep** [comment]
done in b42c79d fix(ghg): remove old facilities and complete new generic module for facilities
