### ISSUE TITLE
[FIX](GHG Results page): fix 'Update Results layout'

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#255]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

@guilbep UNHCR has requested:

Results page: please put the up or down arrow and the difference in emissions on a separate line below. This line of text will be either green (emissions reduction) or red (emissions increase)

![image](https://user-images.githubusercontent.com/111510926/225243679-b0a458ac-3802-4f18-bb02-6e93e5379e11.png)

**Comment by guilbep** [comment]
<img width="1700" alt="results" src="https://user-images.githubusercontent.com/161889/227235652-18a10f92-b7b0-4088-8e7c-1d5bdaa847bf.png">
@ctobin111 would that be okay ?

**Comment by guilbep** [comment]
done in b42c79d fix(ghg): remove old facilities and complete new generic module for facilities
