### ISSUE TITLE
[FEATURE] <Hybrid energy mix adaptability>

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#256]
@guilbep 

For all hybrid energy mix scenarios where solar is used, The baseline value under “total kW of solar installed” is no longer present and moves to kWh/yr in the endline. It would be preferred that both the kW and kWh are editable and that the baseline kW value is kept in the endline.

![image](https://user-images.githubusercontent.com/111510926/225245630-568918ab-5579-40d4-9406-cebc77a6c60f.png)

![image](https://user-images.githubusercontent.com/111510926/225245811-92121290-081b-43e0-a7bb-35635c3b34c3.png)

**Comment by guilbep** [comment]
<img width="562" alt="PreviousTotalKw" src="https://user-images.githubusercontent.com/161889/227234236-c80533bd-1f82-49cc-9370-7eac0a5c5050.png">
@ctobin111 @charlottegiseleweil  It looks like this now; From what I understood from the issue. It answers the problematic ?

Is that correct/better @ctobin111  ?

Do you have any suggestions ?
