### ISSUE TITLE
[FIX](GHG App in General): fix 'number format'

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#257]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

@guilbep UNHCR has requested:

Use the same convention of a thousand separator (‘) for all numbers rather than the spaces.

**Comment by charlottegiseleweil** [comment]
![Image](https://user-images.githubusercontent.com/18381609/225575389-1f274141-d551-4a87-ad04-82cee32bb8d0.png)

**Comment by guilbep** [comment]
@andreullal  @ctobin111  What type of language the number formatting should be ? https://en.wikipedia.org/wiki/Decimal_separator#Examples_of_use

**Comment by ctobin111** [comment]
@charlottegiseleweil Here are some screenshots where the spaces are used as a separator.

![image](https://user-images.githubusercontent.com/111510926/225575829-00c13297-6da4-48f5-b727-30206e6e28f6.png)

![image](https://user-images.githubusercontent.com/111510926/225576260-38f98987-f349-4508-ad46-9430c1241216.png)

**Comment by ctobin111** [comment]
@andreullal @charlottegiseleweil 

If we take the Swiss way: 
1'234'567.89

If we take the Australian/American way:
1,234,567.89

I don't want to impose the Imperial ways, so @andreullal what do you suggest?

**Comment by andreullal** [comment]
I’m ok with doing it either way.



On 16 Mar 2023, at 11:24, ctobin111 ***@***.***> wrote:



@andreullal<https://github.com/andreullal> @charlottegiseleweil<https://github.com/charlottegiseleweil>

If we take the Swiss way:
1'234'567.89

If we take the Australian/American way:
1,234,567.89

I don't want to impose the Imperial ways, so @andreullal<https://github.com/andreullal> what do you suggest?

**Comment by guilbep** [comment]
We'll stay as is for now (marked as done)
