### ISSUE TITLE
[FEATURE] <Facilities page - add 2 hovers>

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#258]
@guilbep 

1) Please add **an extra line in the existing** Hover box to explain diesel generator load when number of litres is NOT known – On “generator load (%)” please state “Load on a diesel generator is the power being consumed from the unit. In a household application the load would be the items in a house, such as lights.”

2) Please add Hover box when assigning “Total kW of solar installed” to read “A performance ratio of 80% is included which assumes a 10% loss through the inverter and 10% transmission loss.”

**Comment by charlottegiseleweil** [comment]
@ctobin111 

1. Do you want to replace current text with yours, or add yours ? 

![Image](https://user-images.githubusercontent.com/18381609/225574282-b9992a56-127d-44f2-b5f3-f09389c7e863.png)

**Comment by ctobin111** [comment]
Hi Charlie,


Sorry, can you be more specific on what text would change? UNHCR had asked for 2 hovers to be added.


Thank you,

Cara

________________________________

**Comment by ctobin111** [comment]
@charlottegiseleweil Hi Charlie, in the email the text box did not show up. I see what you mean now in GitHub. This would be an additional hover. There would be one hover about the default average load and another one on the definition of load. Perhaps one "i" on the percentage and one "i" on the load?

**Comment by charlottegiseleweil** [comment]
It's a bit weird if we add two (i) for the same field. How about putting the 2 sentences in the same hover box ?

**Comment by ctobin111** [comment]
@charlottegiseleweil Agreed. One hover with both sentences could work.

**Comment by charlottegiseleweil** [comment]
Perfect! Updating the issue description accordingly :) thank you !

**Comment by guilbep** [comment]
done in adc0f88
