### ISSUE TITLE
[BUG] <Facilities: Not Powered Intervention>

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#259]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

@guilbep 

When going from baseline as  “not powered facility” to then updating the intervention and adding in a diesel generator or the grid in the endline, the "change in emissions” in % is not displayed. The total emissions changes, but for the particular facility only a “-“ appears.

![image](https://user-images.githubusercontent.com/111510926/225253617-87b095a8-4b24-4979-980a-e4dc2dc172f4.png)

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by charlottegiseleweil** [comment]
Expected behavior : 
- Display "change in emissions"

**Comment by ctobin111** [comment]
@charlottegiseleweil yes exactly

**Comment by guilbep** [comment]
@ctobin111 @charlottegiseleweil What should It be though ? What's the percentage of going from 'None' to 1423 kWh/year ? Or maybe I don't understand the logic.
We should probably review how the 'ratio' logic should apply for facilities.

**Comment by charlottegiseleweil** [comment]
@ctobin111 could you share the equation ?

**Comment by ctobin111** [comment]
@guilbep @charlottegiseleweil  The issue is the relative change given in percentage (baseline - endline)/baseline because normally we are going from a more emitting case in the baseline to a lower emitting case in the endline. If we have not powered, we are dividing by 0. In the particular case where there is no power in the baseline, can we use the relative difference with this equation (endline - baseline)/endline? It will be 100% always.
