### ISSUE TITLE
[BUG] <Facilities: Solar conversion kW to kWh>

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

@guilbep 

In the hybrid case, when you add in kW, it shows up in the kWh/yr column. Thus, the installed solar power in kW falsely displayed as kWh in facility overview. Sum of energy of all facilities is therefore not correct.

![image](https://user-images.githubusercontent.com/111510926/225254985-05f90bd6-0a03-44f8-8203-6e059203e73f.png)

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by charlottegiseleweil** [comment]
@ctobin111 this issue is not totally clear...
- Do you mean that the formula for hybrid should be the same as solar ? 
Can you share the document with all equations for users ? (see #264 )

**Comment by ctobin111** [comment]
@charlottegiseleweil and @guilbep Sorry, to be clear, when the information is logged in as "5 kW", it is then directly transferred to the kwh/yr column without the conversion from kW to kWh. The conversion means that the kWs are multiplied by the Daily Solar Hours (from the general page) and multiplided by a performance ratio of 80% (meaning that there 10 % losses in any panel due to the invertor and 10% losses to the transmission loss). For example, 5 kW X 6 (ave daily solar hours) X 0.8 = 24 kWh

**Comment by charlottegiseleweil** [comment]
Great thank you ! Will be great if clarified in instructions manual :)

**Comment by ctobin111** [comment]
@guilbep @charlottegiseleweil Sorry to be clear we need to have per year so please see page 6 of the guidance manuel on our shared Google Drive:

https://drive.google.com/drive/u/0/folders/1byVzpe2RK8R3Si18wZZZBa40uCAwEwbp

The equation to go from kW to kWh/yr (here I am showing per year) is the following:

Energy [kWh/year] = Installed capacity_solar (kW) ∙PRsolar (80%) ∙ Sun hours (per day) ∙ 365.25 days/year 

It looks correct. Can I test the equation in the tool?
