### ISSUE TITLE
[DOCS] GHG Instructions manual

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/unhcr-geneva-tech-hub-app#264]
@ctobin111 Can you share instructions manual with all equations, so the tool functioning is transparent ?

We can put it in a similar way we did for Shelter : 
<img width="1792" alt="Screenshot 2023-03-16 at 10 20 46" src="https://user-images.githubusercontent.com/18381609/225571878-293e6e40-10d0-41aa-b7cf-ada59f9fecad.png">

Additionally, you can do instructional videos if you'd like. 

from #213
- [ ] In each of the screens, in (i) texts, add a mention "For detailed equations, see User Manual" (link to download) @ctobin111 feel free to edit this text

- [ ] Link the User Manual for Download in the About tab. Give us precise specs of what teyts/how you'd like it to appear

**Comment by ctobin111** [comment]
@charlottegiseleweil I had provided the link to the guidance manuel on our common Google Drive to Pierre in a previous comment. I cannot find that comment, sorry. I mentioned that this guidance manuel will be put in the UNHCR (UN Blue) format.

https://drive.google.com/file/d/1XmB-lOjNXfkPCXSw2RlfnJx9nSTp2ulu/view?usp=share_link

As far as having the same thing as André, I would have to discuss with UNHCR first. This guidance manuel has been drafted according to UNHCR's requests with the equations, references, tables incorporated. I will be making a Loom tutorial on each module once they are finalized.

**Comment by ctobin111** [comment]
Hi Charlie,


I am not sure if I can respond to these email directly as the text says.


In any case,


Please see my comment about the guidance manuel.


https://drive.google.com/file/d/1XmB-lOjNXfkPCXSw2RlfnJx9nSTp2ulu/view?usp=share_link


Thank you,


Cara

________________________________
From: Charlotte Weil ***@***.***>
Sent: Thursday, March 16, 2023 10:23:03 AM
To: EPFL-ENAC/unhcr-geneva-tech-hub-app
Cc: Tobin Cara Christine; Assign
Subject: [EPFL-ENAC/unhcr-geneva-tech-hub-app] [DOCS] GHG Instructions manual (Issue #264)


@ctobin111<https://github.com/ctobin111> Can you share instructions manual with all equations, so the tool functioning is transparent ?

We can put it in a similar way we did for Shelter :
[Screenshot 2023-03-16 at 10 20 46]<https://user-images.githubusercontent.com/18381609/225571878-293e6e40-10d0-41aa-b7cf-ada59f9fecad.png>

Additionally, you can do instructional videos if you'd like.

**Comment by ctobin111** [comment]
@charlottegiseleweil Can you clarify what you mean by: "so the tool functioning is transparent ?" Thank you!

**Comment by charlottegiseleweil** [comment]
So the users can see the equations used. See instructions manual of the Shelter tool for an example ?

**Comment by ctobin111** [comment]
@charlottegiseleweil I can take out the sections Creating New Assessments, Databases etc. in the Guidance Manuel to make them similar to what André had used. UNHCR wants to have the guidance manuel to explain the equations, constants, databases at the module level. So, I see that André made one large pdf also. Can we schedule a meeting next meeting to discuss how I should breakdown the Guidance Manuel?

**Comment by guilbep** [comment]
@charlottegiseleweil What should I do then ? wait for phase 2.II ?

**Comment by charlottegiseleweil** [comment]
@ctobin111 do you mean the users testing the modules in the upcoming months will not have a user manual eith equations ? 

Happy to help if you need with the structure of this manual, but I think it's more on your expertise as you're the closest to your users ! Perhaps just follow the structure of usage of the tool ?
