### ISSUE TITLE
[BUG] Shelter general performance

### ISSUE THREAD

**Issue by guilbep** [EPFL-ENAC/unhcr-geneva-tech-hub-app#273]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

From Caroline Ferreira Medeiros
I can also share some problems that I encountered:
- [x] The first few weeks I could not access the tool, the page was not loading;
- [ ] Difficulty filling in (the tool did not allow some areas to be filled in); Geometry + BoQ
   - [ ] Added information is not saved because fo slow netnwork (- Saved information disappears and reappears (sometimes) without explanation)
   - [x] No way to replicate: Instability (tool crashing constantly, but could be a problem with internet);

- [x] Page refreshes automatically several times, which contributes to loss of information;
- [x] Lack of options/alternatives for certain materials (e.g., our measure is in m³ and can only be included by kg);
- [x] All the problems were both for attaching materials and for filling out general information;
- [x] Verify corrugated sheet formula: weight is too high

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by andreullal** [comment]
- [ ] Review UNHCR-added projects for new materials and material forms. @andreullal 
- [ ] Review UNHCR-added projects to check embodied CO2 and H2O calculations. @andreullal 
- [ ] Review stability issues with UNHCR. @guilbep

**Comment by guilbep** [comment]
@andreullal I've improved a lot the performance. But I have several leads regarding the improvements of the App. We'll need to discuss a bit more. But it's  mainly due to the network speed of the users. I need to spend 2 to 3 days just to improve the speed behavior of the ux/network interaction/ Let's talk on the 30th of march if possible

**Comment by guilbep** [comment]
Lot of optimization possible. But the most important one were done.  (pagination, adding loading information, using remote only, to avoid pouchdb sync, etc..
