### ISSUE TITLE
[BUG] <Download files not working>

### ISSUE THREAD

**Issue by andreullal** [EPFL-ENAC/unhcr-geneva-tech-hub-app#274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

At project information page, clicking <download> button to download a file opens a new blank tab - file does not download - see screenshot:

<img width="1601" alt="Screenshot 2023-03-21 at 10 32 28" src="https://user-images.githubusercontent.com/108796343/226566881-a39e20e0-c286-45bf-9602-fbe71ff6a8a8.png">

In Chrome, tried several projects, image file.

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by guilbep** [comment]
@andreullal Could you give me the url ? I tried every images. And it works every time for me. I'll reopen the issue if I can reproduce. Video could be good also if you can reproduce. Maybe it's because of ad-block
