### ISSUE TITLE
[BUG] <Geometry information/calculations unstable >

### ISSUE THREAD

**Issue by andreullal** [EPFL-ENAC/unhcr-geneva-tech-hub-app#275]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After entering geometry information, sometimes results for volume and window area do not update. 

Also, sometimes entered numbers are lost and have to be re-entered.

<img width="1512" alt="Screenshot 2023-03-21 at 11 01 30" src="https://user-images.githubusercontent.com/108796343/226574105-8cfd3d6b-aec0-4792-bfee-d9226de793cc.png">
<img width="1512" alt="Screenshot 2023-03-21 at 11 01 47" src="https://user-images.githubusercontent.com/108796343/226574129-5e73415e-5f25-4618-bc45-2843389f5396.png">

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by andreullal** [comment]
<img width="1512" alt="Screenshot 2023-03-21 at 11 11 39" src="https://user-images.githubusercontent.com/108796343/226575903-a950fef7-7e3f-444d-bfd0-3dd5c67e2802.png">
<img width="1512" alt="Screenshot 2023-03-21 at 11 12 13" src="https://user-images.githubusercontent.com/108796343/226575915-051c9ca5-69aa-4916-ba6e-bf41a21b9631.png">

**Comment by guilbep** [comment]
@andreullal I don't see all those problems anymore; But we still have speed/performance issues while using the app with slow 3g and slow CPU. (old machines).

We'll need to decide on some changes regarding the UX. Let's talk tomorrow.

**Comment by guilbep** [comment]
@andreullal Most of the bugs are gone, but we still need to add the 'save button'
- [ ] for the info page
- [ ] the geometry page
- [ ] have a loading status for the boq when editing/creating new items

I don't want to break anything before the week-end. So right now it'll stay like this.

**Comment by guilbep** [comment]
For info @charlottegiseleweil I don't have time to make those performance improvements (decided yesterday at noon with @andreullal ) before the release1.0
I'll move this issue to phase2.2

**Comment by guilbep** [comment]
The geometry/info page is way better with the loading status.

I think it's okay the way it is. We just need some speed. Marking it as done.

For more speed, we should have made a totally different design. It's out of scope
