### ISSUE TITLE
[FEATURE] <GHG Global Results>

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#277]
@guilbep UNHCR has wanted to aggregate the results by country and by sector (WASH, Facilities, etc).

This is what they said:

Aggregate emissions per module and per country inclusive of all camps/settlements in the country and put these emissions in a pie chart per country on the map displaying the reference baseline.

We can discuss after March how to do this.

**Comment by guilbep** [comment]
Not part of milestone phase2.2 anymore; @ctobin111 you said you wanted to wait for @charlottegiseleweil in january ? is it still the case?

**Comment by guilbep** [comment]
Decided on december 2023 that it was necessary anymore; it doesn't apply to the scope of the project
