### ISSUE TITLE
[FIX](page scope): fix 'GHG Cookstoves - fixing name'

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

@guilbep 

-	Replace “default” cookstove appliance to mean “no” cookstove appliance

![image](https://user-images.githubusercontent.com/111510926/226865260-25ba4e7e-7e6c-44f1-8fb9-7d668ab79713.png)

**Comment by guilbep** [comment]
Replace Default by none and not: 'no'

done in 133a477 fix(generic): fix cookstove and others
