### ISSUE TITLE
[FIX](page scope): fix 'GHG Cooking: LPG'

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#282]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

@guilbep 

Fix: LPG units and default values for LPG, biogas and piped natural gas
-	According to Manuel’s comment, consumption on the camp and default value for LPG is given in kg/d instead of in m3/day. And the LPG default consumption value is 0.43 kg/d. We do NOT have default values for the biogas nor the piped natural gas.

![image](https://user-images.githubusercontent.com/111510926/226864934-49805bb3-6307-4bf4-b470-a99124b6ec98.png)

**Comment by guilbep** [comment]
done in 133a477 fix(generic): fix cookstove and others
We put default value to 0 for the unknown ones
