### ISSUE TITLE
[FIX](page scope): fix 'GHG Facilities / Cooking: Change in CO2 Emissions calculation'

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#287]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

@guilbep Here is a spreadsheet with the validation calculation with ratio.

https://docs.google.com/spreadsheets/d/13RgAFktveywhmKIcw_avUJdyJLR0GF6u/edit?usp=share_link&ouid=110398523820759855394&rtpof=true&sd=true

(baseline CO2 (ratio of endline (kwh/yr) / baseline (kwh/yr)) - endline CO2) / baseline CO2

Note: for the initial not powered case it should still be (endline - baseline / endline) with no ratio!

And one question: 
Pierre, note can the first b endline case be noted as b' ?

- [ ] diesel generator

**Comment by guilbep** [comment]
@ctobin111 why is it without ratio  for not powered ? 'Note: for the initial not powered case it should still be (endline - baseline / endline) with no ratio!' e.g: we decided yesterday to use the ratio so we could sum it. Do you have an example where it's not working ?
<img width="1462" alt="ratio-not-powered" src="https://user-images.githubusercontent.com/161889/228229317-03864a5c-3648-4fd2-bb76-e4833c22e44c.png">
<img width="1700" alt="not_powered_ratio" src="https://user-images.githubusercontent.com/161889/228229321-2a2f468d-b113-458b-bb73-58d316a8203f.png">

**Comment by guilbep** [comment]
done in [feat/release-1.0/feedback-facilities 150fba6] feat(ghg): abstract generic survey table
