### ISSUE TITLE
[FIX](GHG Facilities): fix 'Decimal points kWh'

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#288]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

@guilbep 
Please limit the decimal points for Diesel kWh to 2 after the comma or period.

![image](https://user-images.githubusercontent.com/111510926/228140087-e49475fb-d138-41a0-a7c6-dc1f681ab2d1.png)

**Comment by guilbep** [comment]
done in * 3425670 fix(ghg): display kwh appropriately for disels and solar
