### ISSUE TITLE
[FIX](GHG Cooking): fix 'spelling of biogas'

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#290]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

@guilbep Can you please replace "Biogass" with "Biogas"

![CookingIssue2_28_03_2023](https://user-images.githubusercontent.com/111510926/228156715-0e1f8aab-cb54-4e7c-b541-3c0f5b9661ca.jpg)
 
Thank you!

**Comment by guilbep** [comment]
done in 9c82104 fix(survey): fix typo
