### ISSUE TITLE
[FIX](GHG General): fix 'Update Locations database'

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#291]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

@guilbep 

Please use this locations database.

https://drive.google.com/file/d/12ELmWVzoMv0sz6pu36Pr8xoR0uKBMQDr/view?usp=share_link

**Comment by guilbep** [comment]
Done in ef56ec8 feat(assets)
