### ISSUE TITLE
[FIX](GHG General): fix 'Update IGES database'

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

@guilbep Please update the IGES database with the following:

https://drive.google.com/drive/folders/1uxI43d0tOXiucHH0mO3Ts38z21TNlccT?usp=sharing

This database was updated in March 2023

**Comment by guilbep** [comment]
done in  ef56ec8 feat(assets)
