### ISSUE TITLE
[GHG Databases] <GHG UNHCR Locations database>

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#294]
@guilbep 

Can you please add this text as an information circle in the UNHCR Locations database next to the header that says Daily Solar Peak Hours.

Daily solar peak hours approximated using the Longterm daily average of global horizontal irradiation (GHI). (GHI data obtained from the Global Solar Atlas 2.0, a free, web-based application developed and operated by the company Solargis s.r.o. on behalf of the World Bank Group, utilizing Solargis data, with funding provided by the Energy Sector Management Assistance Program (ESMAP). For additional information: https://globalsolaratlas.info)

**Comment by guilbep** [comment]
done in * e206b04 fix(ghg): add better text description for ghg
