### ISSUE TITLE
[FIX](GHG WASH trucking): fix 'Liters text'

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#295]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

@Avec 'New Transport' - Trucking Unit 

1) Replace 'Litres' with 'Liters' and 

2) The next line replace "Liters of Fuel Consumed" with "Liters of Fuel Consumed per Year (l/yr)"

**Comment by guilbep** [comment]
done in  ce9f4a4 fix(ghg): change text for volume of truck
