### ISSUE TITLE
[FIX](GHG Cooking): fix 'add photo to cooking'

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#296]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

@guilbep Can you please add this photo for LPG

![image](https://user-images.githubusercontent.com/111510926/228496276-19835b32-87a9-41c9-91f8-3aa05e128d77.png)

**Comment by guilbep** [comment]
@ctobin111  If you want to change the pictures for all gas stove to be this one it could be done in 10-15mn; if you want the combination of cookstove + fuel type with a default image per cookstove. It's gonna take me 1h.

what should it be ?

**Comment by guilbep** [comment]
done in 42ff751] fix(ghg): add new lpg image for cookstove modul
