### ISSUE TITLE
[GHG Cooking] <Show updates for improved cookstoves and sustainably sourced biomass>

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#310]
**Icons for Appliances (and text for hover in "")**
- "Pressure cooker" -> icon "pot-steam"
- "Heat-retaining basket" -> icon : "basket-outline"
_--> Add this icon after name of Cookstove_

Icons for Sustainably-sourced fuel
- "Sustainably sourced biomass" -> icon: tree in GREEN
_--> Add this icon after the name of the fuel_

- TODO:  add hover text
@guilbep 

Since cooking is not being tested in the field, this is not as urgent as the two previous issues.

Would it be possible to add something like an icon, image or even a narrow column to show when an improved cookstove is used or when biomass is sustainably sourced? A tree icon could be placed when sustainably sourced is marked as "yes" because this means that a tree is replanted. A pressure cooker photo could be added to the row of the baseline or endline to show that an improved cookstove device has been added. Happy to brainstorm what is simplest.

- appliance icon near cookstove name
- sustainable or not in cookstove fuel column

**Comment by guilbep** [comment]
Adding that as icons in the line of the table seems good enough. Let's discuss that thursday during the brainstorm.
<img width="333" alt="tree_example" src="https://user-images.githubusercontent.com/161889/231100739-b4c4e790-c262-4cae-8661-6514fc6fd4de.png">

**Comment by charlottegiseleweil** [comment]
@guilbep This is not fully implemented, as there was supposed to be text appearing upon hovering onto the icons. The text that needs to appear is the text in between brackets for each of the icon : 

"Pressure cooker" -> icon "pot-steam"
"Heat-retaining basket" -> icon : "basket-outline"
"Sustainably sourced biomass" -> icon: tree in GREEN

**Comment by ctobin111** [comment]
@guilbep Can you please make sure that the pressure cooker and heat retaining basket icons are the same size as the tree?

Thank you
