### ISSUE TITLE
[BUG] Notifications button not working properly

### ISSUE THREAD

**Issue by sphamba** [EPFL-ENAC/unhcr-geneva-tech-hub-app#332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When clicking on the "Notification" text, nothing happens. Notifications are shown when clicking on the bell icon specifically.

### Expected Behavior

Notifications should open when clicking anywhere on the button.

### Steps To Reproduce

See description

### Environment

```markdown
- OS: Windows 10
- Browser: Chrome 111.0.5563.149
```

**Comment by guilbep** [comment]
Problem fixed at some point in time, before v1.0.0 for sure
