### ISSUE TITLE
[BUG] error message after creating GHG

### ISSUE THREAD

**Issue by regislon** [EPFL-ENAC/unhcr-geneva-tech-hub-app#333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

add a GHG for swizterland, site = SUI, description = "test"

I've got this error : 

![image](https://user-images.githubusercontent.com/97044425/232523476-cd32cb31-ba72-4c0f-b30f-bc90543b92ba.png)

### Expected Behavior

no message 

### Steps To Reproduce

create item as bellow

### Environment

firefox

**Comment by guilbep** [comment]
no problem with that anymore
