### ISSUE TITLE
[BUG] Non-numeric characters able to be entered in numeric fields

### ISSUE THREAD

**Issue by evanjt** [EPFL-ENAC/unhcr-geneva-tech-hub-app#334]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When entering new data within "Project information" under the titles: _Number of people for setup_ and _Time for setup (days)_, non-numeric characters can be entered on Firefox. When saving and going back to the page, the values in these fields disappear.

### Expected Behavior

Numbers can only be entered

### Steps To Reproduce

1. Fill in all details in new -> Project Information. 
2. in **Number of people for setup**, type _six_
3. In **Time for setup (days)**, type _fourteen_
4. Click on a new page, then go back and see if the values stay there

### Environment

```markdown
- OS: Linux 6.2.11-arch1-1 
- Browser: Mozilla Firefox 112.0
```

**Comment by guilbep** [comment]
done in [dev 9ed62784] fix(frontend): add a rule for numbers on shelter page #334
