### ISSUE TITLE
[BUG] Shelter, unknown region when entering Greece as country

### ISSUE THREAD

**Issue by lmptfy** [EPFL-ENAC/unhcr-geneva-tech-hub-app#336]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When creating a new shelter, depending on the country when enter, the region (automatically filled by the website) is whether well-linked or is 'Unkown' (e.g. Greece).

### Expected Behavior

When inputing Greece, I'd expect Europe to show as Region. Otherwise, if not linked, the option to put it manually?

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by guilbep** [comment]
done in [dev 1201108] fix(common): countriesAsList for greece #336 and print function

Only for greece, but probably the case for other countries though
