### ISSUE TITLE
[BUG] Dialogue box disappears after pressing Esc key

### ISSUE THREAD

**Issue by evanjt** [EPFL-ENAC/unhcr-geneva-tech-hub-app#337]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When creating a new project, in the About page, clicking the **Upload Files**, then pressing escape on the keyboard will prevent the **Upload Files** dialogue box to not open again.

If escaping the dialogue box with the X button, this does not occur and reappears as per the expected behaviour

### Expected Behavior

After pressing the escape key on the keyboard, then clicking **Upload Files** again, the dialogue reappears.

### Steps To Reproduce

1. Create a new project
2. Click **UPLOAD FILES**
3. Press the Esc key on the keyboard to close the upload dialogue
4. Press **UPLOAD FILES** again
5. No dialogue appears

### Environment

```markdown
- OS: Linux 6.2.11-arch1-1 
- Browser: Mozilla Firefox 112.0
```

**Comment by guilbep** [comment]
done in [dev 3ebd54f1] fix(frontend): resolve escape bug on modal #337
