### ISSUE TITLE
[BUG] <Conflicts when creating new site>

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/unhcr-geneva-tech-hub-app#338]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="586" alt="Screenshot 2023-04-17 at 17 01 35" src="https://user-images.githubusercontent.com/18381609/232526146-c582d719-255b-4ea1-9bac-4df3503a7550.png">

### Environment

```markdown
Chrome
```

**Comment by guilbep** [comment]
We can't have conflicts on that anymore, since every new assessment has a unique id and live in its own document.

Done in v1.0.0
