### ISSUE TITLE
[BUG] Floor area not computed for "Conical roof - circular plan" shelters

### ISSUE THREAD

**Issue by sphamba** [EPFL-ENAC/unhcr-geneva-tech-hub-app#339]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When defining the geometry of a shelter, the floor area is not computed for "Conical roof - circular plan" shelters

### Environment

```markdown
- OS: Windows 10
- Browser: Chrome 111.0.5563.149
```

**Comment by guilbep** [comment]
was fixed at some point in dev
