### ISSUE TITLE
BOQ page improvements

### ISSUE THREAD

**Issue by guilbep** [EPFL-ENAC/unhcr-geneva-tech-hub-app#34]
- [x] BOQ - Clay > Brick - can length be in mm also (differs from length for other forms) same for both fired and unfired brick. (cf commit #2151851)

- [x] Enable selection of “other” material formats (unit=kg), thereby providing greater flexibility for recording non-standard materials
			— form as other unit should be kg/// have a look into it

- [x] Enable selection of "Other" material. If the correct material isn't there, user can select "other".
     - [x] User must then define the name of the material.
     - [x] User must enter the kgCO2e/kg (instead of referencing database).
     - [x] Add note stating that if kgCO2e/kg not entered, then material excluded from environmental impact calculations. 
     - [x] User must enter kg of material.

- [ ] #97
             - [ ]  i.e., say, 1 BOQ that covers 100 shelters, with calculations still providing results for individual shelter. At top of BOQ page, User prompted for number of shelters - default = 1. At bottom of page, display "Total cost" then under, "Cost per shelter" which is total cost divided by number of shelters.
- [ ] #96
          - [ ]   - e.g., initially, by shelter type (emergency/transitional/durable), by country - IT4R
			— country is optional (good to have though) (SHOULD BE MOVED TO PHASE 2)
- [x] #91
- [x] Provide additional notes/information to assist interpretation - André (text) + IT4R (implementation)
    - [x] screen shot (a-b-c. Etc ) + text notes
- [x] Enable read-only users (i.e., non-owners of a project) to copy the project then modify the copy as project owner - IT4R
    - [x] just check if it works already
- [x] Add “tukul” geometry (circular plan, conical roof) - André (sketch) + IT4R (implementation)
- [x] Enable User to specify material source “unknown”, thereby removing material from transport-related embodied CO2 calculations - André + IT4R
			— write something like source undefined

**Comment by andreullal** [comment]
For the item "Add tukul geometry", here's the diagram (same in graphics folder of GDrive):
![SSC_P4_Shelter-Tukul_220706](https://user-images.githubusercontent.com/108796343/177516466-55a94506-26b4-442e-a80e-0946c1b8835d.png)

For floor area calculation - circle area formula: A = Pi * (W/2)ˆ2

For volume calculation, sum of cylinder and cone volumes: V = (Pi * (W/2)ˆ2 * H1) + (Pi * (W/2)ˆ2 * ((H2-H1)/3)

**Comment by andreullal** [comment]
A_<<Each material listed in the Bill of Quantities is included here. Each material can be expanded to list the different forms in which the material appears in the shelter design.>>

B_<<The weight of each material is provided in order to present the relative amounts of materials used in the shelter design.>>

**Comment by andreullal** [comment]
A_"Each material listed in the Bill of Quantities is included here. Each material can be expanded to list the different forms in which the material appears in the shelter design."

B_"The weight of each material is provided in order to present the relative amounts of materials used in the shelter design."

**Comment by andreullal** [comment]
@guilbep In the first comment I've compiled a few BOQ page changes. I've marked this as a priority to get done in Phase 1 if possible.

**Comment by guilbep** [comment]
<img width="488" alt="brick_fired" src="https://user-images.githubusercontent.com/161889/189914176-2c4b3724-9012-4537-9650-953a706bf891.png">
<img width="490" alt="brick_unfired" src="https://user-images.githubusercontent.com/161889/189914186-1cb532e7-b147-47ab-ae2b-efb902e0b733.png">
@andreullal here what it looks like for brick fired/unfired in mm for all dimensions

**Comment by guilbep** [comment]
@andreullal for the other format of the materials I've updated the 'E_ShelMat copy for json export' sheet in the excel file https://docs.google.com/spreadsheets/d/1mJT188beXH1ndimj-NmglQNf8-3loB4W/edit#gid=45693204

**Comment by guilbep** [comment]
@andreullal I'll need clarification on how this works: 'Add note stating that if kgCO2e/kg not entered, then material excluded from environmental impact calculations.'  For know I've put the embodied_carbon factor to ZERO.

But I'm not sure that's what you meant.

**Comment by andreullal** [comment]
I tested the brick change - it works well.

**Comment by andreullal** [comment]
@guilbep
For the selection of "other" material:
User selects material, enters name, selects source country as usual.
From Material dropdown menu, user selects "Other"
Then, App prompts:

Embodied CO2e coefficient:   ________ kgCO2e/kg (if left blank, material excluded from environmental performance calculations)
Embodied water coefficient: __________L/kg (if left blank, material excluded from environmental performance calculations)
Quantity: _________ kg
Unit cost per kg: ________ $

Include the text in brackets above - small italic font.
