### ISSUE TITLE
[BUG] Geometry fields not sanitised

### ISSUE THREAD

**Issue by evanjt** [EPFL-ENAC/unhcr-geneva-tech-hub-app#341]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If entering numeric data into the geometry, it is possible to add multiple decimal points and therefore affects the **Result dimensions**. The values stay as 0

### Expected Behavior

It should not be possible to add more than one decimal point

### Steps To Reproduce

1. Create a new project
2. Go to Geometry
3. Add values with many decimal points
4. Witness the values in "Result dimensions", they stay as 0
![Screenshot_20230417_171049](https://user-images.githubusercontent.com/8609463/232530347-df3e11d1-8ce1-4df1-b8c6-16608a9dc78b.png)

### Environment

```markdown
- OS: Linux 6.2.11-arch1-1 
- Browser: Mozilla Firefox 112.0
```

**Comment by guilbep** [comment]
done in [dev c5e46b37] fix(frontend): add a rule for numbers on shelter page #341
