### ISSUE TITLE
[FEATURE] geolocation and country limits

### ISSUE THREAD

**Issue by regislon** [EPFL-ENAC/unhcr-geneva-tech-hub-app#342]
inconsistency between maps and entries :

![image](https://user-images.githubusercontent.com/97044425/232530774-71eb437e-cb67-47ab-9f7d-c98d10daf400.png)

Is it possible to add a checker

**Comment by guilbep** [comment]
Decided that it's too complicated for the worth. Out of scope.
It'll be the responsibility of the users.
