### ISSUE TITLE
[FEATURE] message more clear

### ISSUE THREAD

**Issue by regislon** [EPFL-ENAC/unhcr-geneva-tech-hub-app#346]
![image](https://user-images.githubusercontent.com/97044425/232534240-b49b4182-da8b-41f4-8f79-5f0d6b819422.png)

**Comment by guilbep** [comment]
not a problem for the researcher. 
![chnage](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/161889/5db120e5-078c-4c68-86ef-83c89d674040)
We changed the text though
