### ISSUE TITLE
[BUG] Dead links in footers' logos

### ISSUE THREAD

**Issue by sphamba** [EPFL-ENAC/unhcr-geneva-tech-hub-app#347]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

"Geneva technical hub" and "UNHCR" logos lead to a [404](https://www.unhcr.org/publications/brochures/6229f4184/geneva-technical-hub-brochure.html)

**Comment by guilbep** [comment]
fixed, everything point to https://www.unhcr.org/publications/brochures/6229f4184/geneva-technical-hub-brochure.html
