### ISSUE TITLE
[BUG] <GHG: General screen is marked as Saved in grey before saving>

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#348]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

@guilbep I see that the general screen is saved and grey before saving it. Preferably, the blue save button would be displayed before it is saved.

![image](https://user-images.githubusercontent.com/111510926/232726047-d9d33021-b2fb-4085-96ed-5406b0cf0a48.png)

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by ctobin111** [comment]
@guilbep Perhaps related to this is that there is no automatically calculated kwh/year if the kW are input. Maybe this is because the daily solar hours was marked as 0? Will not the default value for this camp be chosen?

![image](https://user-images.githubusercontent.com/111510926/232726986-0dfccb92-d6cd-4990-b451-34b1c790f4b3.png)

**Comment by ctobin111** [comment]
@guilbep If you want to check, I tried this in the following assessment: Bangladesh, Bhasan Char, TestMultipleEndlines

**Comment by guilbep** [comment]
If the solar was 0, then the kwh/year will be zero. Simple as that @ctobin111 

What we may need is a warning for the user on the information page that the solar is 0.

Also check the reference data, it is zero for bashan

0
--

**Comment by guilbep** [comment]
@ctobin111 I don't think that's a bug concerning the 'saved' 'saving' 
That's what we agreed on; When you arrive at the page, it it already 'saved' you want to be able to save only once the user changed it ?

**Comment by ctobin111** [comment]
@guilbep The grey box is good as it stands. Thank you!
