### ISSUE TITLE
[FEATURE] <GHG - warning across all modules>

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#350]
@guilbep UNHCR wants that they can have the warnings pop-up so that the user must click on them before being able to continue to show understanding of the warning. Then the warning should stay as it is now in a red box in the middle of the baseline and endline data entry page.

Please ping me on Jabber if you want to discuss.

The Facilities and WASH modules must be released by the end of this week for testing in the field so this is why I have added this as a priority.

Merci!

**Comment by guilbep** [comment]
@ctobin111  I' m going to do the following things:

- have the same text for the warnings pop-up as the current warning red box
- I'll display the popup each time the user make a change in a endline that results in a difference.

Please confirm before I can start Implementatiojn

**Comment by ctobin111** [comment]
@guilbep yes. this works.

**Comment by guilbep** [comment]
done in release 0.10.1
