### ISSUE TITLE
[BUG] <WASH Trucking - Change in Emissions>

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#351]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

@guilbep The change in emissions calculations in Wash trucking are not working properly.

Please see the screenshots attached.

Basically, -	When checking/unchecking a possible endline (from multiple endlines) from the list, the change in emissions does not update automatically. In the case attached, when selecting a”, there should not be a change in the emissions. Even if the previous modification represented a change.
[COMMENTS ON WASH TRUCKING Module 24042023.docx](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/files/11319041/COMMENTS.ON.WASH.TRUCKING.Module.24042023.docx)

When there can be multiple endlines the ratio should be used as shown in the equations attached. 

Please let me know if you have any questions.

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by charlottegiseleweil** [comment]
@ctobin111 can you specify exactly the equation that need to be corrected ? Please send a URL to the example you screenshotted in your doc. It looks like that line changed indeed, and the total changes, so indeed the ratio changes and there is a change in emission. @guilbep is looking into it

**Comment by guilbep** [comment]
here is the url. https://unhcr-tss.epfl.ch/green_house_gaz/PK/2088/surveys/ad8cbe51-8b79-4e0a-ae19-15d30a05ea63?category=WASH&subcategory=Trucking

I'll have a look at why the percentage is not zero.. we may have a problem with the formula

**Comment by nmontoya03** [comment]
Equations in PDF version:
[COMMENTS.ON.WASH.TRUCKING.Module.24042023.pdf](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/files/11325568/COMMENTS.ON.WASH.TRUCKING.Module.24042023.pdf)

**Comment by guilbep** [comment]
@ctobin111 concerning the change in emission not being zero: the problem is coming from the approximation of trucks which is correct.
100 m3 == 43 trucks. 50m3 == 22 trucks because we Ceil the floating value of trucks ceil(21.5) == 22.

We should probably display that information somewhere ? so that it's not confusing for the users ?

I also expected it to be 0% change in emission. And it was not clear why it was not the case.

@charlottegiseleweil or @ctobin111 any suggestions ?

**Comment by guilbep** [comment]
done in release 0.10.1
