### ISSUE TITLE
[BUG] <Menu title is the previous selection of shelter, upon logging out and returning to main screen>

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/unhcr-geneva-tech-hub-app#355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Use Shelter tool to view a specific shelter assessment. 
Go back to Login screen / Main apps selection screen : the menu title is stil the old shelter selected . See screenshot. 

### Anything else?

<img width="1601" alt="Screenshot 2023-05-02 at 11 33 39" src="https://user-images.githubusercontent.com/18381609/235631600-3f5c5859-7ef5-4a41-ad36-d7ab8e1a1a21.png">

**Comment by guilbep** [comment]
Cannot reproducing that anymore. It was fixed in june maybe
