### ISSUE TITLE
[FEATURE] <GHG Cooking - Adding S3 icon when charcoal is used>

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#358]
- Add a tooltip on a '(S3)' text in parenthesis containing the following text: "Exceptionally, Scope 3 emissions relative to the production of charcoal are being considered due to their high impact." In the table on the column fuel

For charcoal and carbonized briquettes fuel only

---
@guilbep Layla had a great comment. We cannot see that we are considering the production of charcoal or Scope3 emissions. So, when the user checks charcoal as a fuel source, can you kindly put a S3 icon with a hover explanation that says "Exceptionally, Scope 3 emissions relative to the production of charcoal are being considered due to their high impact."

**Comment by charlottegiseleweil** [comment]
@ctobin111 We'll integrate Layla's feedback after the testing phase as we want to minimize changing the tool during testing phase - we'll just update the clarifications essential to understanding (like the hover thing issue #130 and the important bugs indentified - but all these features feedback will be implemented AFTER testing phase). 

You can assign corresponding milestones to these feedbacks: "GHG_Feedback_...". Ok?

**Comment by ctobin111** [comment]
@charlottegiseleweil Sound good.

**Comment by guilbep** [comment]
@ctobin111 By the way. We lack information regarding this issue.

- What is the icon ?  something like this ? https://w7.pngwing.com/pngs/746/978/png-transparent-greenhouse-gas-computer-icons-font-miscellaneous-text-logo.png

- Where do we put the icon ?

Thank you

**Comment by guilbep** [comment]
@ctobin111 please see question above
