### ISSUE TITLE
[BUG] <GHG Cooking - Solar thermal cookers > 

### ISSUE THREAD

**Issue by nmontoya03** [EPFL-ENAC/unhcr-geneva-tech-hub-app#361]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When selecting the Solar cooker with Thermal solar as cookstove fuel, the message “Unknown fuel type” appears (See the screenshot). The total emissions are not visible in the cookstove list, and it is not possible to save the baseline either when only solar cookers have been created. @guilbep Could you kindly check this issue please? 

![image](https://user-images.githubusercontent.com/131168517/236418327-673ccb26-d500-4574-a885-df925322f16b.png)

### Expected Behavior

The equation for the thermal cookstove is presented in the image below with the same emission factor that we used for solar energy in the Facilites Module. 

![image](https://user-images.githubusercontent.com/131168517/236485467-660e9f31-cdec-4658-9b11-3202837e29eb.png)

It is expected to see 0 in the column for total CO2 emissions for the solar cooker and to be able to save the baseline after creating a new solar cooker.

Thank you!

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by guilbep** [comment]
@nmontoya03 as I understand the equation: it's just 'ZERO' So I put zero.

Side question regarding the thermal consumption. In the interface @ctobin111 @nmontoya03 we only display the fuel consumption for diesel and solar..

<img width="1644" alt="diesel_solar" src="https://user-images.githubusercontent.com/161889/236791990-f5185e4f-d762-420c-a269-efbc3d9c5f8e.png">

Is that an error ? Maybe we should display nothing for consumption ? or we should probably have one column with all the different type of fuel consumption ? IF that's the case that'll need a new issue

**Comment by nmontoya03** [comment]
Thank you Pierre! The consumption in the solar cookers should be shown in the column: Solar (kWh/yr) estimated. For solar cookers, we can provide a default value for the "Solar (kWh/yr) estimated" of: ~0.02 kWh/d/person. Similar to the other fuels, this default value should be multiplied by the household size.

In addition, in the case of solar thermal cookers, it is not pertinent to ask the user whether he/she knows the fuel consumption, neither to have the option of cookstove appliance. Could you please hide these options when a solar cooker is created? 

Thank you so much and we can discuss about this in more detail if needed.

**Comment by guilbep** [comment]
@nmontoya03 don't hesitate to @guilbep me next time so I can receive some notification.
I'm sorry I'm seeing this only now. By the way, your comment shoud be in a new issue. Let's discuss tomorrow
