### ISSUE TITLE
[FEATURE] <Exclude partially completed projects from the scorecard>

### ISSUE THREAD

**Issue by andreullal** [EPFL-ENAC/unhcr-geneva-tech-hub-app#366]
Currently, partially completed projects are included in the scorecard, leading to many projects presenting "0" values for the six metrics. We need to find a way to exclude projects from the scorecard until they are fully completed.

@guilbep and @andreullal to discuss

- add a 'completed' status field

# What does it means:
 1) Project information should be completed (all the fields are now mandatory)
 2) Geometry should be completed --> Should have a floor + volume + window area if not it's completed
         - window dimensions can be zero,zero,zero (no windows, windows are optionals)
 3) add toggle button somewhere at the top to trigger the 'completed' status of boq 
  ''Boq comlete ?" looks like this with a switch:   "No ( o        ) Yes" (with no activated here for instance).  in one line
   - Should be placed left of the 'new item' button
 4) For technical perf + habitability
      -> replace the checkbox by a 'yes or no' switch or not applicable.
      -> by default it will be 'inderminate' (undefined value)
      -> The form will be completed when every field is either 'yes or no' or not applicable
      -> Add a text for each final sub section (leaf of group). in gray, small text italic ( checkmark icon (v/x)  'space' complete or incomplete)
      -> For the radio, use the radio button (Default display)
      

5- for loading: just add a circle rotating instead of a linear one

**Comment by guilbep** [comment]
It's done as of 31th of October 2023
