### ISSUE TITLE
[FEATURE] Monitoring Front-End

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/unhcr-geneva-tech-hub-app#37]
- Explore if any free/OSS option
- else develop it or install a paid soln (install before July vacations :))

**Comment by guilbep** [comment]
Right now the best tool is Sentry.io imho, (here are the prices: https://sentry.io/pricing), we could start for free to see if it matches with our users. But we also have (datadog & logrocket). They all have a free price entry point: https://blog.bitsrc.io/5-different-tools-for-frontend-monitoring-79db94014d

On the open-source side: right now I have, but I'll keep looking: https://opentelemetry.io/docs/instrumentation/js/getting-started/
Uptrace: https://bestofvue.com/repo/uptrace-uptrace. 
https://vuejsexamples.com/distributed-tracing-using-opentelemetry-and-clickhouse/
https://lightstep.com/opentelemetry/js

@blueur If you have any idea about other tools, don't hesitate to share.

**Comment by blueur** [comment]
Distributed tracing: 
- https://zipkin.io/
- https://www.jaegertracing.io/

**Comment by guilbep** [comment]
- Update monitoring of the service status is one on icinga2: https://enac-itmonitoring.epfl.ch/icingaweb2/search?q=unhcr#!/icingaweb2/monitoring/host/show?host=unhcr-tss
- I will add sentry monitoring

**Comment by guilbep** [comment]
<img width="1789" alt="monitoring_sentry" src="https://user-images.githubusercontent.com/161889/225916629-95576d9b-8a06-4693-901e-46e25e6eebba.png">
We will try sentry for two weeks. and Then we will decide if we want to pay or not: it's. 29dollars per month.

There is an open source version and I could try to set-it-up my self. But If I spend 8h on it with no guarantee of making it work it would cost 600 .-chf equivalent of 20Months of sentry.. 🗡️
