### ISSUE TITLE
[FIX](GHG All): fix 'Digits after decimal points or commas'

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#372]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Expected Behavior

@guilbep UNHCR requested that the number of digits or chiffres after the comma is limited to two in all cases and to no digits after the comma when the estimation symbol is used ~ . An exception is the latitude and longitude numbers. We can go through the tool together if it is easier.

**Comment by guilbep** [comment]
@ctobin111 Do you have any update on this ?

To sum up what we said the other day:

- It's not possible for inputs without losing precision and having different results. But we could agree that we prefer to have  not precise results but only two digits ?
@nmontoya03 @ctobin111 It'll be nice to have a decision/comment on this issue so we know that we can close it.


Thank you

**Comment by guilbep** [comment]
@ctobin111 @nmontoya03 :) Any updates ?
