### ISSUE TITLE
[FIX](GHG General): fix 'Link and notice for access to Guidance manuel'

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

@guilbep Could you kindly provide a link to the Guidance manuel on the welcome page where the tools are described in words? Then, the users in the field have said that the link by the i symbol is not obvious. So ideally, a text box could be placed that says "Click here for access to the Guidance Manuel"

**Comment by guilbep** [comment]
<img width="1754" alt="new-home-page" src="https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/161889/fb51573b-78ac-436b-899a-1146a00362e9">
Hello @ctobin111 @andreullal I've added a new btn as asked by Cara to link the guidance manual on the home page.

If you have any suggestion regarding this feature. Please comment below before I deploy to production next week.

Thank you.
