### ISSUE TITLE
[FIX](GHG Cooking): fix 'Equation and emission factor Carbonised briquettes'

### ISSUE THREAD

**Issue by nmontoya03** [EPFL-ENAC/unhcr-geneva-tech-hub-app#374]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Expected Behavior

Given the characteristics of carbonized briquettes, the equation to calculate the emissions should be similar to the one used for charcoal (please see equations below). We also have updated emission factors for carbonized briquettes according to comments received from Manuel.

@guilbep Could you please kindly update the equation and the emission factors for carbonized briquettes? 

- Equation for carbonized briquettes when fuel consumption is unknown:

![image](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/131168517/6e602922-0873-4a45-8375-8bb46273927d)

- Equation for carbonized briquettes when fuel consumption is known:

![image](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/131168517/afaa1aad-3394-4b6b-ae92-5e5f2fc02a97)

Updated emission factors for carbonized briquettes:

Energy - Cookstove - Fraction of nonCO2 emissions (%) Carbonized briquette production, 0.4227, https://www.ipcc-nggip.iges.or.jp/public/2019rf/pdf/2_Volume2/19R_V2_4_Ch04_Fugitive_Emissions.pdf
Energy - Cookstove - Fraction of nonCO2 emissions (%) Carbonized briquette combustion, 0.1202, https://www.ipcc-nggip.iges.or.jp/public/2006gl/pdf/2_Volume2/V2_2_Ch2_Stationary_Combustion.pdf
Energy - Cookstove - Efficiency (TCO2e/T) Carbonized briquette production, 2.5836, https://www.ipcc-nggip.iges.or.jp/public/2019rf/pdf/2_Volume2/19R_V2_4_Ch04_Fugitive_Emissions.pdf
Energy - Cookstove - Efficiency (TCO2e/T) Carbonized briquette combustion, 2.0879, https://www.sciencedirect.com/science/article/pii/S246822761930763X

Thank you so much and please let me know if you have any question.

**Comment by guilbep** [comment]
Hi @nmontoya03 could you show me what exactly changed ? it would be faster than trying to decipher the equation ? I'm available on the 24th of may (tomorrow)

**Comment by nmontoya03** [comment]
Hi @guilbep,

Previously we were using the following equation for carbonized briquettes (case for fuel consumption unknown):

![image](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/131168517/98d46e23-e93a-493e-aeb4-254ce1b0b169)

For the new equation, we have two emission factors and their corresponding % non-CO2 emissions (Exactly how we did for charcoal):

![image](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/131168517/841e4da1-bfbb-4a4f-9c65-8e7574bb2751)

Thank you and please let me know if you have any other question or if you prefer to talk about that in a call.

**Comment by nmontoya03** [comment]
@guilbep Exactly. No changes for non-carbonized briquettes. Thank you.
