### ISSUE TITLE
[FEATURE] <Allow for non-UNHCR user registration>

### ISSUE THREAD

**Issue by andreullal** [EPFL-ENAC/unhcr-geneva-tech-hub-app#376]
Allow non-UNHCR users to register.
Registration can be restricted to approved email domains - i.e., email addresses from a list of organisations that are members of the Global Shelter Cluster.
OR
Requests for access could be sent to Rama for approval (not preferred, given extra work and reliance on individual)

**Comment by guilbep** [comment]
@andreullal  is it okay to allow for google login ?
Instead of creating/duplicating login/password for a list of organization.

**Comment by andreullal** [comment]
I’m meeting with Rama tomorrow and will discuss her then. Are you available to speak quickly tomorrow about time estimates for different user registration options?

A


Le 25 mai 2023 à 10:12, Guilbert Pierre ***@***.***> a écrit :

﻿

@andreullal<https://github.com/andreullal> is it okay to allow for google login ?
Instead of creating/duplicating login/password for a list of organization.

**Comment by guilbep** [comment]
Hello @andreullal I'm available all the week (5th of june till thursday 8th off on friday)

**Comment by andreullal** [comment]
If feasible, restrict registrations to .org emails.

**Comment by guilbep** [comment]
<img width="1800" alt="Untitled_registration" src="https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/161889/37ca9c49-3be7-43dc-bace-5423f3b0ba8b">
<img width="1800" alt="Untitled 2" src="https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/161889/630a85b8-d585-41e3-aa55-2a440ba0096d">

**Comment by guilbep** [comment]
done in 0.14.0
