### ISSUE TITLE
[FEATURE] <Allow for definition of projects as "private" or "public">

### ISSUE THREAD

**Issue by andreullal** [EPFL-ENAC/unhcr-geneva-tech-hub-app#377]
Public projects are included in the project list page for all users to see, access in read-only mode, and duplicate.
Private projects are visible to the Owner and Administrators only.
Projects are public by default.

Add a checkbox to the Project Information page.
- Last item after flood risk and seismic risk. (it's okay on the top)
- 
- 'inquiète- "Make project public (public projects are included in the project page, with read-only access for other users)" [  ]
- Default checked (meaning public)

**Comment by andreullal** [comment]
Text for "I"

Public projects are visible for all users, enabling dissemination of shelter designs and assessments. Private projects are visible to the project owner only.

**Comment by guilbep** [comment]
Done in 0.14.0
