### ISSUE TITLE
[FEATURE] <ghg> common

### ISSUE THREAD

**Issue by guilbep** [EPFL-ENAC/unhcr-geneva-tech-hub-app#379]
- add background-color when not in mode
<img width="1497" alt="retour-globaux" src="https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/161889/0fcfe5d0-ae9a-4269-92db-a5ebd7e801f2">

**Comment by ctobin111** [comment]
@guilbep Hi Pierre, will you work on this?

**Comment by guilbep** [comment]
done @ctobin111  in v0.15.0
