### ISSUE TITLE
[FEATURE] <GHG Solid Waste Module Specifications>

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#382]
@guilbep Please find the solid waste specifications in this common folder:

https://drive.google.com/drive/folders/1qVlynXhB0jqBlmTgEiAgLZ1QBn5_YcAJ?usp=sharing

**Comment by charlottegiseleweil** [comment]
Can you ping @guilbep when you consider those specs final @ctobin111 ? Because Natalia's last email you're still preparing regional DB. (July 11)

**Comment by guilbep** [comment]
done in release v0.15.0
