### ISSUE TITLE
feat(ghg-cooking) better solar cooker info

### ISSUE THREAD

**Issue by guilbep** [EPFL-ENAC/unhcr-geneva-tech-hub-app#385]
- [ ] Discuss if we should display something or not regarding the fuel consumption

Hi @ctobin111  @nmontoya03 I removed the diesel and grid power info on the table because as we said, it's confusing to not have the correct info in the table <img width="1502" alt="fuel consumption" src="https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/161889/a5187fde-edb0-419b-af8b-b097c0b661c1">
display only one column for fuel quantity with the appropriate dimension/suffix (make a screenshot for validation)

I tried some things on my side but it's not clear. I'll wait for a decision on your part.

For instance for wood we have 17 kg/day/hh for some fuel as the info
But for grid we may have an hybrid mix of 17 liters of diesel and 100kwh/day/hh for grid and for solar we have the installed and total power per year. Same for thermal power

What should we display ?

**Comment by nmontoya03** [comment]
Hi @guilbep . @ctobin111 and I have been discussing this issue and we could present the fuel and energy consumption in an additional column in the summary table for the cooking module. In this column, we should show the annual fuel/energy consumption with the corresponding units for each fuel and energy source (please see the example in the image). 
 
![image](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/131168517/bced7ece-f677-4389-b75a-1bdd9ae8ecad)

In the case of the hybrid mix, the most important aspect to display is the total energy consumed by the electric stove powered by the hybrid mix. However, Cara was wondering if it would be possible to hover over the value of total consumption for the hybrid mix to see the details about the energy sources.
 
![image](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/131168517/8578a219-369f-4762-be30-206458c2f793)

Thank you so much Pierre and please let us know if this option is feasible. We can also discuss other possibilities to display the information.

**Comment by guilbep** [comment]
<img width="1762" alt="AnnualFuel_Consumption" src="https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/161889/deb835f0-45a9-428d-88e5-58805898c0eb">

@nmontoya03 I just need to test it with Cooking/Lighting and Facilities to see if every thing is correct.

I'm not totally satisfied, not sure why. Probably the number of decimal and number formatting.

Tell me what you think ?
@ctobin111  if you have time also ?

**Comment by guilbep** [comment]
Done as of october 2023
