### ISSUE TITLE
[FIX](GHG Cooking): fix 'Redundancy in questions electric cookstoves powered by diesel generators'

### ISSUE THREAD

**Issue by nmontoya03** [EPFL-ENAC/unhcr-geneva-tech-hub-app#389]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

For electric cookstoves powered by diesel generators, we are asking twice if the user knows the fuel consumption:
![image](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/131168517/23a17463-2f3e-4f0a-9c16-c1a1db754874)

However, after selecting "no" in both fields  (indicating the consumption is unknown) no default value for diesel consumption or energy estimated is shown:
![image](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/131168517/c956056a-10da-41c5-a37b-c59a21744641)

After discussing with @ctobin111, the proposed structure specifically for electric cookstoves powered by diesel generators would be:

![image](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/131168517/c14345c9-b70d-4963-a1f5-26007d956e06)

@guilbep do you think we could implement this structure for electric cookstoves powered by diesel generators? Thank you so much!

**Comment by guilbep** [comment]
<img width="571" alt="cookstove_yes" src="https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/161889/9bc3c208-0af4-48a7-812d-10f24a25a5e4">
<img width="548" alt="cookstove_no_no_with_appliance" src="https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/161889/fcbc8d47-6d58-43bd-84c3-9dca9d6b19fc">
<img width="575" alt="cookstove_no_yes_with_no_appliance" src="https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/161889/ae8a12df-85b8-4499-b168-f5d6aa080924">
<img width="498" alt="cookstove_no_unknown" src="https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/161889/b4b5760f-ff73-4846-b324-437ecbf6f741">

Are you okay with those configuration ? Please have a look at the 'appliance' one with the name file: cookstove_no_no_with_appliance.png

**Comment by nmontoya03** [comment]
@guilbep It looks great, thank you! I just wonder, in the case of unknown number of litres and unknown generator size and working hours, might we present the default value for the fuel consumption (varying depending on the selected cookstove appliance)? And also, would this new structure impact the Facilities Module? Thank you again!

**Comment by guilbep** [comment]
@nmontoya03 Yes, it still does not work. I'm trying to fix this :)

**Comment by guilbep** [comment]
done in release 0.15.0
