### ISSUE TITLE
[FIX](GHG Cooking): fix 'Remove cookstove appliance and fuel known fields for Hybrid Mix '

### ISSUE THREAD

**Issue by nmontoya03** [EPFL-ENAC/unhcr-geneva-tech-hub-app#390]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Expected Behavior

@guilbep @ctobin111  In the case of electric cookstoves powered by Hybrid Mix, we cannot provide a default value for the energy mix so it is not pertinent to ask the user whether he/she knows the fuel consumption, neither to have the option of cookstove appliance. @guilbep Could you please hide these options when a electric cookstove powered by Hybrid Mix is created? Thank you so much!

**Comment by guilbep** [comment]
done on release 0.15.0
