### ISSUE TITLE
[FIX](GHG Cooking): fix 'Name change for Kerosene cookstoves'

### ISSUE THREAD

**Issue by nmontoya03** [EPFL-ENAC/unhcr-geneva-tech-hub-app#392]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

@guilbep In the Cooking module / Liquid fuel cookstove, could you please change the name "Kerosene/paraffin" to "Kerosene"? It would be just a name modification since we are correctly using the emission factor for kerosene in the calculations. Thank you!

**Comment by guilbep** [comment]
Done and deployed to unhcr-tss-test.epfl.ch
