### ISSUE TITLE
[BUG] <BOQ selection of material "Steel fixing..." then form "other" doesn't work>

### ISSUE THREAD

**Issue by andreullal** [EPFL-ENAC/unhcr-geneva-tech-hub-app#404]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Selection material <Steel fixing...> then form <Other> leads to error message for unit. See screenshot:

<img width="1569" alt="Screenshot 2023-06-29 at 10 55 49" src="https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/108796343/553889aa-3531-4157-8aef-c3dd55d39706">

### Expected Behavior

selecting for <other> should then enable selection of unit <kg>

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by guilbep** [comment]
@andreullal We're okay with the fact that the unit should be "KG" for the other of every material ?

**Comment by guilbep** [comment]
@andreullal Okay. I've found out why The prefix for Steel fixing was STE same as Steel. I renamed the identifer with STEF; It will be: STEFX-H_, STEFX-L_, STEFX-N_, STEFX-OTH_

So I'm able to determine the OTH_ suffix in the identifier.

Btw, we were missing two other form in the csv for Rubber and Grass ; So I duplicated the line and changed only the 'local' to false.

Please, advise.

But it's working again on my side.
