### ISSUE TITLE
[FIX](BOQ): fix 'for material <sand>, repeat form <sand>'

### ISSUE THREAD

**Issue by andreullal** [EPFL-ENAC/unhcr-geneva-tech-hub-app#405]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

The fields for material form in the BOQ and the box diagrams (environmental impact) should not show .. for sand form.

<img width="1569" alt="Screenshot 2023-06-29 at 16 28 41" src="https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/108796343/8a0ac1a1-0f14-4e93-9528-65bcff724043">

![Screenshot 2023-06-30 at 10 17 57](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/108796343/72bb0ba2-1223-4886-b091-db98c223e349)

### Anything else?

currently, only option for sand form is <..>. This .. then shows up in the BOQ and the box diagrams.

**Comment by guilbep** [comment]
Same problem with Grass and Rubber @andreullal so I'll do the same.

I'll display Sand instead of '..' for Sand material
Rubber for Rubber and Grass for Grass.

**Comment by guilbep** [comment]
done in v0.15.0
