### ISSUE TITLE
[BUG] <Password reset function not working>

### ISSUE THREAD

**Issue by andreullal** [EPFL-ENAC/unhcr-geneva-tech-hub-app#407]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Attempt to reset password hangs after email address entered (no email received). Using Safari, with EPFL administrator account.

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by guilbep** [comment]
Update on the 17th of july; I've ask IT to unblock the machine.

**Comment by guilbep** [comment]
It's working now; please confirm @andreullal  when you're back

**Comment by guilbep** [comment]
update: it's working for several user. I'll mark it as done

**Comment by andreullal** [comment]
Yes, it’s working correctly now.


[EPFL logo]<https://www.epfl.ch/>
André Ullal
Scientific Collaborator
Phone: +41 21 695 72 19
Mobile: +41 78 751 99 38

On 17 Aug 2023, at 13:56, Guilbert Pierre ***@***.***> wrote:



update: it's working for several user. I'll mark it as done
