### ISSUE TITLE
[FIX](page scope): fix 'replace me'

### ISSUE THREAD

**Issue by guilbep** [EPFL-ENAC/unhcr-geneva-tech-hub-app#413]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

Consistency across module regarding texts:

The current behavior: We have "Percentage of total households" for the cooking module.
We have Percentage of total households for Lighting module.

We have "% of total waste generated" for The Domestic Solid Waste module.

What should we do ?

A) Nothing.

B) Replace Percentage of by "% of total households"

**Comment by nmontoya03** [comment]
@guilbep @ctobin111 I would say option A) Nothing. In the case of this module, the user will provide values of waste generation per person and waste composition based on averages of the whole camp. Therefore, we don't expect to represent in the tool differences between households but the total quantities of materials and the associated emissions.

**Comment by guilbep** [comment]
Thanks @nmontoya03 ! I'm closing it now
