### ISSUE TITLE
[FEATURE] <GHG SOLID WASTE MODULE> display reference efficiency factor for region dependent configuration

### ISSUE THREAD

**Issue by guilbep** [EPFL-ENAC/unhcr-geneva-tech-hub-app#414]
@ctobin111 It still needs to be done in my opinion.

@nmontoya03 Do you think we need to display the region-country correspondance list ?

**Comment by nmontoya03** [comment]
Yes. I think we should show the regional emission factors used in the solid waste module and the region-country correspondence list. To avoid creating many different reference tabs, could we add a new tab with all the regional emission factors and merge the region-country correspondence list into an existing reference tab (such as UNHCR LOCATIONS)? What do you think @guilbep @ctobin111 ?

**Comment by ctobin111** [comment]
@nmontoya03 sounds great to add the regions next to the countries already in the UNHCR locations db. @guilbep ideally we could put the regional emission factors at the bottom of the GHG db but we could also add in a new db tab if you think it is simpler. If we add in a new tab for the regional emissions factor, we should create a link and explanation from the GHG db.

**Comment by guilbep** [comment]
@ctobin111 I'll put the regions below the countries for solar as another table. We have more countries than for solar.. If I add the region for the solar table.. it's like hiding countries.
