### ISSUE TITLE
[FIX](GHG): fix 'update Result page'

### ISSUE THREAD

**Issue by nmontoya03** [EPFL-ENAC/unhcr-geneva-tech-hub-app#421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

This is a Manuel's comment from his feedback on 21/07/2023:

Result page should have a clear and prominent indication that only Scope 1 and Scope 2 emissions are considered. The current information in a pop-up icon is not sufficient (cf. screenshot below). Immediately when looking at the results, its limitation to Scope 1 and Scope 2 should be visible. Can we for instance add text to the right of the title “Results”?

![image](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/131168517/18464cd6-6734-4b0a-9e76-15110e8747e4)

Furthermore, @guilbep could you please add in the message the following sentence: "Exceptionally, Scope 3 emissions associated with feedstock production and/or processing of charcoal, ethanol and vegetable oil are considered due to their high impact relative to the total emissions."

Thank you!

**Comment by guilbep** [comment]
<img width="1738" alt="Results" src="https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/161889/1a5afca0-65d7-4afd-a9a8-74943ac15bf8">
@nmontoya03 For now, it will look like this. If it's not what you wish for please advise on design @ctobin111  :) Thank you
