### ISSUE TITLE
[FIX](GHG Reference data): fix 'Title for country-region correspondence list'

### ISSUE THREAD

**Issue by nmontoya03** [EPFL-ENAC/unhcr-geneva-tech-hub-app#430]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

Thank you @guilbep for having added the correspondence list as part of the UNHCR LOCATIONS Reference database. Could you please update the title of the correspondence list with the following text: "Geographic Regions from UN M49 Standard (https://unstats.un.org/unsd/methodology/m49/overview/). Regions information used to calculate regional emission factors for the Solid Waste module."

**Comment by guilbep** [comment]
done in #f883fbd
