### ISSUE TITLE
[BUG] <BOQ - Unable to enter quantities to 3 decimal places - e.g., 0.001>

### ISSUE THREAD

**Issue by andreullal** [EPFL-ENAC/unhcr-geneva-tech-hub-app#432]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When entering a new BOQ material, the popup dialogue doesn't allow entry of small amounts to two decimal places.

e.g., for steel, kg, I can enter 0.1, though I can't enter 0.09. Same for other materials and units that I've tested - in general, it seems that numerical entries can only be to one decimal place

### Expected Behavior

All numerical entries should allow up to three decimal places, since some of the quantities might be very low, particularly for m, m2, m3 and kg units. E.g., the users should be able to enter: 0.1, 0.11, 0.111

### Environment

```markdown
- OS:
- Node:
- npm:
```

### Anything else?

![Screenshot 2023-09-21 at 15 36 47](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/108796343/7ba8e589-63ab-4f5f-a7e8-5bfd1923007e)

**Comment by andreullal** [comment]
@guilbep - could address this urgently? I hope it's just a quick matter of enabling 3 decimal point numerical data entry for all the material inputs.

**Comment by guilbep** [comment]
@andreullal it's going to be quick a priori :) Thanks for noticing!

**Comment by guilbep** [comment]
It should be fixed now, could you confirm? @andreullal  ?
