### ISSUE TITLE
[FIX](GHG Intro Page): fix 'New UNHCR Locations DB with solar hours'

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#435]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

@guilbep 

Hi Pierre,

Please find the link to the revised table for the locations. 

[]((https://docs.google.com/spreadsheets/d/1VVxsSS-KCUmP-giKZwlARNmw5RSSZHUQ/edit?usp=sharing&ouid=110398523820759855394&rtpof=true&sd=true))

This table was provided by the UNHCR GIS group. Please use the table in the second tab. REF Locations

Please note that the pcode is indicated as the unique identifier in the first tab Metadata. You might want to consider this in your assessment work.

Please let me know if you have any questions.

Best,

Cara

**Comment by ctobin111** [comment]
@guilbep not sure why the link is not copying above

https://docs.google.com/spreadsheets/d/1VVxsSS-KCUmP-giKZwlARNmw5RSSZHUQ/edit?usp=sharing&ouid=110398523820759855394&rtpof=true&sd=true

**Comment by guilbep** [comment]
done
