### ISSUE TITLE
[BUG] <GHG General> Kenya Kakuma

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#436]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

@guilbep When one tries to add Kakuma, the camp name jumps to Test2. This is the test platform. Kakuma cannot be chosen.

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by guilbep** [comment]
not the case anymore since the migration!  @ctobin111 could you confirm ?
