### ISSUE TITLE
[FIX](GHG header): fix 'Remove Offsets from the GHG menu bar'

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#437]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

@guilbep Can you kindly remove "Offset" as a menu tab option in the GHG menu bar?

Thank you

**Comment by guilbep** [comment]
done in | * fb81d72 (origin/dev, dev) fix(ghg): better code for cooking and lighting
