### ISSUE TITLE
[FIX](GHG General): fix 'update locations database'

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

@guilbep The Locations database is up to date. Please see the following:

https://docs.google.com/spreadsheets/d/1VVxsSS-KCUmP-giKZwlARNmw5RSSZHUQ/edit#gid=1437641817

**Comment by guilbep** [comment]
done
