### ISSUE TITLE
[FIX](GHG Pumping): fix 'put in units in the diesel generators '

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#439]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

@guilbep In the test platform, when one clicks on diesel generators there is "Diesel estimated" as the bottom line. It should read "Diesel estimated (kwh/yr)"

![image](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/111510926/be200dd6-6b2e-423d-9838-a3d0ed2ec40b)

**Comment by guilbep** [comment]
![estimated](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/161889/0b633a91-fc6d-4246-b3b4-7fc5db9c5452)

It's enough as it is. If we have more feedback we'll had back kWh per type of month/year again.
![estimated](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/161889/082b5f40-b23e-4f9e-bccd-5a63b02e40a6)
