### ISSUE TITLE
[BUG] <GHG Cooking>

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#440]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

@guilbep Hi Pierre, when adding an improved cooking device (when the quantity of fuel) is not known, the endline does not show the improved cooking appliance icon. This is on the non-test platform. Could you kindly remember to add this feature?

Thank you,

Cara

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by guilbep** [comment]
![endline](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/161889/631eb6b7-91db-46ff-96af-21856f68f41d)
@ctobin111 it's working on my side. Cf #duplicate here: https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/issues/449
