### ISSUE TITLE
[GHG Solid Waste] <Add information icons>

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#442]
@guilbep Can you please add the following information warning hovers next to the following solid waste management options:

1) Warning for managed disposal option: "Managed disposal emissions relate to anaerobic conditions that release methane. Methane has a much higher global warming potential than carbon dioxide (28 times more powerful as GHG), so the CO2e emissions considered are relatively high compared to options like burning or open pits disposal that release predominantly biogenic CO2."
 
2) Warning for unmanaged option: "This option does not account for non-climate change impacts such as air pollution, leaching and public health concerns."
 
3) Warning for burning: "This option does not account for non-climate change impacts such as issues related to air pollution and public health."

**Comment by ctobin111** [comment]
@guilbep Another text revision for 2. Warning

Warning for unmanaged option: "This option appears to have lower emissions than the managed option, however, it does not account for non-climate change impacts such as air pollution, leaching and public health concerns."

**Comment by guilbep** [comment]
done in * c6a6538 (HEAD -> dev, origin/dev) feat(ghg): update text for #442
