### ISSUE TITLE
[GHG Lighting] <Including default values for Lighting devices>

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#443]
@guilbep I am trying the Lighting and I think the user should have some default values. Could we either include them as a table such as we did in the SWM module or include them like we did in cooking? Whatever is easiest.

For your memory the default values can be found here:

[][]((https://drive.google.com/drive/u/4/folders/14w8NOSc-OBRF9A-BQfoMabVPARwso6fg))

Thank you,

Cara

**Comment by guilbep** [comment]
Hi Cara,

I’ve deployed a ‘working’ version to the test platform.


- The co2 computation does not work yet for the hybrid electric
- The hybrid electric mix is not limited to 100%; not sure how to do that yet.


See you tomorrow!


On Oct 25, 2023, at 12:08, ctobin111 ***@***.***> wrote:



Assigned #443<https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/issues/443> to @guilbep<https://github.com/guilbep>.
