### ISSUE TITLE
[BUG] <Reference data - materials transport - description text cut> #445

### ISSUE THREAD

**Issue by andreullal** [EPFL-ENAC/unhcr-geneva-tech-hub-app#445]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Only part of the text explaining to the transport data (at top of page) appears. Previously, the full text description was there.

<img width="1624" alt="Screenshot 2023-09-28 at 15 41 20" src="https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/108796343/8c4309d8-050a-469c-bc24-6766cab83840">

### Expected Behavior

Full description explaining the calculation method, as per previous versions. 

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by guilbep** [comment]
I'll keep this open @andreullal, since it's not working on safari (different behavior with scroll-bar, they're hidden by default)..

Thanks Apple btw :) https://stackoverflow.com/a/10100209 <-- this needs to be implemented to cirvumvent apple weird behavior.

**Comment by guilbep** [comment]
done in 81a3ea5 fix(shelter): force the scroll bar for material transport Fri, 27 Oct 2023 15:37:58 +0200 (8 weeks ago)
