### ISSUE TITLE
[BUG] <GHG Lighting calculation>

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#447]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

@guilbep In the summary table, the Annual fuel / Energy consumption is per household. So the energy or fuel per household has to be multiplied by the percentage of the households and the total number of households.

![image](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/111510926/419c52cc-c9f1-4a43-b729-0fd3293d8dec)

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by guilbep** [comment]
![ok](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/161889/df48829f-db51-40fa-9836-9a7486392da1)
The above example is for one household. I've tested it. and everything seems okay.

It's in production now, you should be able to test it
