### ISSUE TITLE
[BUG] <GHG Cooking - Improved cookstoves>

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#449]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

@guilbep Improved cookstove appliance logo is not appearing in test or recently deployed versions. See Kakuma recent examples.

![image](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/111510926/9e52f426-312e-4fa9-a551-701688452fbc)

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by guilbep** [comment]
@ctobin111 what's the improved cookstove appliance logo "?

**Comment by guilbep** [comment]
@ctobin111 Okay,, I see what happened. We only have the icon for some type of cookstoves and conditions.
![improved_cookstove](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/161889/bfe91bc9-dbde-4585-a08c-3b9b2b7ae450)

We need to have an appliance first. And if we don't have one, we show nothing.

rules regarding appliance :
        //   - only some cookstove tech have access
        //   - show if Fuel quantity not known (disabledFuelUsage is true)
        //   - show only if
        //     - cooking is electric diesel generator AND
        //     -  disabledFuelUsage is True AND
        //     -  disableDieselLiters is False (no diesel generator charact )

**Comment by guilbep** [comment]
If the current conditions does not work for our case, we should review them together to make sure it's all good. I'm closing the issue for now. Re-Open it if you think it still needs to be fixed

**Comment by ctobin111** [comment]
@guilbep It is not working from my side. Can we do a quick Zoom so that I can show you?

**Comment by ctobin111** [comment]
@guilbep the user should be able to add an improved alliance as an endline. This is an improvement to the efficiency of the system.

**Comment by ctobin111** [comment]
@guilbep Improved appliances are the pressure cookers and the heat retaining baskets

**Comment by guilbep** [comment]
@ctobin111 there is a problem with how it's been implemented then. Because it's not the case presently. Only the above conditions needs to be met.
Could you send me an invite for tomorrow so we can talk about it ?

**Comment by guilbep** [comment]
done in  fb81d72 (origin/dev, dev) fix(ghg): better code for cooking and lighting
