### ISSUE TITLE
[FIX](GHG): fix 'Lighting: Decimal points for kw/h hover'

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#451]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

@guilbep Please remind me if we can put the numbers after the decimal points to 2. This is in the summary table for Lighting Annual fuel / Energy consumption

![image](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/111510926/e0a3bbbf-304f-4e61-bbd8-d4b406375aa6)

Thank you, Cara

**Comment by guilbep** [comment]
I can do that!

**Comment by guilbep** [comment]
![fixed_lighting](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/161889/d20bc11e-d0c7-4af4-a6cd-f3e9ec2541aa)
I think my previous comment is an error, it may have been an another issue, I commented on the wrong one. As you can see it has been fixed already.
