### ISSUE TITLE
[FEATURE][GHG]Landing Page e

### ISSUE THREAD

**Issue by guilbep** [EPFL-ENAC/unhcr-geneva-tech-hub-app#467]
<b>comment</b>: Reference data – UNHCR LOCATION: are the population numbers changing over time (for example, dynamically connected to a database)?

If not, put the year of reference and the link to the source. 
Also, why are there only some countries (for example, I couldn’t find Uganda or Rwanda, etc.)? and https://globalsolaratlas.info should have the hyperlink.

<br/><b>actions</b>: IT4R will add the new database with census year and the updated GIS database from UNHCR (After meeting with Edgar on the 31st of August).

Information for solar hours is presented for the countries hosting refugee camps according to the list provided to EPFL. EssentialTech will update this information based on the updated GIS database. add year in population column displayed in reference + add year in the information page.

And remove year, when the user modify the population number (show original population + year in grey text); we should show default value (peak hours, etc) not possible to be modified by the user IT4R will add a hyperlink for https: //globalsolaratlas.info and EssentialTech will provide a text to explain how to extract the solar hours for new locations. IT4R will provide information on how to update new dataset each year<br/><hr/>

<b>estimated_hours</b>: 4<br/><b>unhcr_comments</b>: null<br/>

<b>ctobin111</b>: "
- [x] Provide updated GIS database from UNHCR after receiving response from GIS group about missing coordinates (with year of census, coordinates, population and solar hours)
- [x]  Provide a text to explain how to extract the solar hours for new locations"<br/>

<b>me</b>: "
- [x] Update new database into the tool. 
- [x] add year in population column displayed in reference + add year in the information page. 
- [x] (edit: removed due to duplicate in. #468) And remove year, when the user modify the population number (show original population + year in grey text); we should show default value (peak hours, etc) not possible to be modified by the user 
- [x] Add a hyperlink for https: //globalsolaratlas.info
- [x] Provide information on how to update new dataset each year"

**Comment by guilbep** [comment]
"Provide information on how to update new dataset each year" :  The user need to modify /frontend/src/assets/references/unhcr_location.json

1) update couchdb-setup/rawdata/unhcr_location.csv with the latest data (based on the excel here)https://docs.google.com/spreadsheets/d/1VVxsSS-KCUmP-giKZwlARNmw5RSSZHUQ/edit#gid=1437641817 ==> [Locations_EPFL_092023_filtered_solar_hours.xlsx](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/files/13283077/Locations_EPFL_092023_filtered_solar_hours.xlsx))

2) Then you can use the Makefile in couchdb-setup/rawdata to create the /frontend/src/assets/references/unhcr_location.json

Then it should be okay

**Comment by guilbep** [comment]
@ctobin111 do you have something to do on this issue ?

**Comment by ctobin111** [comment]
@guilbep the User's Manual explains how to extract the solar hours for new locations. If a new location is added by the user, can we refer them to the User's Manual?

**Comment by guilbep** [comment]
done in [dev 8571276] fix(ghg): correct solar info tooltip #467
