### ISSUE TITLE
[FEATURE][GHG]Creating a new assessment a: original/user created

### ISSUE THREAD

**Issue by guilbep** [EPFL-ENAC/unhcr-geneva-tech-hub-app#472]
<b>comment</b>: Existing / new sites: an icon/symbol could be added for

Add an icon with a tooltip with the following text in the title for the assessment
- i) original site
- ii) user created site

- So far, it is impossible to distinguish between pre-defined sites and sites added by users (see the example below: Mbera 1 was created by a field colleague).

<br/><b>actions</b>: UNHCR should have a discussion with IT4R. it should be seen at the list level and also on the assessment title: let's use https://pictogrammers.com/library/mdi/icon/license/ with blue ribbon kind of color: and the text/tooltip should say: original site from unhcr data<br/><hr/><b>estimated_hours</b>: 1<br/><b>unhcr_comments</b>: null<br/><b>ctobin111</b>: null<br/><b>me</b>: "it should be seen at the list level and also on the assessment title: let's use https://pictogrammers.com/library/mdi/icon/license/ with blue ribbon kind of color: and the text/tooltip should say: original site from unhcr data"

**Comment by ctobin111** [comment]
@guilbep should we discuss this? I remember that a non original site will not have the pcode in the URL. Anything else?

**Comment by guilbep** [comment]
done in [dev 15b5bbe] feat(ghg): add a faster way of recognising original site from UNHCR #472
