### ISSUE TITLE
[FEATURE][GHG]Creating a new assessment d

### ISSUE THREAD

**Issue by guilbep** [EPFL-ENAC/unhcr-geneva-tech-hub-app#475]
<b>comment</b>: Coordinates: Coordinates did not seem to be correct in one identified case. Is this issue related to the uncommon naming? <br/><b>actions</b>: Discussed with UNHCR GIS group week on 31 August 2023. UNHCR GIS group sent a new .csv file with improved coordinates. As of 29.09.2023, 6 questionable points are waiting explanations from the GIS team.<br/><hr/><b>estimated_hours</b>: 0<br/><b>unhcr_comments</b>: This line is not clear. Is there a need for action from IT4R?<br/><b>ctobin111</b>: "EssentialTech is waiting on UNHCR GIS after updates noted in line 7 of this Excel"<br/><b>me</b>: "Pierre will upload the updated database"

**Comment by ctobin111** [comment]
@guilbep new UNHCR GIS table was provided and uploaded.
