### ISSUE TITLE
[FEATURE][GHG]Module: Cooking a

### ISSUE THREAD

**Issue by guilbep** [EPFL-ENAC/unhcr-geneva-tech-hub-app#485]
<b>comment</b>: Wood vs. pellets/briquettes: Using the same cooking technology, pellets or briquettes produce less GHG emissions than wood (although a much larger amount is combusted) – please check whether this is correct.<br/><b>actions</b>: Cara/Natalia will check the emission factors, net calorific values and default values of fuel consumption and send to IT4R to update.<br/><hr/><b>estimated_hours</b>: 0.5<br/><b>unhcr_comments</b>: null<br/><b>ctobin111</b>: "check the emission factors, net calorific values and default values of fuel consumption"<br/><b>me</b>: "Update databases with received info"

**Comment by nmontoya03** [comment]
Net calorific value of pellets and briquettes is lower than for wood, which explains a larger amount required for pellets/briquettes. However, emission factor for wood is higher than the one for briquettes/pellets (1.89 vs 1.27 kgCO2e/kg fuel). @guilbep @ctobin111 closing the issue after checking.
