### ISSUE TITLE
[FEATURE] <Update HH icon and title>

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#49]
- [x] Toilet symbol for household waste should be updated. [ICON TO BE ADDED]
- [x] Rename the module “domestic solid waste”

**Comment by guilbep** [comment]
hello @ctobin111 here are some screenshots of the renaming of HH Waste
<img width="1342" alt="Domestic solid waste" src="https://user-images.githubusercontent.com/161889/186853956-d4e255bb-666c-4d6e-ac22-04e15607d3ee.png">

<img width="455" alt="domestic_solid_waste_2" src="https://user-images.githubusercontent.com/161889/186853948-a9010823-75b1-40e8-8b55-94583ddc9920.png">

**Comment by ctobin111** [comment]
Hi Pierre, the best symbol would be of a rubbish bin with a recycling symbol or something like this:
![rubbish-bins-waste-paper-baskets-recycling-bin-recycling-symbol-computer-icons-png-favpng-kz1D3896i3P8pPjLzD8dpn1cH](https://user-images.githubusercontent.com/111510926/186888640-dea61d62-9c9e-4619-9326-1d06b7df83f9.jpg)

Here is the reference for this icon: https://www.bing.com/images/search?view=detailV2&ccid=xMByZKkz&id=CBF4632BEA1315F71F24CB32475283B66939F7EA&thid=OIP.xMByZKkzTSf2WIoeOco7kQHaHa&mediaurl=https%3a%2f%2fimg.favpng.com%2f19%2f15%2f13%2frubbish-bins-waste-paper-baskets-recycling-bin-recycling-symbol-computer-icons-png-favpng-kz1D3896i3P8pPjLzD8dpn1cH.jpg&cdnurl=https%3a%2f%2fth.bing.com%2fth%2fid%2fR.c4c07264a9334d27f6588a1e39ca3b91%3frik%3d6vc5abaDUkcyyw%26pid%3dImgRaw%26r%3d0&exph=820&expw=820&q=symbol+rubbish+bin+recycle&simid=608014855268748202&FORM=IRPRST&ck=A5A43154773014451CFB2685A64ACE79&selectedIndex=0&idpp=overlayview&ajaxhist=0&ajaxserp=0

**Comment by guilbep** [comment]
@ctobin111 
<img width="539" alt="domestic_solid_waster" src="https://user-images.githubusercontent.com/161889/190338913-f764d876-bc59-4957-b7b0-81601987ccb9.png">
 It will look like this!

**Comment by guilbep** [comment]
All done in #95 https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/pull/95

**Comment by ctobin111** [comment]
Perfect

On 15 Sep 2022, at 09:17, Guilbert Pierre ***@***.***> wrote:

﻿

Closed #49<https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/issues/49> as completed.
