### ISSUE TITLE
[FEATURE][GHG]Module: Cooking g

### ISSUE THREAD

**Issue by guilbep** [EPFL-ENAC/unhcr-geneva-tech-hub-app#491]
<b>comment</b>: Ethanol: We agreed that the tool should consider S3 emissions from feedstock production – please adjust accordingly.<br/><b>actions</b>: Cara/Natalia will update the emission factor accordingly.<br/><hr/><b>estimated_hours</b>: 0.5<br/><b>unhcr_comments</b>: null<br/><b>ctobin111</b>: "update the emission factor accordingly"<br/><b>me</b>: null

**Comment by guilbep** [comment]
@ctobin111 @nmontoya03  is the ethanol emission factor is up to date ?

**Comment by nmontoya03** [comment]
Hi @guilbep @ctobin111 ,

Please find here below the updated emission factors for ethanol (cooking module) and vegetable oil (lighting module):

*Ethanol: 0,945452 kg CO2e/L
Source:
https://cfpub.epa.gov/si/si_public_record_report.cfm?Lab=NRMRL&dirEntryId=339679

*Vegetable oil: 1,878252 kg CO2e/L. 
Sources: 
https://www.epa.gov/system/files/documents/2023-03/ghg_emission_factors_hub.pdf
https://www.sciencedirect.com/science/article/pii/S0048969722016321

Could you kindly update these values in the database? If you think it is simpler for you, I can also update myself the values in the file. Let me know. Thank you!

**Comment by guilbep** [comment]
done in [dev ef36f07] feat(ghg): update ghg_reference and unhcr_location with latest values #491
