### ISSUE TITLE
[FEATURE][GHG]Module: Cooking h

### ISSUE THREAD

**Issue by guilbep** [EPFL-ENAC/unhcr-geneva-tech-hub-app#492]
<b>comment</b>: Biogas: please verify / correct the default value for biogas consumption. Alternative values have been provided in the past by UNHCR. <br/><b>actions</b>: Cara/Natalia will check the default value accordingly.<br/><hr/><b>estimated_hours</b>: 0<br/><b>unhcr_comments</b>: No need for IT4R actions?<br/><b>ctobin111</b>: "check the default value accordingly"<br/><b>me</b>: "Default factor database will be update accordingly and IT4R's time to do this is included in line 32"

**Comment by guilbep** [comment]
@ctobin111 @nmontoya03 What's the status of this issue ?

**Comment by ctobin111** [comment]
@guilbep Biogas default value provided by Manuel:

Per person 0.400 m3/p/d

(https://energypedia.info/images/2/2c/Biogas_gate_volume_2.pdf)
