### ISSUE TITLE
[FEATURE][GHG]Module: Cooking i

### ISSUE THREAD

**Issue by guilbep** [EPFL-ENAC/unhcr-geneva-tech-hub-app#493]
<b>comment</b>: Piped natural gas: please verify / correct the default value for consumption.<br/><b>actions</b>: Cara/Natalia will check the default values for fuel consumption.<br/><hr/><b>estimated_hours</b>: 0<br/><b>unhcr_comments</b>: null<br/><b>ctobin111</b>: "check the default values for fuel consumption"<br/><b>me</b>: "Default factor database will be update accordingly and IT4R's time to do this is included in line 32"

**Comment by guilbep** [comment]
@ctobin111 @nmontoya03 What's the status of this issue ?

**Comment by ctobin111** [comment]
@guilbep Natural Gas default value provided by Manuel:

Per person 0.400 m3/p/d

(https://energypedia.info/images/2/2c/Biogas_gate_volume_2.pdf)

**Comment by nmontoya03** [comment]
@guilbep Natural gas default value calculated based on biogas consumption and the fuels net calorific values:

Per person 0.420 m3/p/d
