### ISSUE TITLE
[FEATURE][GHG]Module: Cooking n

### ISSUE THREAD

**Issue by guilbep** [EPFL-ENAC/unhcr-geneva-tech-hub-app#498]
<b>comment</b>: Calculation of change in emissions: Would it not be more reasonable to calculate the percentage of emission reductions in reference to its percentage of households? Example: 50% using LPG instead of wood (0.23 instead of 2.53 t CO2e/yr = -90%). The total result will then compare the total emission reductions (2.77 instead of 5.07 = -45%)<br/><b>actions</b>: Guidance manual shows the calculation. This can be updated with UNHCR consensus<br/><hr/><b>estimated_hours</b>: 0<br/><b>unhcr_comments</b>: null<br/><b>ctobin111</b>: "Modify the change in emissions equation so that the ratio is also included in the denominator. Provide text to IT4R for hover/info icon Update the User's Manual accordingly"<br/><b>me</b>: "Update the equation. Add hover/info icon indicating that for the change in emissions we compare line by line with the baseline emissions."

**Comment by ctobin111** [comment]
@guilbep this has been resolved.
