### ISSUE TITLE
[FEATURE][GHG]Module: Cooking t

### ISSUE THREAD

**Issue by guilbep** [EPFL-ENAC/unhcr-geneva-tech-hub-app#504]
<b>comment</b>: Pictures of cooking solutions: once the module is finalized (and before the field testing), the selection of pictures should be reviewed and approved.<br/><b>actions</b>: Photos for traditional cookstoves and gasifiers will be updated by IT4R.<br/><hr/><b>estimated_hours</b>: 0.5<br/><b>unhcr_comments</b>: null<br/><b>ctobin111</b>: null<br/><b>me</b>: "update pictures"

**Comment by ctobin111** [comment]
@nmontoya03 We have the one picture of a traditional cookstove attached here. I took the one from the gasifier in the tutorial presentation. Anything else we should add or do I need to get this information from Manuel?

![image](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/111510926/0bc08bfe-d5fd-4fe8-831b-aaacde5fd2f5)

![image](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/111510926/b96b4fe4-8a84-49a1-bf27-c6db24d2fd9e)

**Comment by nmontoya03** [comment]
@ctobin111 Manuel also provided an updated photo for the gas powered cookstoves (attached here). For the other cookstoves photos we did not get comments from his side. 
![Gas powered cookstove](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/131168517/62c8ee3a-bc05-4c37-8101-588f82904088)

**Comment by ctobin111** [comment]
@nmontoya03 Thank you. I will ask Manuel. @guilbep can you kindly upload these photos and then close this comment. We are getting there. Thank you!

**Comment by guilbep** [comment]
done in [dev 2570027] feat(ghg): change images for lpg,traditional-wood,gasifier #504
