### ISSUE TITLE
[FEATURE][GHG]Module: Lighting a: default value #507

### ISSUE THREAD

**Issue by guilbep** [EPFL-ENAC/unhcr-geneva-tech-hub-app#507]
<b>comment</b>: Wood – can we have an estimation of how much firewood is utilized for lighting for HH? I fear the kg/day/hh is difficult information to insert.<br/><b>actions</b>: EssentialTech will provide default values for fuel consumption an IT4R will include them in the tool.<br/><hr/><b>estimated_hours</b>: 8<br/><b>unhcr_comments</b>: null<br/><b>ctobin111</b>: "EssentialTech will provide default values for fuel consumption"<br/><b>me</b>: "IT4R will include them in the tool (included in new lighting structure work)"

**Comment by ctobin111** [comment]
@nmontoya03 Jinjin provided this information: report for firewood consumption rate in Kenya (rural area): 2.14kg/capital/day. But it's hard to distinguish the intentions and they work both for cooking and lighting. Btw, the emission factor of wood in GHG tool is 1.89kg CO2e/kg in case you need it. ☺https://www.sciencedirect.com/science/article/pii/S0961953400000726 

I think we agreed on using a fraction of this for lighting. Do you have any recollections? Also, does Jinjin's EF match yours for wood?

**Comment by guilbep** [comment]
TODO: add a default biomass of 2.14kg/cap/day for wood for lighting module.
Add a link to the science direct paper 
![Image](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/161889/10f25916-9d33-448c-9837-3c1f5781fbac)

**Comment by nmontoya03** [comment]
Hi @guilbep @ctobin111 Regarding this issue, I remember Pierre was saving the default values of consumption for cooking in terms of fuel/capita/day to be able to calculate adapted default values depending on the HH size. If we keep this for Lighting, the default value for wood consumption/capita/day can be calculated as: 

Total wood consumption/capita/day - Wood consumption for cooking/capita/day. 

In the case of assuming a tree stone fire cookstove, the default value is 1.7 kg wood/cap/day. Then, the wood consumed for Lighting would be: 2.14kg/capita/day -1.7 kg/cap/day =**0.44 kg/capita/day**

Please let me know if you agree with this value or if you have any comment.

Thank you!

**Comment by guilbep** [comment]
![Image](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/161889/c3b0b097-f110-478c-bd95-cc01d61dcf64)

done in [dev a7eb316] feat(ghg): add default value for lighting/cooking wood #507, #508

**Comment by nmontoya03** [comment]
Thank you Pierre, as you already included in the tool the default values of consumption for the Lighting fuels are:

Wood: 0.44 kg/capita/day
Candles: 0.0053 kg/capita/day
Kerosene: 0.03276 L/cap/day
Vegetable oil: 0.14 L/cap/day

**Comment by nmontoya03** [comment]
Hi @guilbep, we know have a defualt value of gasoline of 0.0351 L/capita/day. Could you please kindly add it to Lighting Module? Thank you!

**Comment by guilbep** [comment]
done in https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/commit/f373ca81b5c2dc8dfc82366b9b0402c970fa4e94 4 weeks ago

fix(ghg): add latest correction before demo prod tomorrow

- [x] I’ve just added it; I had forgotten about it;
defualt value for gasoline of 0.0351 L/capita/day
- [x] IPCC link missing on entry page
- [x] It should be fixed now; Existing UNHCR sites
in Colombia: When creating the new assessment with an
existing UNHCR site, the icon for the UNCHR site correcty
appears in the assessment general page.
However, in the home page with the assessment list,
the icon is still the one for user created site (please see the screenshots).
- [x] remove Description it from the Anaerobic digestion and Composting emissions factors?
