### ISSUE TITLE
[FEATURE][GHG]Module: Lighting b, default value for candle

### ISSUE THREAD

**Issue by guilbep** [EPFL-ENAC/unhcr-geneva-tech-hub-app#508]
<b>comment</b>: Candle – can we have an estimation? Also, the user may know the number of candles per day more than the kg/day/HH<br/><b>actions</b>: EssentialTech will provide default values for fuel consumption an IT4R will include them in the tool.<br/><hr/><b>estimated_hours</b>: null<br/><b>unhcr_comments</b>: null<br/><b>ctobin111</b>: "EssentialTech will provide default values for fuel consumption"<br/><b>me</b>: "IT4R will include them in the tool (included in new lighting structure work)"

**Comment by ctobin111** [comment]
@guilbep For 3.9 daily lighting hours, the consumption rate is 0.026kg/d. So the defalut value should be 0.026 kg/d and default daily lighting hours should be 3.9 hours.

Can you kindly put this in an information hover next to or below the default value 0.026 kg/d: Based on a mean weight loss of wax 6.75 g/h). Reference: https://iopscience.iop.org/article/10.1088/1757-899X/1252/1/012011/pdf

**Comment by guilbep** [comment]
done in [dev c19ce86] feat(ghg): add default value for lighting/cooking wood #507, #508
