### ISSUE TITLE
[FEATURE] <Change Facilities screen column title>

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#51]
"Renewables (kW)" should be new column title. See screenshot.

![image](https://user-images.githubusercontent.com/111510926/185893101-f6108a16-0fa5-4e03-b5b1-8854ec77b8b7.png)

**Comment by guilbep** [comment]
Thank you @ctobin111  may I ask why we go from (kwh) to (kw) for Renewables ?

**Comment by ctobin111** [comment]
Hi Pierre, the reason for this is that solar panels are generally provided in kW rather than kWh. The calculations will remain the same.
