### ISSUE TITLE
[FEATURE][GHG]Module: Lighting h

### ISSUE THREAD

**Issue by guilbep** [EPFL-ENAC/unhcr-geneva-tech-hub-app#514]
<b>comment</b>: Torch/phone with battery (rechargeable or not): This option might be confusing for users<br/><b>actions</b>: Phones have been removed from the new structure that will be implemented by IT4R.<br/><hr/><b>estimated_hours</b>: 0.5<br/><b>unhcr_comments</b>: null<br/><b>ctobin111</b>: null<br/><b>me</b>: "remove torch"

**Comment by ctobin111** [comment]
@guilbep we removed phones and have been more explicit about which is rechargeable.
