### ISSUE TITLE
[FEATURE] Add estimation clause as hover

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#52]
UNHCR has asked us to repeat this hover assumption over the i in the Facilities front page and on the results page:

"The GHG tool only considers Scope 1 and 2 emissions at this stage. The calculations are estimations. For renewables in particular, it is assumed that the addition of solar panels will add zero emissions."

I can also provide this to the Tool Summary if you provide me the access.

**Comment by guilbep** [comment]
Hello @ctobin111 What is the 'Tool Summary' ?

Here what it looks like by the way:
<img width="1126" alt="facililities_information" src="https://user-images.githubusercontent.com/161889/186847030-24df8ee0-deda-4490-b3f0-6d8183d8ec20.png">
<img width="1499" alt="results_information" src="https://user-images.githubusercontent.com/161889/186847032-e8e55c54-ffb9-44cf-97d3-640a30237fae.png">

**Comment by guilbep** [comment]
Hey @ctobin111 I'm guessing you wanted me to add this information to the description of the ghg app in the (app list page, and about page). Here are some screenshots. Please tell me if you want any modification to it.
<img width="1213" alt="scroll_description" src="https://user-images.githubusercontent.com/161889/186848146-3a0ab733-9c69-4864-9ab9-ce41244c7cfb.png">
<img width="1363" alt="description" src="https://user-images.githubusercontent.com/161889/186848152-63cc1e4a-efa0-4033-9bc0-af3db9f0d15d.png">

**Comment by guilbep** [comment]
Waiting on  Cara's approval to close this issue
