### ISSUE TITLE
[FEATURE][GHG]Module: WASH trucking e

### ISSUE THREAD

**Issue by guilbep** [EPFL-ENAC/unhcr-geneva-tech-hub-app#520]
<b>comment</b>: Density of fluids: water, wastewater, and faecal sludge have different densities. This likely affects transportation. Faecal sludge, for instance, can have a much higher density than drinking water. To estimate emissions, are inserted m3 converted into kg (in the backend)? If so, could we include an input mask to define the density of wastewater and faecal sludge (with default values provided)? Users could then overwrite the default values in case more accurate information is available.<br/><b>actions</b>: EssentialTech will do a review on fluid density and copy UNHCR WASH expert (Anne) to get her feedback about the assumptions. The way it works now is valid for any kind of freight material.<br/><hr/><b>estimated_hours</b>: 4<br/><b>unhcr_comments</b>: null<br/><b>ctobin111</b>: null<br/><b>me</b>: "add a new density field ?"

**Comment by ctobin111** [comment]
@guilbep UNHCR wanted to focus only on water supply and not trucking of faecal sludge, so this issue is closed.
