### ISSUE TITLE
[FEATURE][GHG]Module: WASH trucking g.i.

### ISSUE THREAD

**Issue by guilbep** [EPFL-ENAC/unhcr-geneva-tech-hub-app#523]
<b>comment</b>: the use of the term “litres” is confusing. While you are aiming at litres of fuel consumed, users may think it refers to water / wastewater / faecal sludge. Please adapt text<br/><b>actions</b>: IT4R will adapt the text to litres of fuel.<br/><hr/><b>estimated_hours</b>: 2<br/><b>unhcr_comments</b>: null<br/><b>ctobin111</b>: null<br/><b>me</b>: null

**Comment by ctobin111** [comment]
@guilbep this has been updated.
