### ISSUE TITLE
[FEATURE][GHG]Module: WASH trucking i.iv. #526

### ISSUE THREAD

**Issue by guilbep** [EPFL-ENAC/unhcr-geneva-tech-hub-app#526]
<b>comment</b>: Overall, the fuel consumption of a number of trucks might not be known. Rather the reading from the mileage / kilometrage. Could this be another calculation method (not identical to the existing “transport distance” approach)?<br/><b>actions</b>: The total distance travelled per month can be asked as input to calculate the emissions if the UNHCR WASH group considers it a high priority issue. The fluid volume will still be required for the warning message.<br/><hr/><b>estimated_hours</b>: 4<br/><b>unhcr_comments</b>: null<br/><b>ctobin111</b>: null<br/><b>me</b>: "Change form and inputs"

**Comment by guilbep** [comment]
Waiting for more discussion with UNHCR

**Comment by guilbep** [comment]
@ctobin111 @nmontoya03  I'm pretty sure we decided on not doing this. But I could not find any trace of our discussion on it. I'm closing for now. Please re-open with more info if it should be done

**Comment by ctobin111** [comment]
@guilbep good to close because an outdated duplicate of issue #579
