### ISSUE TITLE
[FEATURE][GHG]Module: WASH trucking i

### ISSUE THREAD

**Issue by guilbep** [EPFL-ENAC/unhcr-geneva-tech-hub-app#528]
<b>comment</b>: “PETROL / gaz”: please correct writing. Is the term “gaz” required?<br/><b>actions</b>: IT4R will correct the capitalization of PETROL and the spelling of GAS (North American term for petrol): PETROL / GAS.<br/><hr/><b>estimated_hours</b>: 2<br/><b>unhcr_comments</b>: null<br/><b>ctobin111</b>: null<br/><b>me</b>: null

**Comment by ctobin111** [comment]
@guilbep This seems to already have been done in the trucking part of the Water Supply module.

![image](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/111510926/c3106c61-b9b7-40e8-a770-23784a24bafb)

Can you kindly see if there are any other references to petrol in your code? If there are no other, then this issue should be closed.

**Comment by guilbep** [comment]
done
