### ISSUE TITLE
[FEATURE] Add absolute difference in emissions

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#53]
The final comment by UNHCR was to also put in the simple differences (baseline tons CO2e/yr - endline tons CO2e/yr) on the Facilities calculation page at the bottom and on the Results page. For them the Results are two things the relative percentage that we have but also the simple difference.

![image](https://user-images.githubusercontent.com/111510926/185895545-e207f5f1-7d51-493d-b5af-1f9831f5d789.png)

**Comment by guilbep** [comment]
[](
<img width="585" alt="expected_behavior_from_ghg" src="https://user-images.githubusercontent.com/161889/185930066-d9f6ff7b-c4d7-42d1-845c-5e9cedb4ac5f.png">
u

**Comment by guilbep** [comment]
Results + Facilities : Putting in absolute difference in emissions, in addition to percentage change
