### ISSUE TITLE
[FEATURE][GHG]Module: WASH trucking m

### ISSUE THREAD

**Issue by guilbep** [EPFL-ENAC/unhcr-geneva-tech-hub-app#532]
<b>comment</b>: Alternatives for endline: The real alternative to water trucking is installing a water supply system. Analog to the planned module “water pumping”, would it be feasible to add the corresponding features in the WASH trucking module? Energy consumption/emissions could be based on the energy sources system created for the “facility” modules (diesel generator, PV, grid etc.).<br/><b>actions</b>: This option is being discussed with IT4R to decide how to merge these two modules.<br/><hr/><b>estimated_hours</b>: 8<br/><b>unhcr_comments</b>: null<br/><b>ctobin111</b>: "EssentialTech will explain how the volumes of water either trucked or pumped will be placed in the combined module. Each individual modules logic and equations remain the same."<br/><b>me</b>: null

**Comment by guilbep** [comment]
@ctobin111 do you confirm that it's done ?

**Comment by ctobin111** [comment]
@guilbep yes done, only minor updates like warnings and text.
