### ISSUE TITLE
[FEATURE][GHG]Module: WASH - Pumping e

### ISSUE THREAD

**Issue by guilbep** [EPFL-ENAC/unhcr-geneva-tech-hub-app#538]
<b>comment</b>: The pop-up information near the title of the module says that the pumping is either for water or faecal sludge. But then, in the new water pump, there is no way to choose faecal sludge. Better to remove it from the explanation. <br/><b>actions</b>: EssentialTech will review the module descriptions. It can be discussed with UNHCR WASH experts whether the faecal sludge pumping represents an important emission source.<br/><hr/><b>estimated_hours</b>: 0<br/><b>unhcr_comments</b>: null<br/><b>ctobin111</b>: null<br/><b>me</b>: null

**Comment by ctobin111** [comment]
@guilbep Faecal sludge and sludge pumping text should be removed. Here is the new text:

The Water Supply module calculates the emissions that are generated by either trucking water to and from a water source and a distribution point and/or by pumping from a borehole at the settlement. Either diesel or petrol trucks can be used in calculating emissions.

**Comment by guilbep** [comment]
done in [dev d986859] fix(ghg): replace information icon text: delete faecal sludge reference #538
