### ISSUE TITLE
[FEATURE][GHG]Module: Material - Domestic Solid Waste a

### ISSUE THREAD

**Issue by guilbep** [EPFL-ENAC/unhcr-geneva-tech-hub-app#540]
<b>comment</b>: Generation rate: - needs to be inserted as g/cap/day, the examples are displayed in kg/cap/day. Would it make sense to use the same unit for both, to avoid misunderstandings?

- Ideally use SI units
- – kg in this example
- Please correct the unit, add …/cap/day
- Please rephrase: generation rate (instead of generation)
- Please rephrase example document: “from displacement contexts” (instead of “Refugee Camps”).
- Not all the mentioned examples are from refugee camps.

<br/><b>actions</b>: IT4R will adapt the units and rephrase the names<br/><hr/><b>estimated_hours</b>: 2<br/><b>unhcr_comments</b>: null<br/><b>ctobin111</b>: null<br/><b>me</b>: null

**Comment by ctobin111** [comment]
@guilbep this is same comment as #570

**Comment by guilbep** [comment]
done in [dev 046e333] fix(domesticSolidWaste): replace g per kg and change wording
@ctobin111 need to recheck computation because of g -> kg conversion
