### ISSUE TITLE
[FEATURE][GHG]Module: Material - Domestic Solid Waste b

### ISSUE THREAD

**Issue by guilbep** [EPFL-ENAC/unhcr-geneva-tech-hub-app#541]
<b>comment</b>: Waste generation examples: please add example from Bangladesh <br/><b>actions</b>: EssentialTech will include the Bangladesh example into the waste composition and generation document and send it to IT4R to update in the tool.<br/><hr/><b>estimated_hours</b>: 0.5<br/><b>unhcr_comments</b>: null<br/><b>ctobin111</b>: "EssentialTech will include the Bangladesh example into the waste composition and generation document "<br/><b>me</b>: null

**Comment by ctobin111** [comment]
@guilbep Please take the revisesd table from our Google Drive. Here is the link:

[](https://docs.google.com/presentation/d/1IBljrMCgmwd_lo8YPI_Zzc0_NmPtl5lN/edit?usp=drive_link&ouid=110398523820759855394&rtpof=true&sd=true)

**Comment by guilbep** [comment]
[RefugeeWasteExamples.pptx.pdf](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/files/13368760/RefugeeWasteExamples.pptx.pdf)

**Comment by guilbep** [comment]
done in [dev 0e8573c] chore: update file paths for RefugeeWasteExamples.pdf #541

**Comment by ctobin111** [comment]
@guilbep Better table, [https://docs.google.com/presentation/d/1IBljrMCgmwd_lo8YPI_Zzc0_NmPtl5lN/edit?usp=drive_link&ouid=110398523820759855394&rtpof=true&sd=true]

**Comment by guilbep** [comment]
DONE!
