### ISSUE TITLE
[FEATURE][GHG]Module: Material - Domestic Solid Waste e

### ISSUE THREAD

**Issue by guilbep** [EPFL-ENAC/unhcr-geneva-tech-hub-app#544]
<b>comment</b>: Order of non-biowaste: For the ease of data entry, please use the same order of non-biowaste as in the example document<br/><b>actions</b>: IT4R will change the order<br/><hr/><b>estimated_hours</b>: 0.33<br/><b>unhcr_comments</b>: null<br/><b>ctobin111</b>: null<br/><b>me</b>: null

**Comment by ctobin111** [comment]
@guilbep The current order is shown here:

![image](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/111510926/d28fdd25-c6a2-411c-a7c0-e7f73cef06bc)

The new order is still biowaste first, then:

nonbiowaste:

textiles
rubber / leather
paper / cardboard
plastics
nappies (diapers)
mixed / unknown composition

**Comment by guilbep** [comment]
done
