### ISSUE TITLE
[FEATURE][GHG]Module: Material - Domestic Solid Waste f

### ISSUE THREAD

**Issue by guilbep** [EPFL-ENAC/unhcr-geneva-tech-hub-app#545]
<b>comment</b>: Total percentage of generated waste can exceed 100%. Please add a warning mechanism.<br/><b>actions</b>: IT4R will add warning message (text or pop up)<br/><hr/><b>estimated_hours</b>: 1<br/><b>unhcr_comments</b>: null<br/><b>ctobin111</b>: null<br/><b>me</b>: null

**Comment by ctobin111** [comment]
@guilbep this comment is redundant with comment #569
