### ISSUE TITLE
[FEATURE][GHG]Module: Material - Domestic Solid Waste M

### ISSUE THREAD

**Issue by guilbep** [EPFL-ENAC/unhcr-geneva-tech-hub-app#550]
<b>comment</b>: change wording: anaerobic digestion (instead of anaerobically digested)<br/><b>actions</b>: IT4R will change the wording<br/><hr/><b>estimated_hours</b>: 0.1<br/><b>unhcr_comments</b>: null<br/><b>ctobin111</b>: null<br/><b>me</b>: null

**Comment by ctobin111** [comment]
@guilbep Please make this text update in the endline option for biowaste:

![image](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/111510926/efb9214d-b08c-49a8-88e6-1dd0da5ec196)

**Comment by guilbep** [comment]
done in [dev 9be205b] fix(domestic-solid-waste): change wording for anaerobic digestion #550
