### ISSUE TITLE
[FEATURE][GHG]Module: Material - Domestic Solid Waste j

### ISSUE THREAD

**Issue by guilbep** [EPFL-ENAC/unhcr-geneva-tech-hub-app#551]
<b>comment</b>: Is there the need to define when and how emissions are counted, and when they are considered circular? E.g. - burning biowaste leads to zero emissions – like burning wood from sustainable sources - burning plastic leads to emissions (= burning of fossil petrochemicals) - anaerobic digestion still leads to emissions – how come? - burning paper / card board leads to little emissions. Unmanaged paper / cardboard leads to increased emissions<br/><b>actions</b>: EssentialTech needs to clarify with UNHCR where these assumptions should be defined. Similar to sustainably managed biomass, neglected CO2 emissions from biowaste can be represented with an icon in the tool (only non-CO2 emissions accounted for). The other assumptions would be included in the user's manual like for the other modules.<br/><hr/><b>estimated_hours</b>: 0.5<br/><b>unhcr_comments</b>: null<br/><b>ctobin111</b>: "Verify protocol for low tech appliances. update manual with non-CO2 emissions clarification."<br/><b>me</b>: "Update user's manual"

**Comment by ctobin111** [comment]
@guilbep this has been resolved with the warnings that you provided.
