### ISSUE TITLE
[FEATURE][GHG]Module: Material - Domestic Solid Waste l

### ISSUE THREAD

**Issue by guilbep** [EPFL-ENAC/unhcr-geneva-tech-hub-app#553]
<b>comment</b>: Emissions of different management options: in terms of GHG emissions, managing solid waste seems to be way worse than open burning or not managing it. Would it make sense to add an information / paragraph on this dilemma?<br/><b>actions</b>: A message (provided by EssentialTech) will be added to the tool indicating associated environmental and health impacts of open burning and unmanaged disposal.<br/><hr/><b>estimated_hours</b>: 4<br/><b>unhcr_comments</b>: null<br/><b>ctobin111</b>: "EssentialTech to provide text"<br/><b>me</b>: "IT4R to add text"

**Comment by ctobin111** [comment]
@guilbep This is completed.
