### ISSUE TITLE
[FEATURE][GHG] - Water Supply module: add input for default efficiency of trucks #579

### ISSUE THREAD

**Issue by guilbep** [EPFL-ENAC/unhcr-geneva-tech-hub-app#579]
![display-fuel-efficiency](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/161889/030da79c-c27b-48fd-84e1-b0288eca7920)

Label: Truck fuel effiency (REF_WSH_G, REF_WSH_D) but transformed bia the REF_EFF_DIES and REF_EFF_PET)
Unit:  L / 100 km
Display default, but user can change it

cf #527 for reference 

@ctobin111 provide the formula (just to be sure)

**Comment by ctobin111** [comment]
@guilbep @nmontoya03 

Hi Pierre, the equation with the fuel efficiency is the following:

User inputs fuel efficiency in Litres / 100 km

Fuel efficiency [l/100 km] * XX km / yr = XY litres/yr

XY litres/yr * (Emission Factor – Diesel [kg CO2e/l] OR Emission Factor - Gasoline [kg CO2e/l]) = YY kg CO2e/yr

Note:

Emission Factor – Diesel (100% mineral diesel) = 2.72 kg CO2e/l
Emission Factor – Gasoline (100% mineral gasoline) = 2.34 kg CO2e/l

**Comment by guilbep** [comment]
![Image](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/161889/264c0548-db2c-46b5-9cd6-e2b5ad2e6fce)

Hi @ctobin111 It seems that my implementation is not working properly. I may have done something wrong with the formula.

Let's check real quick at the begining of january

**Comment by nmontoya03** [comment]
![image](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/131168517/3002a93c-a464-4bdf-81c7-7584887beb5e)

**Comment by guilbep** [comment]
done in 45dbbc8 (HEAD -> dev) Merge branch 'feat/579-water-supply-truck-efficiency' into dev
