### ISSUE TITLE
[FEATURE][GHG]: aggregate emission factor by module

### ISSUE THREAD

**Issue by guilbep** [EPFL-ENAC/unhcr-geneva-tech-hub-app#580]
Instead of having a table with all the emission factor, change the display to only display emission factors used per module
Like the Result PAge

cf issue: https://www.color-hex.com/color-palette/1014117 for the colors

- all emission factors from the different modules are listed alphabetically – would it make sense to bundled them per module, or have another sort of structuring?
actions: To discuss with UNHCR the best way to present the emissions in the references database (search bar, filter per module)

Estimated_hours: 4
@ctobin111 add the excel listing the corresponding ref

**Comment by ctobin111** [comment]
@guilbep @nmontoya03 Here is the bundled emissions factor database by module. [https://docs.google.com/spreadsheets/d/1WvETvzsdFb1NuCPXt8xmfn1nQT_xYkbs/edit?usp=drive_link&ouid=110398523820759855394&rtpof=true&sd=true](url)

If there are any changes to the values by Natalia, should we do them in this sheet? What is simplest for you Pierre?

**Comment by guilbep** [comment]
@ctobin111 well. It's very different that what the other document was. Let me think it through. I'll come back to you

**Comment by guilbep** [comment]
@ctobin111 @nmontoya03 What I'm going to do:

I'm going to use this google doc/spreadsheet as the new 'REFERENCE', I'm not sure the way it's currently done is very efficient. It may creates confusion and human error.

@nmontoya03 for instance the new value in this issue: [#491](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/issues/491). should be reflected in this new document.

i'm going to edit the document to have the module showing properly.

What's the repeated IN RED ?


I'm available today to discuss a bit this excel file

**Comment by guilbep** [comment]
- I keep the icons
- I rewrite the csv with @nmontoya03 latest updates
- Keep the columns names with the simplified new description

**Comment by guilbep** [comment]
@ctobin111 @nmontoya03 I updated the csv file on the google drive: https://docs.google.com/spreadsheets/d/1WvETvzsdFb1NuCPXt8xmfn1nQT_xYkbs/edit#gid=146266238

Tell me if everything is okay

**Comment by guilbep** [comment]
@ctobin111 thanks. Not sure how to resolve point 3)

**Comment by nmontoya03** [comment]
Hi @guilbep @ctobin111 Thank you for updating the database! For point 3), I think you can add an info icon (like the one you added for the grid EF - please see image below). The info icon would be in the source field for Emission Factor - Recycling/Reuse [kgCO2e/kg] and the message would be: The GHG Emission Calculator only considers Scope 1 and 2 emissions. All waste categories can be recycled/reused except nappies (diapers).

![image](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/131168517/a4e3de7e-e831-4116-a053-3f6aabf0afc7)

Thank you!

**Comment by guilbep** [comment]
okay! thanks @nmontoya03 I've added it to the csv, it's supposed to be in the 'ref'column 💯 https://docs.google.com/spreadsheets/d/1WvETvzsdFb1NuCPXt8xmfn1nQT_xYkbs/edit#gid=146266238

**Comment by guilbep** [comment]
done in [dev f21813f] feat(ghg): add reference by module #580

**Comment by guilbep** [comment]
@nmontoya03 @ctobin111 If you do some change in the google docs, please send me a message so I can update it
