### ISSUE TITLE
[FEATURE][GHG] Generator size #585

### ISSUE THREAD

**Issue by guilbep** [EPFL-ENAC/unhcr-geneva-tech-hub-app#585]
# Comments from Webinar to UNHCR COP 23 NOV 2023
- Use two input fields (one for kW, one for kVA) and use an assumed power factor to convert from one to the other - or we also add an insert field for power factor (with default)

**Comment by ctobin111** [comment]
@guilbep We discussed going from kV to kWh as an option for diesel generators.

A power factor is required and a standard power factor is generally 0.8. Source: [https://www.globalpwr.com/power-calculator/]

Here is the equation:

kVA * PF (Power factor) = kW

![image](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/111510926/ed24ec9e-0de6-4660-85df-ec7ef4552c95)

**Comment by guilbep** [comment]
done in [dev 5f8f9b9] feat(ghg): add kVA and kW automatic conversion ##585

**Comment by guilbep** [comment]
add A power factor is required and a standard power factor is generally 0.8. Source: [https://www.globalpwr.com/power-calculator/] to the reference file, partout ou on utilise generator (donc partout)

**Comment by guilbep** [comment]
done in [dev 572e962] feat(ghg): add REF_POW_FAC to the list of reference
