### ISSUE TITLE
[POLISH] Database tables should have unlimited rows per page

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/unhcr-geneva-tech-hub-app#59]
** Which part/screens of the tool? **
- DB tab
<img width="522" alt="Screenshot 2022-08-22 at 18 03 26" src="https://user-images.githubusercontent.com/18381609/185966717-76953c58-e394-460a-bed5-222ec3314426.png">

Don't limit the number of rows per page except if DB contains ≥ 50-100 rows.

**Comment by guilbep** [comment]
@charlottegiseleweil Since that part was implemented by @blueur, do you confirm that I should do it ?

**Comment by guilbep** [comment]
@charlottegiseleweil @blueur Do we want to do that for phase 1 ?

**Comment by charlottegiseleweil** [comment]
This should be done yes - can wait Phase 2 if it's leftovers from Phase 1

**Comment by guilbep** [comment]
I'm moving it to phase 2 then.

**Comment by guilbep** [comment]
@charlottegiseleweil It's breaking the css/behavior of vuetify.
And every table now has more than 36 items. I've added back the pagination to all the reference table.

made in: fb9ae80 (HEAD -> dev, origin/dev) fix(commons): add pagination to all tables to avoid scroll problem
