### ISSUE TITLE
[FEATURE] <GHG> Update fNRB dataset

### ISSUE THREAD

**Issue by nmontoya03** [EPFL-ENAC/unhcr-geneva-tech-hub-app#622]
Hi again @guilbep @ctobin111 

I'm storing in the following link the updated dataset for the fNRB values. Could you please kindly upload them in the tool?

https://epflch.sharepoint.com/:x:/r/sites/ENAC-IT/Documents%20partages/Research%20IT/Advanced%20Services/0041%20%E2%80%93%20UNHCR/PHASE_2/GHG/DATABASES/fNRB.csv?d=wdc91665f6b16410bada77858a3f9d112&csf=1&web=1&e=2QjMy3

The title for the dataset would be: fNRB (Fraction of non-renewable biomass) per country. Source: https://doi.org/10.1088/1748-9326/acb501

For the countries that are not listed in the database, the default value for fNRB is 30%. The source for this value is: https://cdm.unfccc.int/methodologies/PAmethodologies/tools/am-tool-30-v1.pdf

Thank you so much for your help!

**Comment by guilbep** [comment]
[ghg_fnrb.csv](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/files/14567561/ghg_fnrb.csv)
Thanks @nmontoya03  here is the csv with the isocode2 version that I'll be using in the code

**Comment by guilbep** [comment]
@nmontoya03 @ctobin111 by the way, if it's now 0.3 default for fNRB it means that I'm going to replace
the Fraction of Non renewable biomass (fNRB) in Emission Factors tab in the ghg_reference.csv
    "value": 0.85,
    "source": "https://cdm.unfccc.int/DNA/fNRB/index.html",

**Comment by guilbep** [comment]
done in [dev 8d37e62] feat(reference-data): update fnrb dataset #622
