### ISSUE TITLE
[FEATURE] <GHG: include percentage of carbon to leachate in code>

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#633]
@guilbep 

After a very rigorous Life Cycle Assessment and working with a solid waste management expert, we would like to add a multiplication factor in the code for the Solid Waste Management module. Basically, we would like to include 3% carbon going to leachate for solid waste emission factors: To represent this reduction on the emission factor, the equation for emissions in the solid waste module should be updated as follows:

CO2 Emissions (tCO2e/yr) = REF_EF_SWM * Material (gram/per person / per day) * 365.25 * Population (from general information tab)* %toGas / 1000000 (g/ton)

In the case of Open pits, unmanaged and Managed disposal sites, the parameter %toGas will be 0.97 (for bio and non-biowaste). For all the other alternatives, the parameter %toGas is 1.

**Comment by guilbep** [comment]
done like so:
    let percentToGas = 1;
    // only for Open pits, unmanaged and Managed disposal sites
    if ([openPits, managedDisposalSite].includes(practiceType)) {
      // https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/issues/633
      // After a very rigorous Life Cycle Assessment and working with a solid waste management expert,
      //we would like to add a multiplication factor in the code for the Solid Waste Management module.
      // Basically, we would like to include 3% carbon going to leachate for solid waste emission factors:
      // To represent this reduction on the emission factor, the equation for emissions in the solid waste
      //module should be updated as follows:
      percentToGas = 0.97;
    }
    
    

in commit 
[dev 35a81f2] feat(frontend): correct domestic solid waste formula #633 carbon to leachate

By the way @ctobin111  we use kg/per person /per day in the interface, not gram anymore
