### ISSUE TITLE
[FIX](GHG Grid DB): fix 'Add instructions'

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#634]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

@guilbep Hi Pierre, here is a readme file along with the sample xls files attached and zipped. I hope this will be ok for UNICC. I tested it and with the Developer tool in Excel, it is easy to do this.
[Grid_emission_factor.zip](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/files/14570238/Grid_emission_factor.zip)

**Comment by guilbep** [comment]
nothing to do
