### ISSUE TITLE
[FEATURE] <GHG: Add spacer links for LCA reports, maybe make subfolders>

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#635]
@guilbep Hi Pierre, as I mentioned there will be 5 static pdfs to upload below the guidance manual and tutorial videos. Would it be possible to have 3 folders when clicking on the question mark in the top right:

1) Guidance Manual
2) Tutorial Videos
3) Life Cycle Assessments

As I mentioned in the readme, there are 9 Tutorial videos, all being re-done due to the recent request of UNHCR.

We are finalizing the Life Cycle Assessment reports this week. There will be 5. Can they be listed as the following:

LCA Cooking (coming soon)
LCA Domestic Solid Waste (coming soon)
LCA Facilities (coming soon)
LCA Lighting (coming soon)
LCA Water Supply (coming soon)

**Comment by ctobin111** [comment]
@guilbep here are the pdf reports

[LCA_Facilities_GHG_Brief_Mar2024_vf.pdf](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/files/14745043/LCA_Facilities_GHG_Brief_Mar2024_vf.pdf)
[LCA_Water Supply_GHG_Brief_Mar2024_vf.pdf](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/files/14745046/LCA_Water.Supply_GHG_Brief_Mar2024_vf.pdf)
[LCA_SWM_GHG_Brief_Mar2024_vf.pdf](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/files/14745047/LCA_SWM_GHG_Brief_Mar2024_vf.pdf)
[LCA_Lighting_GHG_Brief_Mar2024_vf.pdf](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/files/14745048/LCA_Lighting_GHG_Brief_Mar2024_vf.pdf)
[LCA_Cooking_GHG_Brief_Mar2024_vf.pdf](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/files/14745049/LCA_Cooking_GHG_Brief_Mar2024_vf.pdf)

Can you kindly try to create a drop-down or subfolders to have 3 sections like in this diagram:
![Requested_Structure_QuestionMarkIcon_GHG_Tool](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/111510926/37105267-a513-4b0a-90cc-2e6acd6b24c3)

**Comment by guilbep** [comment]
add new links in [dev 50e64f57] fix(frontend): add new uri for videos #635

**Comment by guilbep** [comment]
done in https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/releases/tag/v1.16.0
no time for the new feature asked (drop-down with subfolder) though
