### ISSUE TITLE
[FIX](GHG Databases): fix 'Ember references'

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#643]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

@guilbep The Grid Emission Factors database does not open in a new window. Can you this be done?

Also, for the Emission Factors database for the modules (Facilities, Cooking, Lighting and WaterSupply) the old IGES database was referenced, so we need to replace the reference with EMBER anywhere it says the following:

"Energy - Electricity - Emission Factor - National Grid [kg CO2e/kWh]"

The Ember link is as follows:

[](https://ember-climate.org/data-catalogue/yearly-electricity-data/)

Merci!

**Comment by guilbep** [comment]
done in [dev a8b440d] fix(frontend): reference data updated for grid default #643
