### ISSUE TITLE
[FEATURE] <GHG - detail User Created ID>

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#644]
@guilbep 

As Manuel had requested, can you kindly do the following:

Put “User Created ID” next to the sites that are self-generated. I believe these are the non p-codes listed under the site name.

Thank you!

**Comment by guilbep** [comment]
<img width="353" alt="UserCreatedId" src="https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/161889/9b8638b3-0e82-470a-83bb-a1fd24af6ca5">
done in [dev e32b24d] feat(frontend): add User created id next to custom id #644
