### ISSUE TITLE
[FEATURE] <GHG UNHCR Locations database>

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#645]
@guilbep Can you kindly add this phrase to the top of the UNHCR Locations database:

"Data below have been provided by the UNHCR GIS division for the year 2022. The exception is the daily solar peak hour information."

And then continue with what is written.

Daily solar peak hours approximated using the Longterm daily average of global horizontal irradiation (GHI). (GHI data obtained from the Global Solar Atlas 2.0, a free, web-based application developed and operated by the company Solargis s.r.o. on behalf of the World Bank Group, utilizing Solargis data, with funding provided by the Energy Sector Management Assistance Program (ESMAP). For additional information: [globalsolaratlas.info](https://globalsolaratlas.info/))

Thank you.

**Comment by guilbep** [comment]
done in [dev 35f6706] feat(frontend): add new sentence in UNHCR locations #645
