### ISSUE TITLE
[FEATURE] <GHG Tool: Add titles to the cooking and lighting default values database>

### ISSUE THREAD

**Issue by nmontoya03** [EPFL-ENAC/unhcr-geneva-tech-hub-app#650]
@guilbep Could you please kindly add the following titles to the default values database?

Message for Lighting default values:

Default values for fuel consumption were calculated assuming 3.9 hours/day as the lighting demand (Source: doi: 10.1016/j.deveng.2020.100056).

Message for Cooking default values:

The default values of consumption assume the energy demand for cooking is met by the primary cooking solution. The default value for firewood consumption was used to calculate other fuels’ consumption together with the net calorific value (NCV) and the cookstove efficiency (except for biogas and piped natural gas). Except where otherwise indicated, the values for NCV and assumed cookstove efficiency were taken from the following links respectively:
https://www.ipcc-nggip.iges.or.jp/public/2006gl/pdf/2_Volume2/V2_1_Ch1_Introduction.pdf
https://cfpub.epa.gov/si/si_public_record_report.cfm?Lab=NRMRL&dirEntryId=339679
Details on the calculations and assumptions are available in the User’s Manual.

Thank you! I also created the pull request for updating the database, could you please let me know if you have any problem to see the changes?

Best,

Natalia.

**Comment by guilbep** [comment]
Thanks @nmontoya03 it's done on dev, 
I'm going to deploy to prod tomorrow morning:

done in [dev 94254a73] feat(frontend): add subtitle for cooking and lighting
