### ISSUE TITLE
Project list page improvements

### ISSUE THREAD

**Issue by andreullal** [EPFL-ENAC/unhcr-geneva-tech-hub-app#69]
- [x] Add the email address (username) of project owner and date created to the project card information. Small text, italic, as last item on the project card.
- [x] Filtering project list by country or countries (dropdown list of countries with checkboxes enabling one or more countries

**Comment by andreullal** [comment]
![1_Enhancements_ProjList_](https://user-images.githubusercontent.com/108796343/195061863-3019ced7-1738-46a6-8192-9bc5da3e590b.png)

**Comment by guilbep** [comment]
Closed by merging #121
