### ISSUE TITLE
[FEATURE] Tests e2e cypress/ basic authentication

### ISSUE THREAD

**Issue by guilbep** [EPFL-ENAC/unhcr-geneva-tech-hub-app#7]
We should implement with cypress basic tests for the following user flow

- [ ]  Login/logout (unhcr + guest + custom)
- [ ]  Shelter tool
    - [ ]  Create/Delete/Edit shelter
    - [ ]  READ ONLY same thing than above but with guest user
    - [ ]  same thing bug for unhcr user
- [ ]  Scorecards/results

**Comment by charlottegiseleweil** [comment]
to merge
