### ISSUE TITLE
File upload and storage - images and technical drawings.

### ISSUE THREAD

**Issue by andreullal** [EPFL-ENAC/unhcr-geneva-tech-hub-app#70]
The app will also function as a repository of design information about different shelter designs, including technical drawings and images. In the Project Information page, Users enable uploading of files. Image files: pdf, jps, tiff, etc. 

When uploading, Users should label the file: 1) Image, 2) drawings - floor plan, 3) drawings, roof plan, 4) drawing - section, 5) drawing - elevation. One file might contain multiple drawings, so Users should be able to attach multiple labels to a file.

Uploaded files should then appear as labeled thumbnails that can be: 1) viewed in pop-up window, or 2) downloaded.

- [x] commit the 'authentication' verification on the upload-fast-api; it should check with couchdb that the user is authenticated.
- [x] Remove unnecessary changes inside AboutView
- [x] Add the image in the 'comparison page' Will be done #197
- [x] protect for prject when not a project user --> non owner should have a read only view

- [x] have an option for download
- [x] have an option for deleting

- [x] rename label to be Type of image instead of Select type of image depending on user rights
- [x] the name should be editable with an icon btn (with a subtext that says: press escape or enter when finished)
- [x] add pdf support
- [x] adding new files, will not delete the previously uploaded files
- [x] the success notification should only be displayed once the file is correctly retrieved from the serve
- [x] add a spining wheel or / processing in progress thing for upload and delete
- [x] Add a gray square: with text in white saying: 'Thumbnail not available'
- [x] add an error message in the front end when file fail to upload
- [x] Max 10 Megabytes, and max 10 files per project/shelter
- [x] Add any kind of format --> with a type like: 'Other' with a detail like ' let's try it anyway (chose the type in frontend)
- [x] new types:  Image / Drawing / Report / Other
- [x] Add a 'description field'  200 characters max (small text, under the title)
- [x] Instead of a cross it should be a valid icon mdiCheck
BONUS:
- [x] s3 cleanup -> delete endpoints on the api to clean the s3 bucket
- [x] do not remove existing images when uploading again
- [x] Sanity check --> add a script that retrieve all the s3 images in the database: the goal is to have a list of file not to remove in s3>

**Comment by andreullal** [comment]
@guilbep 

![4_Respository_-01](https://user-images.githubusercontent.com/108796343/205515195-112344f1-92cd-47d9-a601-a379e3b4d264.png)
![4_Respository_-02](https://user-images.githubusercontent.com/108796343/205515196-bd3f269f-96d2-4442-83be-6e11212c3698.png)
![4_Respository_-03](https://user-images.githubusercontent.com/108796343/205515197-2ae546cb-875f-47f0-9a4c-008d66febe6a.png)

**Comment by guilbep** [comment]
@andreullal Okay!

**Comment by andreullal** [comment]
Example to edit name of file in list of uploads:

<img width="756" alt="Screenshot 2023-01-19 at 11 07 11" src="https://user-images.githubusercontent.com/108796343/213414493-9e24d6e8-67c6-45ce-92eb-47b58704aeaa.png">
<img width="756" alt="Screenshot 2023-01-19 at 11 07 27" src="https://user-images.githubusercontent.com/108796343/213414503-c985bbbf-585d-4b56-9449-35ddc1e8333e.png">

**Comment by guilbep** [comment]
By the way @andreullal It has been deployed to production and test platform. It's not pretty. But all the functionnality are there. If you want to test. I'll improve the design tomorrow. Please come forward if you see any thing wrong.

**Comment by guilbep** [comment]
<img width="1508" alt="edit-mode-list-upload" src="https://user-images.githubusercontent.com/161889/217853103-52845fec-13a0-4ae3-9bf4-6469105a4595.png">
<img width="1368" alt="upload-file" src="https://user-images.githubusercontent.com/161889/217853129-bc585f0c-cf13-455e-b3bf-fdc25aaf1a53.png">
By the way @andreullal here are screenshots for read-only and edit mode for the upload.
