### ISSUE TITLE
[FEATURE] Set up Monitoring/Analytics

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/unhcr-geneva-tech-hub-app#76]
Setup GAnalytics to track usage of the tool .

**Comment by charlottegiseleweil** [comment]
@guilbep you mentioned in issue #37 that we don't have an issue for setting up GAnalytics, but we do, it's this one !

**Comment by charlottegiseleweil** [comment]
@guilbep coucou !

**Comment by guilbep** [comment]
Done in feat/76 branch.
Monitoring of the app is following in issue #37
