### ISSUE TITLE
[FEATURE] <GHG Report generation>

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/unhcr-geneva-tech-hub-app#77]
@ctobin111 - can you describe the contents you'd expect (with template layout ideally) for the report ?

**Comment by guilbep** [comment]
I'm closing this issue, because all of the above questions were answered here: https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/issues/85 #85

**Comment by charlottegiseleweil** [comment]
@ctobin111

**Comment by ctobin111** [comment]
@charlottegiseleweil and @guilbep The UNHCR energy and WASH technical groups do not yet have a clear idea on how they want report generation. Ideally they can print the results page. I will come back to this issue  @ctobin111

**Comment by guilbep** [comment]
duplicate of #277 closing
