### ISSUE TITLE
BOQ xls file upload instead of in-app data entry

### ISSUE THREAD

**Issue by andreullal** [EPFL-ENAC/unhcr-geneva-tech-hub-app#79]
- [ ] Define template xls file that features all the same options of the app BOQ @andreullal 
- [ ] Add to the BOQ page a button enabling download of the xls template
- [ ] Add to the BOQ page a button enabling uplaod of a completed xls BOQ
- [ ] Add a note stating that the XLS BOQ must use template
- [ ] Add function to reject any incorrect file

cf

Format of output BOQ:

[1_Enhancements_OutputBOQ.xlsx](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/files/9803974/1_Enhancements_OutputBOQ.xlsx)

**Comment by andreullal** [comment]
Format of output BOQ:

[1_Enhancements_OutputBOQ.xlsx](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/files/9803974/1_Enhancements_OutputBOQ.xlsx)

**Comment by andreullal** [comment]
@guilbep @charlottegiseleweil 

We should separate this issue into:
1) BOQ xls file upload instead of in-app data entry (on hold since it seems unfeasible within time constraints)
2) BOQ xls file download (proceed using the standard output xls file attached to the previous comment.

**Comment by andreullal** [comment]
BOQ file download is covered in issue 85. 

No need to continue with BOQ file upload (as an alternative to in-app BOQ data entry) - the benefit is minimal compared to amount of work involved. I'll explain this to UNHCR (who requested the BOQ upload functionality).

**Comment by guilbep** [comment]
@andreullal for the upload do you think we will have time for the next phase ?

**Comment by andreullal** [comment]
@guilbep  I think no, no need to proceed with this - we can close the issue. The effort required far exceeds the potential benefit.
