### ISSUE TITLE
[CHORE] remove user list on github

### ISSUE THREAD

**Issue by guilbep** [EPFL-ENAC/unhcr-geneva-tech-hub-app#8]
- Remove user list on git
- Non-versionned script to add default user (move somewhere else)
- Ability for user to change their password

Teste with PouchDB Authentication, but changing password seem not possible (maybe due to user rights on _users database : [https://github.com/pouchdb-community/pouchdb-authentication](https://github.com/pouchdb-community/pouchdb-authentication)

**Comment by charlottegiseleweil** [comment]
@blueur can you handle this by mid-March ?

**Comment by blueur** [comment]
Why not just changing all passwords ?
