### ISSUE TITLE
Environmental performance page improvements

### ISSUE THREAD

**Issue by andreullal** [EPFL-ENAC/unhcr-geneva-tech-hub-app#81]
- [x] In table, vertically align headings Material, Material weight, and Embodied water
- [x] In table, add line under Material column header (to make same as other columns
- [x] #131
- [x] USe 2 columns for Habitat Risks and Reuse and Recycling considerations
- [x] Embodied carbon column unit = kgCO2e - NOT kgCO2e/kg

**Comment by andreullal** [comment]
![1_Enhancements_EP_](https://user-images.githubusercontent.com/108796343/195055778-d623a1d7-a736-49c4-80c5-4600d2a265d0.png)

**Comment by andreullal** [comment]
Alternative chart types: 1) treemap (i.e. what we have now), 2) sunburst (see picture below), 3) sankey (see picture below - materials on one side, forms on other).

![Screenshot 2022-10-17 at 22 08 13](https://user-images.githubusercontent.com/108796343/196273946-cf80d1de-abe1-4e29-83da-ea47a843cad1.png)
![Screenshot 2022-10-17 at 22 08 27](https://user-images.githubusercontent.com/108796343/196273979-656f1782-ba91-4cee-9ff1-6b46d66d28f4.png)

**Comment by andreullal** [comment]
@guilbep - alternative chart types and mode/layout of selection described in images in above post.

**Comment by guilbep** [comment]
done in commit 29c024e
