### ISSUE TITLE
Technical performance page improvements

### ISSUE THREAD

**Issue by andreullal** [EPFL-ENAC/unhcr-geneva-tech-hub-app#82]
- [x] ~~Flood mitigation - present flood risk (from Project Information) and add popup/hover text of Information/advice~~
- [x] ~~Seismic resistance - present seismic risk (from Project Information) and add popup/hover text of Information/advice~~
- [x] Internal comfort/natural ventilation - automatic calculation/assessment of ratio window area : floor area based on Geometry output (floor area and windows area) (edit done in #72)
- [x] Personal security - automatic assessment of window openings dimension based on Geometry input (Windows area)

**Comment by andreullal** [comment]
Flood mitigation and seismic risk changes removed.

**Comment by guilbep** [comment]
Closed by 55b061a released in v0.3.0
