### ISSUE TITLE
Scorecard improvements

### ISSUE THREAD

**Issue by andreullal** [EPFL-ENAC/unhcr-geneva-tech-hub-app#84]
- [x] Enable filtering by: shelter type, country, year (of assessment)
- [x] Provide advice (text) for interpretation of results @andreullal 
- [x] Keep selected scorecard in filtering

**Comment by andreullal** [comment]
![Image](https://user-images.githubusercontent.com/108796343/195076998-96793204-1191-4e29-a7cc-0d3ed2988a98.png)

**Comment by guilbep** [comment]
@andreullal I think I still need the.'Provide advice (text) for interpretation of results' on your part ?

**Comment by guilbep** [comment]
@andreullal Sorry if I did not come up earlier. But I think I find it strange than when we fillter some shelter_type or other. It filters out the selected Shelter.
Should it work like that ? or not ? I guest we should always keep the selected shelter ?

what do you think ?

**Comment by andreullal** [comment]
Yes, I agree, we should always keep the selected shelter.

**Comment by guilbep** [comment]
done in commit ee161bd
