### ISSUE TITLE
Side-by-side shelter comparison

### ISSUE THREAD

**Issue by andreullal** [EPFL-ENAC/unhcr-geneva-tech-hub-app#86]
Enable selection of 2 or 3 shelters and the assessment results of these shelters to be presented side-by-side (similar to product comparisons in commerce websites). Would require shelters to be selected from the project list page. Perhaps a button for "compare shelters", which then brings up check-boxes to selected 2 or 3 projects for comparison.

Enable download of a standard pdf report of the comparison.

- [ ] Design screenshot/function of the selection @andreullal 
- [ ] Design screenshots of the comparison @andreullal 
- [ ] Design output report @andreullal 
- [ ] Implement

**Comment by guilbep** [comment]
closed because duplicate of #120
