### ISSUE TITLE
Compile and report user statistics

### ISSUE THREAD

**Issue by andreullal** [EPFL-ENAC/unhcr-geneva-tech-hub-app#87]
- [ ] Enable saving of user statistics - say, number of users, number of projects, average number of projects per user, average time spent per project. 
- [ ] Enable onscreen reporting of user statistics to Admin users

**Comment by andreullal** [comment]
@guilbep  User stats accessible via the same analysis tab as global project stats:

![3_GlobSum_-03](https://user-images.githubusercontent.com/108796343/205513210-a3620ed9-598f-45c1-817a-909442551508.png)

**Comment by guilbep** [comment]
We don't need this issue anymore since we decided that the user /report statistics will be displayed in the overview data screen
https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/issues/164
