### ISSUE TITLE
[FEATURE] (Facilities) <Put in Other option in case other alternative energies are used>

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#89]
In the 4 energy modules, put in an 'Other' option to be read as a column with kWh as the unit. More information will be provided.

**Comment by guilbep** [comment]
@ctobin111 is it still relevant ?

**Comment by ctobin111** [comment]
@guilbep UNHCR has not provided more detail on this so we can leave this as closed for now. We will see what they say from the field trials. Thank you.
