### ISSUE TITLE
[FIX] (Facilities) <Energy Mix lumped in kWh is not correct for solar>

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#90]
@guilbep, the solar column (column 3 with the new title) is actually only in kW. I am getting a database with average solar hours per location from the HomerPro software. We need to discuss how this database can be easiest uploaded. Perhaps this has been done by David with Edgard. The kW must be multiplied by the number of solar hours to get to kWh in order to have a fair comparison with the diesel and grid.

Energy mix is provided as a pie chart in only kWh. So all three columns in Facilities will then be in kWh and can be compared in the pie chart correctly.

**Comment by guilbep** [comment]
Cf issue #107 comment: 
>Yes, please see issue https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/issues/90
Eventually, column 5 will have to be multiplied by the number of solar hours per site. Just as we are reading in coordinates, site names, populations to each site with the API to be provided by UNHCR, I will try to see if we can read in the solar hours also. I need to get this information from an open-source database like Homer Pro.

**Comment by guilbep** [comment]
@ctobin111 I'll need a csv or something similar to upload the data

**Comment by guilbep** [comment]
@ctobin111 Did you put the dataset inside the gdrive ? I cannot find it

**Comment by ctobin111** [comment]
@guilbep Please see the database uploaded on Issue #194

**Comment by guilbep** [comment]
[Solar_Daily_Hours_UNHCR_Refugge_Locations_03_02_2023.xlsx](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/files/10576743/Solar_Daily_Hours_UNHCR_Refugge_Locations_03_02_2023.xlsx)

By the way @ctobin111 I recomputed the average and I ended up with: "default": 5.317878598

**Comment by guilbep** [comment]
done in * 35cf39f feat(ghg): add solar information to site
