### ISSUE TITLE
Provide user instructions/manual/video - André

### ISSUE THREAD

**Issue by guilbep** [EPFL-ENAC/unhcr-geneva-tech-hub-app#91]

**Comment by guilbep** [comment]
march 2023

**Comment by charlottegiseleweil** [comment]
@andreullal we're still waiting on user manual to include in your tool !

**Comment by andreullal** [comment]
@guilbep . Here's a first video for testing. Please take a look and let me know if there's anything that should be changed before I go ahead with the other videos.


https://user-images.githubusercontent.com/108796343/226344405-c05f0db3-feb1-4e14-849f-90a1503716db.mp4

**Comment by andreullal** [comment]
@guilbep 

11x instruction videos are on the project google drive at: 

https://drive.google.com/drive/folders/1wrzt8TAQbO3o0Aj5JZnYQxKEn_uyj5QC?usp=sharing

They're in mp4 format and larger files sizes (I assume), though I expect you would have to optimise them anyway. 

Still one more video to do - on uploading and downloading files.

**Comment by guilbep** [comment]
Uploaded and made available; just need to fix a small thing regarding the videos still playing when closed
